// Generated by scripts/generate-error-codes.py. Do not edit.

export const errorCatalog = {
  "adapter.api_call_failed": {
    "messageKey": "errors.adapter.api_call_failed",
    "httpStatus": 502,
    "retryable": true
  },
  "adapter.auth_failed": {
    "messageKey": "errors.adapter.auth_failed",
    "httpStatus": 401,
    "retryable": false
  },
  "adapter.capability_unsupported": {
    "messageKey": "errors.adapter.capability_unsupported",
    "httpStatus": 400,
    "retryable": false
  },
  "adapter.connection_failed": {
    "messageKey": "errors.adapter.connection_failed",
    "httpStatus": 503,
    "retryable": true
  },
  "adapter.connection_lost": {
    "messageKey": "errors.adapter.connection_lost",
    "httpStatus": 503,
    "retryable": true
  },
  "adapter.matrix_projection_failed": {
    "messageKey": "errors.adapter.matrix_projection_failed",
    "httpStatus": 500,
    "retryable": true
  },
  "adapter.message_quota_exceeded": {
    "messageKey": "errors.adapter.message_quota_exceeded",
    "httpStatus": 429,
    "retryable": true
  },
  "adapter.provider_extension_not_supported": {
    "messageKey": "errors.adapter.provider_extension_not_supported",
    "httpStatus": 501,
    "retryable": false
  },
  "adapter.reply_target_missing": {
    "messageKey": "errors.adapter.reply_target_missing",
    "httpStatus": 409,
    "retryable": false
  },
  "adapter.reply_window_expired": {
    "messageKey": "errors.adapter.reply_window_expired",
    "httpStatus": 409,
    "retryable": false
  },
  "adapter.send_failed": {
    "messageKey": "errors.adapter.send_failed",
    "httpStatus": 502,
    "retryable": true
  },
  "adapter.send_unconfirmed": {
    "messageKey": "errors.adapter.send_unconfirmed",
    "httpStatus": 504,
    "retryable": false
  },
  "adapter.transport_forward_ws_connection_failed": {
    "messageKey": "errors.adapter.transport_forward_ws_connection_failed",
    "httpStatus": 503,
    "retryable": true
  },
  "adapter.transport_forward_ws_session_lost": {
    "messageKey": "errors.adapter.transport_forward_ws_session_lost",
    "httpStatus": 503,
    "retryable": true
  },
  "adapter.transport_http_api_auth_failed": {
    "messageKey": "errors.adapter.transport_http_api_auth_failed",
    "httpStatus": 401,
    "retryable": false
  },
  "adapter.transport_http_api_invalid_response": {
    "messageKey": "errors.adapter.transport_http_api_invalid_response",
    "httpStatus": 502,
    "retryable": true
  },
  "adapter.transport_http_api_request_failed": {
    "messageKey": "errors.adapter.transport_http_api_request_failed",
    "httpStatus": 502,
    "retryable": true
  },
  "adapter.transport_not_implemented": {
    "messageKey": "errors.adapter.transport_not_implemented",
    "httpStatus": 501,
    "retryable": false
  },
  "adapter.transport_reverse_ws_auth_failed": {
    "messageKey": "errors.adapter.transport_reverse_ws_auth_failed",
    "httpStatus": 401,
    "retryable": false
  },
  "adapter.transport_reverse_ws_upgrade_failed": {
    "messageKey": "errors.adapter.transport_reverse_ws_upgrade_failed",
    "httpStatus": 503,
    "retryable": true
  },
  "adapter.transport_unavailable": {
    "messageKey": "errors.adapter.transport_unavailable",
    "httpStatus": 503,
    "retryable": false
  },
  "adapter.transport_webhook_auth_failed": {
    "messageKey": "errors.adapter.transport_webhook_auth_failed",
    "httpStatus": 401,
    "retryable": false
  },
  "adapter.transport_webhook_duplicate_event": {
    "messageKey": "errors.adapter.transport_webhook_duplicate_event",
    "httpStatus": 202,
    "retryable": false
  },
  "adapter.transport_webhook_invalid_payload": {
    "messageKey": "errors.adapter.transport_webhook_invalid_payload",
    "httpStatus": 400,
    "retryable": false
  },
  "permission.authentication_required": {
    "messageKey": "errors.permission.authentication_required",
    "httpStatus": 401,
    "retryable": false
  },
  "permission.blacklisted": {
    "messageKey": "errors.permission.blacklisted",
    "httpStatus": 403,
    "retryable": false
  },
  "permission.current_secret_invalid": {
    "messageKey": "errors.permission.current_secret_invalid",
    "httpStatus": 403,
    "retryable": false
  },
  "permission.denied": {
    "messageKey": "errors.permission.denied",
    "httpStatus": 403,
    "retryable": false
  },
  "permission.not_whitelisted": {
    "messageKey": "errors.permission.not_whitelisted",
    "httpStatus": 403,
    "retryable": false
  },
  "permission.unavailable": {
    "messageKey": "errors.permission.unavailable",
    "httpStatus": null,
    "retryable": true
  },
  "platform.internal_error": {
    "messageKey": "errors.platform.internal_error",
    "httpStatus": 500,
    "retryable": true
  },
  "platform.invalid_config": {
    "messageKey": "errors.platform.invalid_config",
    "httpStatus": 400,
    "retryable": false
  },
  "platform.invalid_request": {
    "messageKey": "errors.platform.invalid_request",
    "httpStatus": 400,
    "retryable": false
  },
  "platform.rate_limited": {
    "messageKey": "errors.platform.rate_limited",
    "httpStatus": 429,
    "retryable": true
  },
  "platform.render_input_too_large": {
    "messageKey": "errors.platform.render_input_too_large",
    "httpStatus": 413,
    "retryable": false
  },
  "platform.render_queue_full": {
    "messageKey": "errors.platform.render_queue_full",
    "httpStatus": 429,
    "retryable": true
  },
  "platform.render_timeout": {
    "messageKey": "errors.platform.render_timeout",
    "httpStatus": 504,
    "retryable": true
  },
  "platform.resource_busy": {
    "messageKey": "errors.platform.resource_busy",
    "httpStatus": 409,
    "retryable": true
  },
  "platform.resource_missing": {
    "messageKey": "errors.platform.resource_missing",
    "httpStatus": 503,
    "retryable": false
  },
  "platform.resource_not_found": {
    "messageKey": "errors.platform.resource_not_found",
    "httpStatus": 404,
    "retryable": false
  },
  "platform.state_conflict": {
    "messageKey": "errors.platform.state_conflict",
    "httpStatus": 409,
    "retryable": false
  },
  "platform.task_queue_full": {
    "messageKey": "errors.platform.task_queue_full",
    "httpStatus": 429,
    "retryable": true
  },
  "platform.task_timeout": {
    "messageKey": "errors.platform.task_timeout",
    "httpStatus": 504,
    "retryable": true
  },
  "platform.template_not_found": {
    "messageKey": "errors.platform.template_not_found",
    "httpStatus": 404,
    "retryable": false
  },
  "platform.third_party_account_not_found": {
    "messageKey": "errors.platform.third_party_account_not_found",
    "httpStatus": 404,
    "retryable": false
  },
  "platform.upstream_request_failed": {
    "messageKey": "errors.platform.upstream_request_failed",
    "httpStatus": 502,
    "retryable": true
  },
  "platform.upstream_response_too_large": {
    "messageKey": "errors.platform.upstream_response_too_large",
    "httpStatus": 502,
    "retryable": false
  },
  "platform.user_rate_limited": {
    "messageKey": "errors.platform.user_rate_limited",
    "httpStatus": 429,
    "retryable": true
  },
  "platform.value_too_large": {
    "messageKey": "errors.platform.value_too_large",
    "httpStatus": 413,
    "retryable": false
  },
  "plugin.artifact_invalid": {
    "messageKey": "errors.plugin.artifact_invalid",
    "httpStatus": 400,
    "retryable": false
  },
  "plugin.contract_unsupported": {
    "messageKey": "errors.plugin.contract_unsupported",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.core_version_incompatible": {
    "messageKey": "errors.plugin.core_version_incompatible",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.event_canceled": {
    "messageKey": "errors.plugin.event_canceled",
    "httpStatus": null,
    "retryable": false
  },
  "plugin.event_timeout": {
    "messageKey": "errors.plugin.event_timeout",
    "httpStatus": null,
    "retryable": true
  },
  "plugin.init_timeout": {
    "messageKey": "errors.plugin.init_timeout",
    "httpStatus": null,
    "retryable": true
  },
  "plugin.install_digest_mismatch": {
    "messageKey": "errors.plugin.install_digest_mismatch",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.install_failed": {
    "messageKey": "errors.plugin.install_failed",
    "httpStatus": 409,
    "retryable": true
  },
  "plugin.install_inspection_expired": {
    "messageKey": "errors.plugin.install_inspection_expired",
    "httpStatus": 409,
    "retryable": true
  },
  "plugin.install_inspection_required": {
    "messageKey": "errors.plugin.install_inspection_required",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.internal_error": {
    "messageKey": "errors.plugin.internal_error",
    "httpStatus": null,
    "retryable": false
  },
  "plugin.management_action_failed": {
    "messageKey": "errors.plugin.management_action_failed",
    "httpStatus": 502,
    "retryable": false
  },
  "plugin.not_handled": {
    "messageKey": "errors.plugin.not_handled",
    "httpStatus": null,
    "retryable": false
  },
  "plugin.not_recoverable": {
    "messageKey": "errors.plugin.not_recoverable",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.package_resource_limit_exceeded": {
    "messageKey": "errors.plugin.package_resource_limit_exceeded",
    "httpStatus": 413,
    "retryable": false
  },
  "plugin.package_unsafe_entry": {
    "messageKey": "errors.plugin.package_unsafe_entry",
    "httpStatus": 400,
    "retryable": false
  },
  "plugin.permission_denied": {
    "messageKey": "errors.plugin.permission_denied",
    "httpStatus": 403,
    "retryable": false
  },
  "plugin.platform_mismatch": {
    "messageKey": "errors.plugin.platform_mismatch",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.protocol_violation": {
    "messageKey": "errors.plugin.protocol_violation",
    "httpStatus": null,
    "retryable": false
  },
  "plugin.settings_apply_failed": {
    "messageKey": "errors.plugin.settings_apply_failed",
    "httpStatus": 409,
    "retryable": true
  },
  "plugin.shutdown_timeout": {
    "messageKey": "errors.plugin.shutdown_timeout",
    "httpStatus": null,
    "retryable": true
  },
  "plugin.stopping": {
    "messageKey": "errors.plugin.stopping",
    "httpStatus": null,
    "retryable": false
  },
  "plugin.store_catalog_unavailable": {
    "messageKey": "errors.plugin.store_catalog_unavailable",
    "httpStatus": 503,
    "retryable": true
  },
  "plugin.store_integrity_mismatch": {
    "messageKey": "errors.plugin.store_integrity_mismatch",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.store_release_unavailable": {
    "messageKey": "errors.plugin.store_release_unavailable",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.store_source_conflict": {
    "messageKey": "errors.plugin.store_source_conflict",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.store_source_immutable": {
    "messageKey": "errors.plugin.store_source_immutable",
    "httpStatus": 409,
    "retryable": false
  },
  "plugin.trusted_code_confirmation_required": {
    "messageKey": "errors.plugin.trusted_code_confirmation_required",
    "httpStatus": 403,
    "retryable": false
  },
  "plugin.uninstall_failed": {
    "messageKey": "errors.plugin.uninstall_failed",
    "httpStatus": 409,
    "retryable": true
  },
  "plugin.webhook_replay_rejected": {
    "messageKey": "errors.plugin.webhook_replay_rejected",
    "httpStatus": 401,
    "retryable": false
  },
  "plugin.webhook_timestamp_skew": {
    "messageKey": "errors.plugin.webhook_timestamp_skew",
    "httpStatus": 401,
    "retryable": false
  },
  "release.artifact_invalid": {
    "messageKey": "errors.release.artifact_invalid",
    "httpStatus": 502,
    "retryable": false
  },
  "release.disk_space_insufficient": {
    "messageKey": "errors.release.disk_space_insufficient",
    "httpStatus": 507,
    "retryable": true
  },
  "release.install_failed": {
    "messageKey": "errors.release.install_failed",
    "httpStatus": 500,
    "retryable": true
  },
  "release.manifest_expired": {
    "messageKey": "errors.release.manifest_expired",
    "httpStatus": 409,
    "retryable": true
  },
  "release.manifest_invalid": {
    "messageKey": "errors.release.manifest_invalid",
    "httpStatus": 502,
    "retryable": false
  },
  "release.replay_rejected": {
    "messageKey": "errors.release.replay_rejected",
    "httpStatus": 409,
    "retryable": false
  },
  "release.rollback_failed": {
    "messageKey": "errors.release.rollback_failed",
    "httpStatus": 500,
    "retryable": false
  },
  "release.signature_invalid": {
    "messageKey": "errors.release.signature_invalid",
    "httpStatus": 502,
    "retryable": false
  },
  "release.trust_required": {
    "messageKey": "errors.release.trust_required",
    "httpStatus": 409,
    "retryable": false
  },
  "release.update_not_supported": {
    "messageKey": "errors.release.update_not_supported",
    "httpStatus": 409,
    "retryable": false
  }
} as const

export const errorMessages = {
  "adapter": {
    "api_call_failed": "协议 API 调用失败",
    "auth_failed": "协议鉴权失败",
    "capability_unsupported": "当前适配器不支持该能力",
    "connection_failed": "协议连接建立失败",
    "connection_lost": "协议连接已断开",
    "matrix_projection_failed": "协议兼容矩阵生成失败",
    "message_quota_exceeded": "主动推送额度已用完",
    "provider_extension_not_supported": "当前 provider 扩展能力尚未实现",
    "reply_target_missing": "回复目标不存在或已失效",
    "reply_window_expired": "消息回复时限已过",
    "send_failed": "消息发送失败",
    "send_unconfirmed": "消息发送结果未确认",
    "transport_forward_ws_connection_failed": "OneBot 主动连接建立失败",
    "transport_forward_ws_session_lost": "OneBot 主动连接已断开",
    "transport_http_api_auth_failed": "OneBot HTTP API 鉴权失败",
    "transport_http_api_invalid_response": "OneBot HTTP API 响应不合法",
    "transport_http_api_request_failed": "OneBot HTTP API 请求失败",
    "transport_not_implemented": "当前协议传输模式尚未实现",
    "transport_reverse_ws_auth_failed": "OneBot 回连鉴权失败",
    "transport_reverse_ws_upgrade_failed": "OneBot 回连升级失败",
    "transport_unavailable": "适配器传输当前不可用",
    "transport_webhook_auth_failed": "OneBot Webhook 鉴权失败",
    "transport_webhook_duplicate_event": "OneBot Webhook 重复事件已丢弃",
    "transport_webhook_invalid_payload": "OneBot Webhook 负载不合法"
  },
  "permission": {
    "authentication_required": "请求认证未通过",
    "blacklisted": "当前用户或群处于黑名单中",
    "current_secret_invalid": "当前密码不正确",
    "denied": "当前用户无权执行该操作",
    "not_whitelisted": "当前用户或群不在白名单中",
    "unavailable": "暂时无法确认权限，本次操作未执行"
  },
  "platform": {
    "internal_error": "内部错误",
    "invalid_config": "配置校验失败",
    "invalid_request": "请求参数不合法",
    "rate_limited": "触发平台级限流",
    "render_input_too_large": "渲染输入超过大小限制",
    "render_queue_full": "渲染队列已满",
    "render_timeout": "渲染任务超时",
    "resource_busy": "资源正被占用，请稍后重试",
    "resource_missing": "缺少必要资源",
    "resource_not_found": "请求的资源不存在",
    "state_conflict": "当前状态不允许执行该操作",
    "task_queue_full": "后台任务队列已满",
    "task_timeout": "后台任务超时",
    "template_not_found": "模板不存在",
    "third_party_account_not_found": "三方账号不存在或尚未配置凭据",
    "upstream_request_failed": "上游请求失败",
    "upstream_response_too_large": "上游响应超过大小限制",
    "user_rate_limited": "用户命令触发冷却限流",
    "value_too_large": "写入值超过大小限制"
  },
  "plugin": {
    "artifact_invalid": "插件产物结构或入口校验失败",
    "contract_unsupported": "插件合同版本不受支持",
    "core_version_incompatible": "插件与当前 RayleaBot 版本不兼容",
    "event_canceled": "插件事件处理已取消",
    "event_timeout": "插件事件处理超时",
    "init_timeout": "插件初始化超时",
    "install_digest_mismatch": "插件包与检查结果不一致",
    "install_failed": "插件安装失败",
    "install_inspection_expired": "插件包检查结果已过期",
    "install_inspection_required": "请先检查插件包并确认信任",
    "internal_error": "插件内部处理异常",
    "management_action_failed": "插件管理操作执行失败",
    "not_handled": "插件声明不处理该事件",
    "not_recoverable": "插件当前不可恢复",
    "package_resource_limit_exceeded": "插件包超过资源限制",
    "package_unsafe_entry": "插件包包含不安全文件",
    "permission_denied": "插件访问未声明权限",
    "platform_mismatch": "插件产物与当前平台不匹配",
    "protocol_violation": "插件协议违规",
    "settings_apply_failed": "设置已保存，运行时应用失败，请重试保存或重载插件",
    "shutdown_timeout": "插件优雅退出超时",
    "stopping": "插件正在停止，不再接受新动作",
    "store_catalog_unavailable": "插件商店目录暂不可用",
    "store_integrity_mismatch": "插件商店产物与目录摘要不一致",
    "store_release_unavailable": "当前平台没有可安装的插件商店产物",
    "store_source_conflict": "插件源地址已存在",
    "store_source_immutable": "官方插件源不能修改或删除",
    "trusted_code_confirmation_required": "必须确认该插件将作为完全可信的本地代码运行",
    "uninstall_failed": "插件卸载失败",
    "webhook_replay_rejected": "插件 Webhook 请求已被识别为重复事件",
    "webhook_timestamp_skew": "插件 Webhook 请求时间戳超出容忍窗口"
  },
  "release": {
    "artifact_invalid": "更新包完整性或签名验证失败",
    "disk_space_insufficient": "磁盘空间不足",
    "install_failed": "更新安装失败",
    "manifest_expired": "发布清单已过期",
    "manifest_invalid": "发布清单无效",
    "replay_rejected": "已拒绝旧版或被替换的发布清单",
    "rollback_failed": "更新回滚失败",
    "signature_invalid": "发布签名验证失败",
    "trust_required": "当前安装不具备自动更新信任基线",
    "update_not_supported": "当前平台仅支持引导更新"
  }
} as const
