import type { components } from './generated'

export type PluginRegistrationState = components['schemas']['PluginRegistrationState']
export type PluginDesiredState = components['schemas']['PluginDesiredState']
export type PluginRuntimeState = components['schemas']['PluginRuntimeState']
export type PluginRole = components['schemas']['PluginRole']
export type PluginTrustLevel = components['schemas']['PluginTrustSummary']['level']
export type PluginInstallSourceType = components['schemas']['PluginInstallRequest']['source_type']
export type PluginSourceSummary = components['schemas']['PluginSourceSummary']
export type PluginTrustSummary = components['schemas']['PluginTrustSummary']
export type PluginCommandSummary = components['schemas']['PluginCommandSummary']
export type PluginPermissionRequirement = components['schemas']['PluginPermissionRequirement']
export type PluginPermissionStatus = components['schemas']['PluginPermissionStatus']
export type PluginPermissionSource = components['schemas']['PluginPermissionSource']
export type PluginPermissionSummary = components['schemas']['PluginPermissionSummary']
export type PluginSummary = components['schemas']['PluginSummary']
export type PluginDetail = components['schemas']['PluginDetail']
export type PluginListResponse = components['schemas']['PluginListResponse']
export type PluginDetailResponse = components['schemas']['PluginDetailResponse']
export type PluginInstallRequest = components['schemas']['PluginInstallRequest']
export type PluginGrantRequest = components['schemas']['PluginGrantRequest']
export type PluginGrantSummary = components['schemas']['PluginGrantSummary']
export type PluginGrantListResponse = components['schemas']['PluginGrantListResponse']
