import type { components } from './generated'

export type PluginState = components['schemas']['PluginState']
export type PluginRole = components['schemas']['PluginRole']
export type PluginInstallSourceType = components['schemas']['PluginInstallRequest']['source_type']
export type PluginCommandSummary = components['schemas']['PluginCommandSummary']
export type PluginManagementUIPage = components['schemas']['PluginManagementUIPage']
export type PluginSummary = components['schemas']['PluginSummary']
export type PluginDetail = components['schemas']['PluginDetail']
export type PluginListResponse = components['schemas']['PluginListResponse']
export type PluginDetailResponse = components['schemas']['PluginDetailResponse']
export type PluginInstallRequest = components['schemas']['PluginInstallRequest']
export type PluginStoreSource = components['schemas']['PluginStoreSource']
export type PluginStoreSourcesResponse = components['schemas']['PluginStoreSourcesResponse']
export type PluginStoreSourceInput = components['schemas']['PluginStoreSourceInput']
export type PluginStoreEntry = components['schemas']['PluginStoreEntry']
export type PluginStoreDependency = components['schemas']['PluginStoreDependency']
export type PluginStoreListResponse = components['schemas']['PluginStoreListResponse']
export type PluginStoreDetailResponse = components['schemas']['PluginStoreDetailResponse']
export type PluginStoreInstallRequest = components['schemas']['PluginStoreInstallRequest']
