// Generated by web/scripts/generate-websocket-types.mjs from contracts/websocket-events.yaml.
// Do not edit this file manually.

import type { components } from './generated'

export type ManagementWebSocketChannel = 'logs' | 'events' | 'tasks' | 'plugin_console'
export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'authenticated' | 'auth_failed' | 'reconnecting'

export type WebSocketErrorPayload = {
  code: string
  message?: string
  message_key: string
  details?: Record<string, unknown>
}

export interface WebSocketFrame<T = Record<string, unknown>> {
  channel: ManagementWebSocketChannel
  type: string
  timestamp: string
  data: T
  request_id?: string
  error?: WebSocketErrorPayload
}

export interface SessionExpiredFrame {
  type: 'session_expired'
  data: Record<string, never>
}

export type ServiceStatusEventPayload = {
  service_status: 'setup_required' | 'stopped' | 'starting' | 'running' | 'degraded' | 'stopping' | 'failed'
  summary: string
  reason?: string
  reason_codes?: string[]
}

export type PluginStateEventPayload = {
  plugin_id: string
  registration_state: 'installed' | 'removed'
  desired_state: 'enabled' | 'disabled'
  runtime_state: 'starting' | 'running' | 'stopping' | 'crashed' | 'backoff' | 'dead_letter' | 'stopped'
  display_state: 'discovered' | 'invalid_manifest' | 'conflict' | 'removed' | 'enabled' | 'enabling' | 'running' | 'disabling' | 'stopping' | 'crashed' | 'backoff' | 'dead_letter' | 'disabled'
  commands?: components['schemas']['PluginCommandSummary'][]
  command_conflicts?: string[]
}

export type ConnectionStatusEventPayload = {
  connection_status: ConnectionStatus
  summary: string
}

export type GenericManagementEventPayload = {
  event_type: string
  summary: string
}

export type BridgeRuntimeObservabilityEventPayload = {
  observability_scope: 'bridge_runtime'
  summary: string
  last_supported_event_kind?: string
  last_delivery_outcome?: 'delivered' | 'error'
  delivered_count: number
  result_count: number
  error_count: number
  adapter_dedup_drops_total?: number
  bridge_ignored_total?: number
  dispatcher_delivered_total?: number
  dispatcher_dropped_total?: number
  dispatcher_ignored_total?: number
}

export type DispatcherDropReason = 'queue_full' | 'plugin_not_running' | 'unsubscribed' | 'runtime_unavailable'

export type DispatcherRuntimeDropRow = {
  reason: DispatcherDropReason
  plugin_id?: string
  event_type?: string
  count: number
}

export type DispatcherRuntimeObservabilityEventPayload = {
  observability_scope: 'dispatcher_runtime'
  window_seconds: number
  delivered_count: number
  dropped_count: number
  ignored_count: number
  drops_by_reason?: DispatcherRuntimeDropRow[]
}

export type BilibiliSourceStatusEventPayload = {
  source: 'bilibili'
  status: 'disabled' | 'idle' | 'connecting' | 'connected' | 'degraded' | 'failed'
  summary: string
  live_watched_rooms: number
  live_connected_rooms: number
  live_failed_rooms: number
  fallback_polling: boolean
  dynamic_enabled: boolean
  dynamic_watched_uids: number
  last_event_at: string | null
  last_error: string
  diagnosis: components['schemas']['BilibiliSourceDiagnosis']
}

export type ProtocolSnapshotEventPayload = {
  protocol: 'onebot11'
  protocol_snapshot: components['schemas']['OneBot11ProtocolSnapshotResponse']
}

export type EventsPayload =
  | ServiceStatusEventPayload
  | PluginStateEventPayload
  | ConnectionStatusEventPayload
  | GenericManagementEventPayload
  | BridgeRuntimeObservabilityEventPayload
  | DispatcherRuntimeObservabilityEventPayload
  | BilibiliSourceStatusEventPayload
  | ProtocolSnapshotEventPayload

export type PluginConsoleFrameData = {
  plugin_id: string
  stream: 'stdout' | 'stderr' | 'system'
  text: string
  timestamp: string
}
