// Generated by web/scripts/generate-websocket-types.mjs from contracts/websocket-events.yaml.
// Do not edit this file manually.

import type { components } from './generated'

export type ManagementWebSocketChannel = 'logs' | 'events' | 'tasks' | 'plugin_console'
export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'authenticated' | 'auth_failed' | 'reconnecting'

export type WebSocketErrorPayload = {
  code: string
  message?: string
  message_key: string
  details?: Record<string, unknown>
}

export interface WebSocketFrame<T = Record<string, unknown>> {
  channel: ManagementWebSocketChannel
  type: string
  timestamp: string
  data: T
  request_id?: string
  error?: WebSocketErrorPayload
}

export interface SessionExpiredFrame {
  type: 'session_expired'
  data: Record<string, never>
}

export type ServiceStatusEventPayload = {
  service_status: 'setup_required' | 'stopped' | 'starting' | 'running' | 'degraded' | 'stopping' | 'failed'
  summary: string
  reason?: string
  reason_codes?: string[]
}

export type PluginStateEventPayload = {
  plugin_id: string
  registration_state: 'installed' | 'removed'
  desired_state: 'enabled' | 'disabled'
  runtime_state: 'starting' | 'running' | 'stopping' | 'crashed' | 'backoff' | 'dead_letter' | 'stopped'
  display_state: 'discovered' | 'invalid_manifest' | 'conflict' | 'removed' | 'enabled' | 'enabling' | 'running' | 'disabling' | 'stopping' | 'crashed' | 'backoff' | 'dead_letter' | 'disabled'
  commands?: components['schemas']['PluginCommandSummary'][]
  command_conflicts?: string[]
}

export type ConnectionStatusEventPayload = {
  connection_status: ConnectionStatus
  summary: string
}

export type GenericManagementEventPayload = {
  event_type: string
  summary: string
}

export type BridgeRuntimeObservabilityEventPayload = {
  observability_scope: 'bridge_runtime'
  summary: string
  last_supported_event_kind?: string
  last_delivery_outcome?: 'delivered' | 'error'
  delivered_count: number
  result_count: number
  error_count: number
}

export type ProtocolSnapshotEventPayload = {
  protocol: 'onebot11'
  protocol_snapshot: components['schemas']['OneBot11ProtocolSnapshotResponse']
}

export type EventsPayload =
  | ServiceStatusEventPayload
  | PluginStateEventPayload
  | ConnectionStatusEventPayload
  | GenericManagementEventPayload
  | BridgeRuntimeObservabilityEventPayload
  | ProtocolSnapshotEventPayload

export type PluginConsoleFrameData = {
  plugin_id: string
  stream: 'stdout' | 'stderr' | 'system'
  text: string
  timestamp: string
}
