// Generated by web/scripts/generate-websocket-types.mjs from contracts/websocket-events.yaml.
// Do not edit this file manually.

import type { components } from './generated'

export const webSocketPaths = {
  logs: '/ws/logs',
  events: '/ws/events',
  pluginConsole: (id: string) => `/ws/plugins/${encodeURIComponent(id)}/console`,
} as const

export const webSocketEvents = {
  logsAppended: 'logs.appended',
  eventsReceived: 'events.received',
  pluginsConsole: 'plugins.console',
  sessionExpired: 'session_expired',
} as const

export const managementEventTypes = {
  governanceChanged: 'governance.changed',
} as const

export type ManagementWebSocketChannel = 'logs' | 'events' | 'plugin_console'

export type WebSocketErrorPayload = {
  code: string
  message?: string
  details?: Record<string, unknown>
}

export interface WebSocketFrame<T = Record<string, unknown>> {
  channel: ManagementWebSocketChannel
  type: typeof webSocketEvents.logsAppended | typeof webSocketEvents.eventsReceived | typeof webSocketEvents.pluginsConsole
  timestamp: string
  data: T
  request_id?: string
  error?: WebSocketErrorPayload
}

export interface SessionExpiredFrame {
  type: typeof webSocketEvents.sessionExpired
  data: components['schemas']['SessionExpiredPayload']
}

export type ConnectionStatus = components['schemas']['ConnectionStatusEvent']['connection_status']
export type ServiceStatusEventPayload = components['schemas']['ServiceStatusEvent']
export type EventsPayload = components['schemas']['EventsReceivedPayload']
export type PluginConsoleFrameData = components['schemas']['PluginConsoleFrame']
