import type { RouteRecordRaw } from 'vue-router'

import BasicLayout from '@/layouts/BasicLayout.vue'
import RouteView from '@/layouts/RouteView.vue'
import ExceptionView from '@/views/core/ExceptionView.vue'

export const adminRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    component: BasicLayout,
    meta: { requiresAuth: true },
    children: [
      {
        path: '',
        name: 'status',
        component: () => import('@/views/dashboard/DashboardView.vue'),
        meta: {
          affixTab: true,
          icon: 'dashboard',
          order: 1,
          requiresAuth: true,
          titleKey: 'routes.status',
        },
      },
      {
        path: '',
        component: RouteView,
        redirect: { name: 'plugins' },
        meta: {
          hideInTab: true,
          icon: 'appstore',
          order: 2,
          requiresAuth: true,
          titleKey: 'routes.pluginCenter',
        },
        children: [
          {
            path: '/plugins',
            name: 'plugins',
            component: () => import('@/views/plugins/PluginsView.vue'),
            meta: {
              icon: 'appstore',
              keepAlive: true,
              order: 1,
              requiresAuth: true,
              titleKey: 'routes.pluginList',
            },
          },
          {
            path: '/plugins/settings',
            name: 'plugin-settings',
            component: () => import('@/views/plugins/PluginSettingsView.vue'),
            meta: {
              icon: 'setting',
              keepAlive: true,
              order: 2,
              requiresAuth: true,
              titleKey: 'routes.pluginSettings',
              viewKey: 'plugin-settings',
            },
          },
          {
            path: '/plugins/:id',
            name: 'plugin-detail',
            component: () => import('@/views/plugins/PluginDetailView.vue'),
            meta: {
              activePath: '/plugins',
              hideInMenu: true,
              requiresAuth: true,
              titleKey: 'routes.pluginDetail',
            },
          },
          {
            path: '/commands',
            name: 'commands',
            component: () => import('@/views/operations/CommandsView.vue'),
            meta: {
              icon: 'commands',
              keepAlive: true,
              order: 3,
              requiresAuth: true,
              titleKey: 'routes.commands',
              viewKey: 'commands',
            },
          },
        ],
      },
      {
        path: '',
        component: RouteView,
        redirect: { name: 'permission-policy' },
        meta: {
          hideInTab: true,
          icon: 'toolbox',
          order: 3,
          requiresAuth: true,
          titleKey: 'routes.operations',
        },
        children: [
          {
            path: '/permission-policy',
            name: 'permission-policy',
            component: () => import('@/views/operations/PermissionPolicyView.vue'),
            meta: {
              icon: 'permission-policy',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.permissionPolicy',
              viewKey: 'permission-policy',
            },
          },
          {
            path: '/access-lists',
            name: 'access-lists',
            component: () => import('@/views/operations/AccessListsView.vue'),
            meta: {
              icon: 'access-lists',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.accessLists',
              viewKey: 'access-lists',
            },
          },
          {
            path: '/rate-limits',
            name: 'rate-limits',
            component: () => import('@/views/operations/RateLimitsView.vue'),
            meta: {
              icon: 'rate-limits',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.rateLimits',
              viewKey: 'rate-limits',
            },
          },
          {
            path: '/tasks',
            name: 'tasks',
            component: () => import('@/views/operations/TasksView.vue'),
            meta: {
              icon: 'tasks',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.tasks',
              viewKey: 'tasks',
            },
          },
        ],
      },
      {
        path: '',
        component: RouteView,
        redirect: { name: 'logs' },
        meta: {
          hideInTab: true,
          icon: 'logs-center',
          order: 4,
          requiresAuth: true,
          titleKey: 'routes.logsCenter',
        },
        children: [
          {
            path: '/logs',
            name: 'logs',
            component: () => import('@/views/operations/LogsView.vue'),
            meta: {
              icon: 'logs',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.logs',
              viewKey: 'logs',
            },
          },
          {
            path: '/logs/history',
            name: 'logs-history',
            component: () => import('@/views/operations/LogsHistoryView.vue'),
            meta: {
              icon: 'history-logs',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.logsHistory',
              viewKey: 'logs-history',
            },
          },
        ],
      },
      {
        path: '',
        component: RouteView,
        redirect: { name: 'protocols' },
        meta: {
          hideInTab: true,
          icon: 'protocols',
          order: 5,
          requiresAuth: true,
          titleKey: 'routes.protocolGroup',
        },
        children: [
          {
            path: '/protocols',
            name: 'protocols',
            component: () => import('@/views/protocols/ProtocolsView.vue'),
            meta: {
              icon: 'protocols',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.protocols',
            },
          },
          {
            path: '/protocols/compatibility',
            name: 'protocols-compatibility',
            component: () => import('@/views/protocols/ProtocolCompatibilityView.vue'),
            meta: {
              icon: 'protocols',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.protocolCompatibility',
            },
          },
        ],
      },
      {
        path: '',
        component: RouteView,
        redirect: { name: 'config' },
        meta: {
          hideInTab: true,
          icon: 'system',
          order: 6,
          requiresAuth: true,
          titleKey: 'routes.system',
        },
        children: [
          {
            path: '/config',
            name: 'config',
            component: () => import('@/views/system/ConfigView.vue'),
            meta: {
              icon: 'config',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.config',
            },
          },
          {
            path: '/render/templates/:templateId?',
            name: 'render-templates',
            component: () => import('@/views/system/RenderTemplatesView.vue'),
            meta: {
              activePath: '/render/templates',
              entryPath: '/render/templates',
              icon: 'render-templates',
              keepAlive: true,
              requiresAuth: true,
              titleKey: 'routes.renderTemplates',
              viewKey: 'render-templates',
            },
          },
        ],
      },
      {
        path: '/403',
        name: 'forbidden',
        component: ExceptionView,
        props: { status: '403' },
        meta: {
          exceptionStatus: '403',
          hideInMenu: true,
          icon: 'forbidden',
          requiresAuth: true,
          titleKey: 'routes.forbidden',
          viewKey: 'forbidden',
        },
      },
      {
        path: '/404',
        name: 'not-found-page',
        component: ExceptionView,
        props: { status: '404' },
        meta: {
          exceptionStatus: '404',
          hideInMenu: true,
          icon: 'not-found',
          requiresAuth: true,
          titleKey: 'routes.notFound',
          viewKey: 'not-found-page',
        },
      },
      {
        path: '/500',
        name: 'server-error',
        component: ExceptionView,
        props: { status: '500' },
        meta: {
          exceptionStatus: '500',
          hideInMenu: true,
          icon: 'server-error',
          requiresAuth: true,
          titleKey: 'routes.serverError',
          viewKey: 'server-error',
        },
      },
      {
        path: '/offline',
        name: 'offline',
        component: ExceptionView,
        props: { status: 'offline' },
        meta: {
          exceptionStatus: 'offline',
          hideInMenu: true,
          icon: 'offline',
          hideInTab: true,
          public: true,
          requiresAuth: false,
          titleKey: 'routes.offline',
          viewKey: 'offline',
        },
      },
      {
        path: '/:pathMatch(.*)*',
        name: 'not-found',
        component: ExceptionView,
        props: { status: '404' },
        meta: {
          exceptionStatus: '404',
          hideInMenu: true,
          icon: 'not-found',
          requiresAuth: true,
          titleKey: 'routes.notFound',
        },
      },
    ],
  },
]
