// Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.

package releaseupdate

const (
	ArtifactWindowsX64Full = "windows-x64-full"
	ArtifactLinuxX64Full   = "linux-x64-full"
	ArtifactMacOSARM64Full = "macos-arm64-full"
	ArtifactLinuxX64Server = "linux-x64-server"
)
