// Generated by scripts/generate-web-brand-assets.mjs from design/mark-light.svg and design/mark-dark.svg. Do not edit.

import light32 from '../assets/brand/mark-light-32.png?no-inline'
import light40 from '../assets/brand/mark-light-40.png?no-inline'
import light48 from '../assets/brand/mark-light-48.png?no-inline'
import light50 from '../assets/brand/mark-light-50.png?no-inline'
import light60 from '../assets/brand/mark-light-60.png?no-inline'
import light64 from '../assets/brand/mark-light-64.png?no-inline'
import light80 from '../assets/brand/mark-light-80.png?no-inline'
import light96 from '../assets/brand/mark-light-96.png?no-inline'
import light120 from '../assets/brand/mark-light-120.png?no-inline'
import light128 from '../assets/brand/mark-light-128.png?no-inline'
import light160 from '../assets/brand/mark-light-160.png?no-inline'
import light192 from '../assets/brand/mark-light-192.png?no-inline'
import light256 from '../assets/brand/mark-light-256.png?no-inline'
import light384 from '../assets/brand/mark-light-384.png?no-inline'
import dark32 from '../assets/brand/mark-dark-32.png?no-inline'
import dark40 from '../assets/brand/mark-dark-40.png?no-inline'
import dark48 from '../assets/brand/mark-dark-48.png?no-inline'
import dark50 from '../assets/brand/mark-dark-50.png?no-inline'
import dark60 from '../assets/brand/mark-dark-60.png?no-inline'
import dark64 from '../assets/brand/mark-dark-64.png?no-inline'
import dark80 from '../assets/brand/mark-dark-80.png?no-inline'
import dark96 from '../assets/brand/mark-dark-96.png?no-inline'
import dark120 from '../assets/brand/mark-dark-120.png?no-inline'
import dark128 from '../assets/brand/mark-dark-128.png?no-inline'
import dark160 from '../assets/brand/mark-dark-160.png?no-inline'
import dark192 from '../assets/brand/mark-dark-192.png?no-inline'
import dark256 from '../assets/brand/mark-dark-256.png?no-inline'
import dark384 from '../assets/brand/mark-dark-384.png?no-inline'

export const rayleaMarkSources = {
  light: {
    32: {
      src: light32,
      srcset: [`${light32} 32w`, `${light40} 40w`, `${light48} 48w`, `${light64} 64w`, `${light96} 96w`].join(', '),
    },
    40: {
      src: light40,
      srcset: [`${light40} 40w`, `${light50} 50w`, `${light60} 60w`, `${light80} 80w`, `${light120} 120w`].join(', '),
    },
    128: {
      src: light128,
      srcset: [`${light128} 128w`, `${light160} 160w`, `${light192} 192w`, `${light256} 256w`, `${light384} 384w`].join(', '),
    },
  },
  dark: {
    32: {
      src: dark32,
      srcset: [`${dark32} 32w`, `${dark40} 40w`, `${dark48} 48w`, `${dark64} 64w`, `${dark96} 96w`].join(', '),
    },
    40: {
      src: dark40,
      srcset: [`${dark40} 40w`, `${dark50} 50w`, `${dark60} 60w`, `${dark80} 80w`, `${dark120} 120w`].join(', '),
    },
    128: {
      src: dark128,
      srcset: [`${dark128} 128w`, `${dark160} 160w`, `${dark192} 192w`, `${dark256} 256w`, `${dark384} 384w`].join(', '),
    },
  },
} as const
