// Generated by scripts/generate-design-tokens.mjs from design/tokens.json. Do not edit.

export const rayleaMark = {
  "viewBox": "0 0 24 26",
  "paths": [
    {
      "d": "M3 10 15 3v11L3 21Z",
      "opacity": 0.5
    },
    {
      "d": "m3 10 9 5v8l-9-5Z",
      "opacity": 0.85
    },
    {
      "d": "m12 15 10-6v9l-10 5Z",
      "opacity": 1
    },
    {
      "d": "M15 3v11l7-5V4Z",
      "opacity": 0.28
    }
  ]
} as const

export interface WebThemeTokens {
  attention: string
  attentionSoft: string
  authCanvasFocus: string
  authCanvasWash: string
  authControl: string
  authControlHover: string
  border: string
  borderControl: string
  brandFill: string
  brandFillHover: string
  brandFillPressed: string
  brandForeground: string
  brandSoft: string
  canvas: string
  chrome: string
  chromeMuted: string
  chromeText: string
  danger: string
  dangerSoft: string
  focus: string
  navHover: string
  navSelected: string
  navSelectedText: string
  onAttention: string
  onBrand: string
  shadowFloating: string
  shadowSurface: string
  success: string
  successSoft: string
  surface: string
  surfaceRaised: string
  surfaceSoft: string
  text: string
  textMuted: string
  warning: string
  warningSoft: string
}

export const webThemes: Record<'light' | 'dark', WebThemeTokens> = {
  light: {
    attention: '#9B4A2F',
    attentionSoft: '#F9ECE6',
    border: '#E3E3E3',
    borderControl: '#8A8A8A',
    brandFill: '#476C5E',
    brandForeground: '#476C5E',
    brandSoft: '#F0F0F0',
    canvas: '#FAFAFA',
    chrome: '#F7F7F7',
    chromeMuted: '#666666',
    chromeText: '#252525',
    danger: '#B9384E',
    dangerSoft: '#FBE9EC',
    focus: '#555555',
    onAttention: '#FFFFFF',
    onBrand: '#FFFFFF',
    success: '#227653',
    successSoft: '#E8F4EE',
    surface: '#FFFFFF',
    surfaceRaised: '#FFFFFF',
    surfaceSoft: '#F4F4F4',
    text: '#252525',
    textMuted: '#666666',
    warning: '#8A5600',
    warningSoft: '#FBF0DC',
    brandFillHover: '#365749',
    brandFillPressed: '#294438',
    navHover: '#EFEFEF',
    navSelected: '#E9E9E9',
    navSelectedText: '#252525',
    authCanvasFocus: '#476C5E1F',
    authCanvasWash: '#476C5E12',
    authControl: '#FFFFFF',
    authControlHover: '#F4F4F4',
    shadowSurface: '0 2px 8px #2525250B',
    shadowFloating: '0 18px 40px #25252524',
  },
  dark: {
    attention: '#E08A61',
    attentionSoft: '#3B261E',
    border: '#3D3D3D',
    borderControl: '#858585',
    brandFill: '#A3C5B3',
    brandForeground: '#BBD0C1',
    brandSoft: '#2B2B2B',
    canvas: '#161616',
    chrome: '#1B1B1B',
    chromeMuted: '#ADADAD',
    chromeText: '#EEEEEE',
    danger: '#FF8494',
    dangerSoft: '#402026',
    focus: '#C0C0C0',
    onAttention: '#18281F',
    onBrand: '#18281F',
    success: '#65D39A',
    successSoft: '#193429',
    surface: '#1E1E1E',
    surfaceRaised: '#292929',
    surfaceSoft: '#252525',
    text: '#EEEEEE',
    textMuted: '#ADADAD',
    warning: '#F0BB5A',
    warningSoft: '#3B2D16',
    brandFillHover: '#BBD0C1',
    brandFillPressed: '#80A48F',
    navHover: '#282828',
    navSelected: '#333333',
    navSelectedText: '#EEEEEE',
    authCanvasFocus: '#A3C5B31F',
    authCanvasWash: '#A3C5B312',
    authControl: '#252525',
    authControlHover: '#252525',
    shadowSurface: '0 2px 10px #00000047',
    shadowFloating: '0 20px 56px #00000070',
  },
}
