// Generated by scripts/generate-design-tokens.mjs from design/tokens.json. Do not edit.

export interface WebThemeTokens {
  attention: string
  attentionSoft: string
  border: string
  borderControl: string
  brandFill: string
  brandFillHover: string
  brandFillPressed: string
  brandForeground: string
  brandSoft: string
  canvas: string
  chrome: string
  chromeMuted: string
  chromeText: string
  danger: string
  dangerSoft: string
  focus: string
  info: string
  infoSoft: string
  navHover: string
  navSelected: string
  navSelectedText: string
  onAttention: string
  onBrand: string
  shadowFloating: string
  shadowRaised: string
  shadowSurface: string
  success: string
  successSoft: string
  surface: string
  surfaceRaised: string
  surfaceSoft: string
  text: string
  textMuted: string
  warning: string
  warningSoft: string
}

export const webThemes: Record<'light' | 'dark', WebThemeTokens> = {
  light: {
    attention: '#6240B8',
    attentionSoft: '#EEE8FB',
    border: '#E4E2DE',
    borderControl: '#8A8782',
    brandFill: '#2860D8',
    brandForeground: '#2860D8',
    brandSoft: '#E8EEFB',
    canvas: '#FFFFFF',
    chrome: '#F5F5F3',
    chromeMuted: '#5F5C56',
    chromeText: '#1C1B19',
    danger: '#A92E29',
    dangerSoft: '#FBDEDB',
    focus: '#2860D8',
    info: '#2159B8',
    infoSoft: '#E0E9FB',
    onAttention: '#FFFFFF',
    onBrand: '#FFFFFF',
    success: '#1D6E3D',
    successSoft: '#DDF1E3',
    surface: '#F5F5F3',
    surfaceRaised: '#FFFFFF',
    surfaceSoft: '#ECEBE8',
    text: '#1C1B19',
    textMuted: '#5F5C56',
    warning: '#7F5000',
    warningSoft: '#FBEBC7',
    brandFillHover: '#1F52C0',
    brandFillPressed: '#1A47A8',
    navHover: '#1C1B190D',
    navSelected: '#FFFFFF',
    navSelectedText: '#1C1B19',
    shadowSurface: '0 1px 2px #1816120D, 0 10px 26px -14px #18161233',
    shadowRaised: '0 1px 2px #18161214, 0 3px 8px -4px #18161224',
    shadowFloating: '0 2px 6px #18161214, 0 24px 48px -16px #18161247',
  },
  dark: {
    attention: '#B9A5FF',
    attentionSoft: '#2A2342',
    border: '#2F2E2B',
    borderControl: '#86837C',
    brandFill: '#3567DC',
    brandForeground: '#8DB3FF',
    brandSoft: '#1F2A44',
    canvas: '#111110',
    chrome: '#1C1C1A',
    chromeMuted: '#B4B1AA',
    chromeText: '#EEEDEA',
    danger: '#FF8177',
    dangerSoft: '#3E1D1B',
    focus: '#8DB3FF',
    info: '#88AEFF',
    infoSoft: '#1B2A45',
    onAttention: '#1A1433',
    onBrand: '#FFFFFF',
    success: '#5BD08B',
    successSoft: '#173323',
    surface: '#1C1C1A',
    surfaceRaised: '#282826',
    surfaceSoft: '#161615',
    text: '#EEEDEA',
    textMuted: '#B4B1AA',
    warning: '#F3BB4F',
    warningSoft: '#3A2C12',
    brandFillHover: '#2B5BD0',
    brandFillPressed: '#2451BF',
    navHover: '#FFFFFF0F',
    navSelected: '#2E2E2B',
    navSelectedText: '#EEEDEA',
    shadowSurface: '0 1px 2px #00000059, 0 10px 28px -14px #00000099',
    shadowRaised: '0 1px 2px #00000066, 0 3px 8px -4px #00000080',
    shadowFloating: '0 2px 6px #00000066, 0 24px 56px -16px #000000B3',
  },
}
