// Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.

package pluginwire

func IsOneBotAction(kind string) bool {
	switch kind {
	case "message.get", "message.delete", "message.history.get", "message.forward.get", "message.forward.send", "message.read.mark", "friend.request.handle", "friend.list", "friend.remark.set", "user.info.get", "user.like.send", "group.list", "group.info.get", "group.member.get", "group.member.list", "group.request.handle", "group.leave", "group.admin.set", "group.ban.set", "group.card.set", "group.title.set", "group.name.set", "group.announcement.list", "group.announcement.create", "group.announcement.delete", "group.essence.list", "group.essence.set", "group.essence.unset", "group.honor.get", "group.todo.set", "file.get", "file.download", "file.group.upload", "file.private.upload", "file.group.url.get", "file.private.url.get", "file.group.fs.info", "file.group.fs.list", "file.group.fs.mkdir", "file.group.fs.delete", "reaction.set", "reaction.list", "poke.send":
		return true
	default:
		return false
	}
}

func IsProviderExtensionAction(kind string) bool {
	switch kind {
	case "provider.napcat.message_emoji.like.set", "provider.napcat.group.sign.set", "provider.luckylillia.friend_groups.get":
		return true
	default:
		return false
	}
}
