// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_lists.sql

package sqlcgen

import (
	"context"
)

const accessListAdd = `-- name: AccessListAdd :exec
INSERT INTO access_list_entries (list_kind, source_protocol, source_adapter, bot_id, entry_type, target_id, reason, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (list_kind, source_protocol, source_adapter, bot_id, entry_type, target_id) DO UPDATE SET reason = excluded.reason
`

type AccessListAddParams struct {
	ListKind       string
	SourceProtocol string
	SourceAdapter  string
	BotID          string
	EntryType      string
	TargetID       string
	Reason         string
	CreatedAt      string
}

func (q *Queries) AccessListAdd(ctx context.Context, arg AccessListAddParams) error {
	_, err := q.db.ExecContext(ctx, accessListAdd,
		arg.ListKind,
		arg.SourceProtocol,
		arg.SourceAdapter,
		arg.BotID,
		arg.EntryType,
		arg.TargetID,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const accessListContains = `-- name: AccessListContains :one
SELECT EXISTS(SELECT 1 FROM access_list_entries
WHERE list_kind = ? AND entry_type = ? AND target_id = ? AND source_protocol = ?
AND ((source_adapter = ? AND bot_id = ?) OR (source_protocol = 'onebot11' AND source_adapter = '' AND bot_id = '')))
`

type AccessListContainsParams struct {
	ListKind       string
	EntryType      string
	TargetID       string
	SourceProtocol string
	SourceAdapter  string
	BotID          string
}

func (q *Queries) AccessListContains(ctx context.Context, arg AccessListContainsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, accessListContains,
		arg.ListKind,
		arg.EntryType,
		arg.TargetID,
		arg.SourceProtocol,
		arg.SourceAdapter,
		arg.BotID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accessListGet = `-- name: AccessListGet :one
SELECT id, list_kind, source_protocol, source_adapter, bot_id, entry_type, target_id, reason, created_at FROM access_list_entries
WHERE list_kind = ? AND source_protocol = ? AND source_adapter = ? AND bot_id = ? AND entry_type = ? AND target_id = ?
`

type AccessListGetParams struct {
	ListKind       string
	SourceProtocol string
	SourceAdapter  string
	BotID          string
	EntryType      string
	TargetID       string
}

func (q *Queries) AccessListGet(ctx context.Context, arg AccessListGetParams) (AccessListEntry, error) {
	row := q.db.QueryRowContext(ctx, accessListGet,
		arg.ListKind,
		arg.SourceProtocol,
		arg.SourceAdapter,
		arg.BotID,
		arg.EntryType,
		arg.TargetID,
	)
	var i AccessListEntry
	err := row.Scan(
		&i.ID,
		&i.ListKind,
		&i.SourceProtocol,
		&i.SourceAdapter,
		&i.BotID,
		&i.EntryType,
		&i.TargetID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const accessListList = `-- name: AccessListList :many
SELECT id, list_kind, source_protocol, source_adapter, bot_id, entry_type, target_id, reason, created_at FROM access_list_entries WHERE list_kind = ? AND entry_type = ? ORDER BY created_at DESC, id DESC
`

type AccessListListParams struct {
	ListKind  string
	EntryType string
}

func (q *Queries) AccessListList(ctx context.Context, arg AccessListListParams) ([]AccessListEntry, error) {
	rows, err := q.db.QueryContext(ctx, accessListList, arg.ListKind, arg.EntryType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessListEntry{}
	for rows.Next() {
		var i AccessListEntry
		if err := rows.Scan(
			&i.ID,
			&i.ListKind,
			&i.SourceProtocol,
			&i.SourceAdapter,
			&i.BotID,
			&i.EntryType,
			&i.TargetID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessListRemove = `-- name: AccessListRemove :execrows
DELETE FROM access_list_entries
WHERE list_kind = ? AND source_protocol = ? AND source_adapter = ? AND bot_id = ? AND entry_type = ? AND target_id = ?
`

type AccessListRemoveParams struct {
	ListKind       string
	SourceProtocol string
	SourceAdapter  string
	BotID          string
	EntryType      string
	TargetID       string
}

func (q *Queries) AccessListRemove(ctx context.Context, arg AccessListRemoveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, accessListRemove,
		arg.ListKind,
		arg.SourceProtocol,
		arg.SourceAdapter,
		arg.BotID,
		arg.EntryType,
		arg.TargetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWhitelistEnabled = `-- name: SetWhitelistEnabled :exec
INSERT INTO whitelist_state (singleton_id, enabled, updated_at) VALUES (1, ?, ?)
ON CONFLICT (singleton_id) DO UPDATE SET enabled = excluded.enabled, updated_at = excluded.updated_at
`

type SetWhitelistEnabledParams struct {
	Enabled   int64
	UpdatedAt string
}

func (q *Queries) SetWhitelistEnabled(ctx context.Context, arg SetWhitelistEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setWhitelistEnabled, arg.Enabled, arg.UpdatedAt)
	return err
}

const whitelistEnabled = `-- name: WhitelistEnabled :one
SELECT enabled FROM whitelist_state WHERE singleton_id = 1
`

func (q *Queries) WhitelistEnabled(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, whitelistEnabled)
	var enabled int64
	err := row.Scan(&enabled)
	return enabled, err
}
