// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package sqlcgen

import (
	"context"
)

const countBootstrap = `-- name: CountBootstrap :one
SELECT COUNT(*) FROM auth_bootstrap_state WHERE singleton_id = 1
`

func (q *Queries) CountBootstrap(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBootstrap)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM admin_sessions WHERE session_id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionID)
	return err
}

const insertBootstrap = `-- name: InsertBootstrap :exec
INSERT INTO auth_bootstrap_state (singleton_id, identifier, secret_digest, signing_key, initialized_at)
VALUES (1, ?, ?, ?, ?)
`

type InsertBootstrapParams struct {
	Identifier    string
	SecretDigest  []byte
	SigningKey    []byte
	InitializedAt string
}

func (q *Queries) InsertBootstrap(ctx context.Context, arg InsertBootstrapParams) error {
	_, err := q.db.ExecContext(ctx, insertBootstrap,
		arg.Identifier,
		arg.SecretDigest,
		arg.SigningKey,
		arg.InitializedAt,
	)
	return err
}

const loadBootstrap = `-- name: LoadBootstrap :one
SELECT identifier, secret_digest, signing_key, initialized_at
FROM auth_bootstrap_state WHERE singleton_id = 1
`

type LoadBootstrapRow struct {
	Identifier    string
	SecretDigest  []byte
	SigningKey    []byte
	InitializedAt string
}

func (q *Queries) LoadBootstrap(ctx context.Context) (LoadBootstrapRow, error) {
	row := q.db.QueryRowContext(ctx, loadBootstrap)
	var i LoadBootstrapRow
	err := row.Scan(
		&i.Identifier,
		&i.SecretDigest,
		&i.SigningKey,
		&i.InitializedAt,
	)
	return i, err
}

const loadSessions = `-- name: LoadSessions :many
SELECT session_id, subject, issued_at, expires_at FROM admin_sessions
`

func (q *Queries) LoadSessions(ctx context.Context) ([]AdminSession, error) {
	rows, err := q.db.QueryContext(ctx, loadSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSession{}
	for rows.Next() {
		var i AdminSession
		if err := rows.Scan(
			&i.SessionID,
			&i.Subject,
			&i.IssuedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO admin_sessions (session_id, subject, issued_at, expires_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(session_id) DO UPDATE SET
    subject = excluded.subject,
    issued_at = excluded.issued_at,
    expires_at = excluded.expires_at
`

type UpsertSessionParams struct {
	SessionID string
	Subject   string
	IssuedAt  string
	ExpiresAt string
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.SessionID,
		arg.Subject,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}
