// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: logging.sql

package sqlcgen

import (
	"context"
)

const getLogSummary = `-- name: GetLogSummary :one
SELECT log_id, boot_id, ts, level, source, message, plugin_id, request_id, details_json
FROM management_logs
WHERE log_id = ?
LIMIT 1
`

type GetLogSummaryRow struct {
	LogID       string
	BootID      string
	Ts          string
	Level       string
	Source      string
	Message     string
	PluginID    string
	RequestID   string
	DetailsJson string
}

func (q *Queries) GetLogSummary(ctx context.Context, logID string) (GetLogSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getLogSummary, logID)
	var i GetLogSummaryRow
	err := row.Scan(
		&i.LogID,
		&i.BootID,
		&i.Ts,
		&i.Level,
		&i.Source,
		&i.Message,
		&i.PluginID,
		&i.RequestID,
		&i.DetailsJson,
	)
	return i, err
}

const insertLogSummary = `-- name: InsertLogSummary :exec
INSERT INTO management_logs (log_id, boot_id, ts, level, source, message, plugin_id, request_id, details_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLogSummaryParams struct {
	LogID       string
	BootID      string
	Ts          string
	Level       string
	Source      string
	Message     string
	PluginID    string
	RequestID   string
	DetailsJson string
}

func (q *Queries) InsertLogSummary(ctx context.Context, arg InsertLogSummaryParams) error {
	_, err := q.db.ExecContext(ctx, insertLogSummary,
		arg.LogID,
		arg.BootID,
		arg.Ts,
		arg.Level,
		arg.Source,
		arg.Message,
		arg.PluginID,
		arg.RequestID,
		arg.DetailsJson,
	)
	return err
}

const pruneLogsBefore = `-- name: PruneLogsBefore :exec
DELETE FROM management_logs WHERE ts < ?
`

func (q *Queries) PruneLogsBefore(ctx context.Context, ts string) error {
	_, err := q.db.ExecContext(ctx, pruneLogsBefore, ts)
	return err
}
