// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: logging.sql

package sqlcgen

import (
	"context"
)

const insertLogSummary = `-- name: InsertLogSummary :exec
INSERT INTO management_logs (ts, level, source, message, plugin_id, request_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertLogSummaryParams struct {
	Ts        string
	Level     string
	Source    string
	Message   string
	PluginID  string
	RequestID string
}

func (q *Queries) InsertLogSummary(ctx context.Context, arg InsertLogSummaryParams) error {
	_, err := q.db.ExecContext(ctx, insertLogSummary,
		arg.Ts,
		arg.Level,
		arg.Source,
		arg.Message,
		arg.PluginID,
		arg.RequestID,
	)
	return err
}

const pruneLogsBefore = `-- name: PruneLogsBefore :exec
DELETE FROM management_logs WHERE ts < ?
`

func (q *Queries) PruneLogsBefore(ctx context.Context, ts string) error {
	_, err := q.db.ExecContext(ctx, pruneLogsBefore, ts)
	return err
}
