// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_stats.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addMessageStatsHour = `-- name: AddMessageStatsHour :exec
INSERT INTO message_stats_hours(hour_start, adapter_id, received, sent) VALUES (?, ?, ?, ?)
ON CONFLICT(hour_start, adapter_id) DO UPDATE SET
    received = message_stats_hours.received + excluded.received,
    sent = message_stats_hours.sent + excluded.sent
`

type AddMessageStatsHourParams struct {
	HourStart int64
	AdapterID string
	Received  int64
	Sent      int64
}

func (q *Queries) AddMessageStatsHour(ctx context.Context, arg AddMessageStatsHourParams) error {
	_, err := q.db.ExecContext(ctx, addMessageStatsHour,
		arg.HourStart,
		arg.AdapterID,
		arg.Received,
		arg.Sent,
	)
	return err
}

const getMessageTracking = `-- name: GetMessageTracking :one
SELECT started_at_ms FROM message_stats_tracking WHERE singleton_id = 1
`

func (q *Queries) GetMessageTracking(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageTracking)
	var started_at_ms int64
	err := row.Scan(&started_at_ms)
	return started_at_ms, err
}

const listMessageStatsAdapters = `-- name: ListMessageStatsAdapters :many
SELECT adapter_id, protocol, last_received_at_ms FROM message_stats_adapters
`

func (q *Queries) ListMessageStatsAdapters(ctx context.Context) ([]MessageStatsAdapter, error) {
	rows, err := q.db.QueryContext(ctx, listMessageStatsAdapters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageStatsAdapter{}
	for rows.Next() {
		var i MessageStatsAdapter
		if err := rows.Scan(&i.AdapterID, &i.Protocol, &i.LastReceivedAtMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageStatsOffline = `-- name: ListMessageStatsOffline :many
SELECT run_id, adapter_id, started_at_ms, ended_at_ms FROM message_stats_offline
WHERE started_at_ms < ?1
	AND (ended_at_ms IS NOT NULL OR run_id <> ?2)
    AND (ended_at_ms IS NULL OR ended_at_ms > ?3)
    AND (ended_at_ms IS NULL OR ended_at_ms - started_at_ms >= 30000)
ORDER BY started_at_ms DESC, adapter_id DESC, run_id DESC LIMIT 1001
`

type ListMessageStatsOfflineParams struct {
	AsOfMs       int64
	CurrentRunID int64
	StartMs      sql.NullInt64
}

func (q *Queries) ListMessageStatsOffline(ctx context.Context, arg ListMessageStatsOfflineParams) ([]MessageStatsOffline, error) {
	rows, err := q.db.QueryContext(ctx, listMessageStatsOffline, arg.AsOfMs, arg.CurrentRunID, arg.StartMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageStatsOffline{}
	for rows.Next() {
		var i MessageStatsOffline
		if err := rows.Scan(
			&i.RunID,
			&i.AdapterID,
			&i.StartedAtMs,
			&i.EndedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageStatsStops = `-- name: ListMessageStatsStops :many
SELECT r.stopped_at_ms AS started_at_ms, n.started_at_ms AS ended_at_ms
FROM message_stats_runs r JOIN message_stats_runs n
    ON n.id = (SELECT MIN(next_run.id) FROM message_stats_runs next_run WHERE next_run.id > r.id)
WHERE r.stopped_at_ms IS NOT NULL AND r.stopped_at_ms < n.started_at_ms
    AND r.stopped_at_ms < ?1 AND n.started_at_ms > ?2
ORDER BY r.stopped_at_ms DESC LIMIT 1001
`

type ListMessageStatsStopsParams struct {
	AsOfMs  sql.NullInt64
	StartMs int64
}

type ListMessageStatsStopsRow struct {
	StartedAtMs sql.NullInt64
	EndedAtMs   int64
}

func (q *Queries) ListMessageStatsStops(ctx context.Context, arg ListMessageStatsStopsParams) ([]ListMessageStatsStopsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessageStatsStops, arg.AsOfMs, arg.StartMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageStatsStopsRow{}
	for rows.Next() {
		var i ListMessageStatsStopsRow
		if err := rows.Scan(&i.StartedAtMs, &i.EndedAtMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverMessageStatsOffline = `-- name: RecoverMessageStatsOffline :exec
UPDATE message_stats_offline SET ended_at_ms = (
    SELECT COALESCE(stopped_at_ms, last_alive_at_ms) FROM message_stats_runs WHERE id = run_id
) WHERE ended_at_ms IS NULL
`

func (q *Queries) RecoverMessageStatsOffline(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverMessageStatsOffline)
	return err
}

const recoverMessageStatsRuns = `-- name: RecoverMessageStatsRuns :exec
UPDATE message_stats_runs SET stopped_at_ms = last_alive_at_ms WHERE stopped_at_ms IS NULL
`

func (q *Queries) RecoverMessageStatsRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverMessageStatsRuns)
	return err
}

const startMessageStatsRun = `-- name: StartMessageStatsRun :one
INSERT INTO message_stats_runs(started_at_ms, last_alive_at_ms) VALUES (?, ?) RETURNING id
`

type StartMessageStatsRunParams struct {
	StartedAtMs   int64
	LastAliveAtMs int64
}

func (q *Queries) StartMessageStatsRun(ctx context.Context, arg StartMessageStatsRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, startMessageStatsRun, arg.StartedAtMs, arg.LastAliveAtMs)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const startMessageTracking = `-- name: StartMessageTracking :exec
INSERT OR IGNORE INTO message_stats_tracking(singleton_id, started_at_ms) VALUES (1, ?)
`

func (q *Queries) StartMessageTracking(ctx context.Context, startedAtMs int64) error {
	_, err := q.db.ExecContext(ctx, startMessageTracking, startedAtMs)
	return err
}

const updateMessageStatsRun = `-- name: UpdateMessageStatsRun :exec
UPDATE message_stats_runs SET last_alive_at_ms = ?, stopped_at_ms = ? WHERE id = ?
`

type UpdateMessageStatsRunParams struct {
	LastAliveAtMs int64
	StoppedAtMs   sql.NullInt64
	ID            int64
}

func (q *Queries) UpdateMessageStatsRun(ctx context.Context, arg UpdateMessageStatsRunParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageStatsRun, arg.LastAliveAtMs, arg.StoppedAtMs, arg.ID)
	return err
}

const upsertMessageStatsAdapter = `-- name: UpsertMessageStatsAdapter :exec
INSERT INTO message_stats_adapters(adapter_id, protocol, last_received_at_ms) VALUES (?, ?, ?)
ON CONFLICT(adapter_id) DO UPDATE SET protocol = excluded.protocol,
    last_received_at_ms = CASE
        WHEN message_stats_adapters.last_received_at_ms IS NULL THEN excluded.last_received_at_ms
        WHEN excluded.last_received_at_ms IS NULL THEN message_stats_adapters.last_received_at_ms
        ELSE MAX(message_stats_adapters.last_received_at_ms, excluded.last_received_at_ms) END
`

type UpsertMessageStatsAdapterParams struct {
	AdapterID        string
	Protocol         string
	LastReceivedAtMs sql.NullInt64
}

func (q *Queries) UpsertMessageStatsAdapter(ctx context.Context, arg UpsertMessageStatsAdapterParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessageStatsAdapter, arg.AdapterID, arg.Protocol, arg.LastReceivedAtMs)
	return err
}

const upsertMessageStatsOffline = `-- name: UpsertMessageStatsOffline :exec
INSERT INTO message_stats_offline(run_id, adapter_id, started_at_ms, ended_at_ms) VALUES (?, ?, ?, ?)
ON CONFLICT(run_id, adapter_id, started_at_ms) DO UPDATE SET ended_at_ms = excluded.ended_at_ms
`

type UpsertMessageStatsOfflineParams struct {
	RunID       int64
	AdapterID   string
	StartedAtMs int64
	EndedAtMs   sql.NullInt64
}

func (q *Queries) UpsertMessageStatsOffline(ctx context.Context, arg UpsertMessageStatsOfflineParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessageStatsOffline,
		arg.RunID,
		arg.AdapterID,
		arg.StartedAtMs,
		arg.EndedAtMs,
	)
	return err
}
