// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"
)

type AdminSession struct {
	SessionID string
	Subject   string
	IssuedAt  string
	ExpiresAt string
}

type AuthBootstrapState struct {
	SingletonID   int64
	Identifier    string
	SecretDigest  []byte
	SigningKey    []byte
	InitializedAt string
}

type BilibiliSourceConfig struct {
	ID                     int64
	UaRotationEnabled      int64
	FingerprintEnabled     int64
	DmImgEnabled           int64
	CaptchaRecoveryEnabled int64
	ProxyGlobalEnabled     int64
	UpdatedAt              string
}

type BilibiliSourceDynamic struct {
	Uid         string
	DynamicID   string
	Service     string
	Title       string
	Summary     string
	Url         string
	Username    string
	AvatarUrl   string
	ImagesJson  string
	PublishedAt int64
	ObservedAt  string
	UpdatedAt   string
}

type BilibiliSourceRoom struct {
	Uid             string
	RoomID          string
	Name            string
	Face            string
	CoverUrl        string
	LiveStatus      int64
	LiveStartedAt   int64
	LiveEventID     string
	ConnectionState string
	LastEventAt     sql.NullString
	LastError       string
	UpdatedAt       string
}

type BilibiliSourceSeen struct {
	EventKey   string
	Uid        string
	EventType  string
	SourceID   string
	ObservedAt string
}

type BilibiliSourceState struct {
	Key       string
	ValueJson string
	UpdatedAt string
}

type BlacklistEntry struct {
	ID        int64
	EntryType string
	TargetID  string
	Reason    string
	CreatedAt string
}

type ManagementLog struct {
	ID          int64
	LogID       string
	BootID      string
	Ts          string
	Level       string
	Source      string
	Message     string
	PluginID    string
	RequestID   string
	DetailsJson string
}

type PluginGrant struct {
	PluginID   string
	Capability string
	ScopeJson  string
	GrantedAt  string
	ExpiresAt  sql.NullString
}

type PluginInstance struct {
	PluginID     string
	DesiredState string
	UpdatedAt    string
}

type PluginKv struct {
	PluginID  string
	Key       string
	ValueJson string
	SizeBytes int64
	UpdatedAt string
}

type PluginPackage struct {
	PluginID     string
	SourceType   string
	SourceRef    string
	Version      string
	ManifestHash string
	PackageHash  string
	InstalledAt  string
}

type RenderTemplateRevision struct {
	RevisionID      string
	TemplateID      string
	TemplateVersion string
	Kind            string
	Message         sql.NullString
	SavedAt         string
	SourceDigest    string
	ManifestJson    string
	Html            string
	Stylesheet      string
	InputSchemaJson sql.NullString
}

type RenderTemplateState struct {
	TemplateID           string
	CurrentRevisionID    string
	UpdatedAt            string
	ValidationValid      int64
	ValidationCheckedAt  string
	ValidationIssueCount int64
	SourceType           string
	SourcePluginID       sql.NullString
	SourceLocalID        sql.NullString
}

type SchedulerJob struct {
	JobID            string
	PluginID         string
	LogLabel         string
	CronExpr         string
	Payload          string
	Enabled          int64
	NextRun          string
	LastRun          sql.NullString
	CreatedAt        string
	UpdatedAt        string
	LastDurationMs   int64
	LastErrorCode    string
	LastErrorMessage string
	LastErrorAt      sql.NullString
	SuccessCount     int64
	FailureCount     int64
	TimeoutCount     int64
	RetryCount       int64
	OtherCount       int64
}

type SecretStore struct {
	Key       string
	Value     []byte
	CreatedAt string
	UpdatedAt string
}

type SystemConfig struct {
	Namespace string
	Key       string
	ValueJson string
	UpdatedAt string
}

type Task struct {
	TaskID     string
	TaskType   string
	Status     string
	Progress   int64
	Summary    string
	StartedAt  sql.NullString
	FinishedAt sql.NullString
	ResultJson sql.NullString
	ErrorJson  sql.NullString
	CreatedAt  string
}

type ThirdPartyAccount struct {
	Platform            string
	AccountID           string
	Label               string
	Enabled             int64
	SecretKey           string
	ProfileUid          string
	ProfileNickname     string
	ProfileAvatarUrl    string
	CredentialState     string
	CredentialCheckedAt sql.NullString
	CredentialLastError string
	LastUsedAt          sql.NullString
	UpdatedAt           string
}

type WhitelistEntry struct {
	ID        int64
	EntryType string
	TargetID  string
	Reason    string
	CreatedAt string
}

type WhitelistState struct {
	SingletonID int64
	Enabled     int64
	UpdatedAt   string
}
