// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"
)

type AdminSession struct {
	SessionID string
	Subject   string
	IssuedAt  string
	ExpiresAt string
}

type AuthBootstrapState struct {
	SingletonID   int64
	Identifier    string
	SecretDigest  []byte
	SigningKey    []byte
	InitializedAt string
}

type BlacklistEntry struct {
	ID        int64
	EntryType string
	TargetID  string
	Reason    string
	CreatedAt string
}

type ManagementLog struct {
	ID          int64
	Ts          string
	Level       string
	Source      string
	Message     string
	PluginID    string
	RequestID   string
	LogID       string
	DetailsJson string
	BootID      string
}

type PluginGrant struct {
	PluginID   string
	Capability string
	GrantedAt  string
	ScopeJson  string
	ExpiresAt  sql.NullString
}

type PluginInstance struct {
	PluginID     string
	DesiredState string
	UpdatedAt    string
}

type PluginKv struct {
	PluginID  string
	Key       string
	ValueJson string
	SizeBytes int64
	UpdatedAt string
}

type PluginPackage struct {
	PluginID     string
	SourceType   string
	SourceRef    string
	Version      string
	ManifestHash string
	PackageHash  string
	InstalledAt  string
}

type RenderTemplateRevision struct {
	RevisionID      string
	TemplateID      string
	TemplateVersion string
	Kind            string
	Message         sql.NullString
	SavedAt         string
	SourceDigest    string
	ManifestJson    string
	Html            string
	Stylesheet      string
	InputSchemaJson sql.NullString
}

type RenderTemplateState struct {
	TemplateID           string
	CurrentRevisionID    string
	UpdatedAt            string
	ValidationValid      int64
	ValidationCheckedAt  string
	ValidationIssueCount int64
	SourceType           string
	SourcePluginID       sql.NullString
	SourceLocalID        sql.NullString
}

type SchedulerJob struct {
	JobID     string
	PluginID  string
	CronExpr  string
	Payload   string
	Enabled   int64
	NextRun   string
	LastRun   sql.NullString
	CreatedAt string
	UpdatedAt string
	LogLabel  string
}

type SecretStore struct {
	Key       string
	Value     []byte
	CreatedAt string
	UpdatedAt string
}

type SystemConfig struct {
	Namespace string
	Key       string
	ValueJson string
	UpdatedAt string
}

type Task struct {
	TaskID     string
	TaskType   string
	Status     string
	Progress   int64
	Summary    string
	StartedAt  sql.NullString
	FinishedAt sql.NullString
	ResultJson sql.NullString
	ErrorJson  sql.NullString
	CreatedAt  string
}

type WhitelistEntry struct {
	ID        int64
	EntryType string
	TargetID  string
	Reason    string
	CreatedAt string
}

type WhitelistState struct {
	SingletonID int64
	Enabled     int64
	UpdatedAt   string
}
