// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plugins.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteAllGrants = `-- name: DeleteAllGrants :exec
DELETE FROM plugin_grants WHERE plugin_id = ?
`

func (q *Queries) DeleteAllGrants(ctx context.Context, pluginID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllGrants, pluginID)
	return err
}

const deleteDesiredState = `-- name: DeleteDesiredState :exec
DELETE FROM plugin_instances WHERE plugin_id = ?
`

func (q *Queries) DeleteDesiredState(ctx context.Context, pluginID string) error {
	_, err := q.db.ExecContext(ctx, deleteDesiredState, pluginID)
	return err
}

const deleteGrant = `-- name: DeleteGrant :exec
DELETE FROM plugin_grants WHERE plugin_id = ? AND capability = ?
`

type DeleteGrantParams struct {
	PluginID   string
	Capability string
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) error {
	_, err := q.db.ExecContext(ctx, deleteGrant, arg.PluginID, arg.Capability)
	return err
}

const deletePackageMetadata = `-- name: DeletePackageMetadata :exec
DELETE FROM plugin_packages WHERE plugin_id = ?
`

func (q *Queries) DeletePackageMetadata(ctx context.Context, pluginID string) error {
	_, err := q.db.ExecContext(ctx, deletePackageMetadata, pluginID)
	return err
}

const loadAllGrants = `-- name: LoadAllGrants :many
SELECT plugin_id, capability, expires_at
FROM plugin_grants ORDER BY plugin_id, capability
`

type LoadAllGrantsRow struct {
	PluginID   string
	Capability string
	ExpiresAt  sql.NullString
}

func (q *Queries) LoadAllGrants(ctx context.Context) ([]LoadAllGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, loadAllGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadAllGrantsRow{}
	for rows.Next() {
		var i LoadAllGrantsRow
		if err := rows.Scan(&i.PluginID, &i.Capability, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAllPackageMetadata = `-- name: LoadAllPackageMetadata :many
SELECT plugin_id, source_type, source_ref, version, manifest_hash, package_hash, installed_at
FROM plugin_packages
`

func (q *Queries) LoadAllPackageMetadata(ctx context.Context) ([]PluginPackage, error) {
	rows, err := q.db.QueryContext(ctx, loadAllPackageMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginPackage{}
	for rows.Next() {
		var i PluginPackage
		if err := rows.Scan(
			&i.PluginID,
			&i.SourceType,
			&i.SourceRef,
			&i.Version,
			&i.ManifestHash,
			&i.PackageHash,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadDesiredStates = `-- name: LoadDesiredStates :many
SELECT plugin_id, desired_state FROM plugin_instances
`

type LoadDesiredStatesRow struct {
	PluginID     string
	DesiredState string
}

func (q *Queries) LoadDesiredStates(ctx context.Context) ([]LoadDesiredStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, loadDesiredStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadDesiredStatesRow{}
	for rows.Next() {
		var i LoadDesiredStatesRow
		if err := rows.Scan(&i.PluginID, &i.DesiredState); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadGrants = `-- name: LoadGrants :many
SELECT plugin_id, capability, scope_json, granted_at, expires_at
FROM plugin_grants WHERE plugin_id = ? ORDER BY capability
`

type LoadGrantsRow struct {
	PluginID   string
	Capability string
	ScopeJson  string
	GrantedAt  string
	ExpiresAt  sql.NullString
}

func (q *Queries) LoadGrants(ctx context.Context, pluginID string) ([]LoadGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, loadGrants, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadGrantsRow{}
	for rows.Next() {
		var i LoadGrantsRow
		if err := rows.Scan(
			&i.PluginID,
			&i.Capability,
			&i.ScopeJson,
			&i.GrantedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDesiredState = `-- name: SaveDesiredState :exec
INSERT INTO plugin_instances (plugin_id, desired_state, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(plugin_id) DO UPDATE SET
    desired_state = excluded.desired_state,
    updated_at = excluded.updated_at
`

type SaveDesiredStateParams struct {
	PluginID     string
	DesiredState string
	UpdatedAt    string
}

func (q *Queries) SaveDesiredState(ctx context.Context, arg SaveDesiredStateParams) error {
	_, err := q.db.ExecContext(ctx, saveDesiredState, arg.PluginID, arg.DesiredState, arg.UpdatedAt)
	return err
}

const saveGrant = `-- name: SaveGrant :exec
INSERT INTO plugin_grants (plugin_id, capability, scope_json, granted_at, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(plugin_id, capability) DO UPDATE SET
    scope_json = excluded.scope_json,
    granted_at = excluded.granted_at,
    expires_at = excluded.expires_at
`

type SaveGrantParams struct {
	PluginID   string
	Capability string
	ScopeJson  string
	GrantedAt  string
	ExpiresAt  sql.NullString
}

func (q *Queries) SaveGrant(ctx context.Context, arg SaveGrantParams) error {
	_, err := q.db.ExecContext(ctx, saveGrant,
		arg.PluginID,
		arg.Capability,
		arg.ScopeJson,
		arg.GrantedAt,
		arg.ExpiresAt,
	)
	return err
}

const savePackageMetadata = `-- name: SavePackageMetadata :exec
INSERT INTO plugin_packages (plugin_id, source_type, source_ref, version, manifest_hash, package_hash, installed_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(plugin_id) DO UPDATE SET
    source_type = excluded.source_type,
    source_ref = excluded.source_ref,
    version = excluded.version,
    manifest_hash = excluded.manifest_hash,
    package_hash = excluded.package_hash,
    installed_at = excluded.installed_at
`

type SavePackageMetadataParams struct {
	PluginID     string
	SourceType   string
	SourceRef    string
	Version      string
	ManifestHash string
	PackageHash  string
	InstalledAt  string
}

func (q *Queries) SavePackageMetadata(ctx context.Context, arg SavePackageMetadataParams) error {
	_, err := q.db.ExecContext(ctx, savePackageMetadata,
		arg.PluginID,
		arg.SourceType,
		arg.SourceRef,
		arg.Version,
		arg.ManifestHash,
		arg.PackageHash,
		arg.InstalledAt,
	)
	return err
}
