// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pluginconfig.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countNamespace = `-- name: CountNamespace :one
SELECT COUNT(*) FROM system_configs WHERE namespace = ?
`

func (q *Queries) CountNamespace(ctx context.Context, namespace string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNamespace, namespace)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listConfigsByNamespace = `-- name: ListConfigsByNamespace :many
SELECT key, value_json
FROM system_configs
WHERE namespace = ?
ORDER BY key ASC
`

type ListConfigsByNamespaceRow struct {
	Key       string
	ValueJson string
}

func (q *Queries) ListConfigsByNamespace(ctx context.Context, namespace string) ([]ListConfigsByNamespaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfigsByNamespace, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfigsByNamespaceRow{}
	for rows.Next() {
		var i ListConfigsByNamespaceRow
		if err := rows.Scan(&i.Key, &i.ValueJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedConfig = `-- name: SeedConfig :execresult
INSERT INTO system_configs (namespace, key, value_json, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(namespace, key) DO NOTHING
`

type SeedConfigParams struct {
	Namespace string
	Key       string
	ValueJson string
	UpdatedAt string
}

func (q *Queries) SeedConfig(ctx context.Context, arg SeedConfigParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, seedConfig,
		arg.Namespace,
		arg.Key,
		arg.ValueJson,
		arg.UpdatedAt,
	)
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO system_configs (namespace, key, value_json, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(namespace, key) DO UPDATE SET
    value_json = excluded.value_json,
    updated_at = excluded.updated_at
`

type UpsertConfigParams struct {
	Namespace string
	Key       string
	ValueJson string
	UpdatedAt string
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfig,
		arg.Namespace,
		arg.Key,
		arg.ValueJson,
		arg.UpdatedAt,
	)
	return err
}
