// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugin_store.sql

package sqlcgen

import (
	"context"
)

const createPluginStoreSource = `-- name: CreatePluginStoreSource :exec
INSERT INTO plugin_store_sources (source_id, name, url, official)
VALUES (?, ?, ?, 0)
`

type CreatePluginStoreSourceParams struct {
	SourceID string
	Name     string
	Url      string
}

func (q *Queries) CreatePluginStoreSource(ctx context.Context, arg CreatePluginStoreSourceParams) error {
	_, err := q.db.ExecContext(ctx, createPluginStoreSource, arg.SourceID, arg.Name, arg.Url)
	return err
}

const deletePluginStoreSource = `-- name: DeletePluginStoreSource :execrows
DELETE FROM plugin_store_sources
WHERE source_id = ? AND official = 0
`

func (q *Queries) DeletePluginStoreSource(ctx context.Context, sourceID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePluginStoreSource, sourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPluginStoreSource = `-- name: GetPluginStoreSource :one
SELECT source_id, name, url, official
FROM plugin_store_sources
WHERE source_id = ?
`

func (q *Queries) GetPluginStoreSource(ctx context.Context, sourceID string) (PluginStoreSource, error) {
	row := q.db.QueryRowContext(ctx, getPluginStoreSource, sourceID)
	var i PluginStoreSource
	err := row.Scan(
		&i.SourceID,
		&i.Name,
		&i.Url,
		&i.Official,
	)
	return i, err
}

const listPluginStoreSources = `-- name: ListPluginStoreSources :many
SELECT source_id, name, url, official
FROM plugin_store_sources
ORDER BY official DESC, name ASC, source_id ASC
`

func (q *Queries) ListPluginStoreSources(ctx context.Context) ([]PluginStoreSource, error) {
	rows, err := q.db.QueryContext(ctx, listPluginStoreSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginStoreSource{}
	for rows.Next() {
		var i PluginStoreSource
		if err := rows.Scan(
			&i.SourceID,
			&i.Name,
			&i.Url,
			&i.Official,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadPluginStoreCatalogCaches = `-- name: LoadPluginStoreCatalogCaches :many
SELECT source_id, catalog_json, refreshed_at
FROM plugin_store_catalog_cache
`

func (q *Queries) LoadPluginStoreCatalogCaches(ctx context.Context) ([]PluginStoreCatalogCache, error) {
	rows, err := q.db.QueryContext(ctx, loadPluginStoreCatalogCaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginStoreCatalogCache{}
	for rows.Next() {
		var i PluginStoreCatalogCache
		if err := rows.Scan(&i.SourceID, &i.CatalogJson, &i.RefreshedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePluginStoreCatalogCache = `-- name: SavePluginStoreCatalogCache :exec
INSERT INTO plugin_store_catalog_cache (source_id, catalog_json, refreshed_at)
VALUES (?, ?, ?)
ON CONFLICT(source_id) DO UPDATE SET
    catalog_json = excluded.catalog_json,
    refreshed_at = excluded.refreshed_at
`

type SavePluginStoreCatalogCacheParams struct {
	SourceID    string
	CatalogJson string
	RefreshedAt string
}

func (q *Queries) SavePluginStoreCatalogCache(ctx context.Context, arg SavePluginStoreCatalogCacheParams) error {
	_, err := q.db.ExecContext(ctx, savePluginStoreCatalogCache, arg.SourceID, arg.CatalogJson, arg.RefreshedAt)
	return err
}

const updatePluginStoreSource = `-- name: UpdatePluginStoreSource :execrows
UPDATE plugin_store_sources
SET name = ?, url = ?
WHERE source_id = ? AND official = 0
`

type UpdatePluginStoreSourceParams struct {
	Name     string
	Url      string
	SourceID string
}

func (q *Queries) UpdatePluginStoreSource(ctx context.Context, arg UpdatePluginStoreSourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginStoreSource, arg.Name, arg.Url, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
