// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pluginkv.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteKV = `-- name: DeleteKV :execresult
DELETE FROM plugin_kv WHERE plugin_id = ? AND key = ?
`

type DeleteKVParams struct {
	PluginID string
	Key      string
}

func (q *Queries) DeleteKV(ctx context.Context, arg DeleteKVParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteKV, arg.PluginID, arg.Key)
}

const getKV = `-- name: GetKV :one
SELECT value_json FROM plugin_kv WHERE plugin_id = ? AND key = ?
`

type GetKVParams struct {
	PluginID string
	Key      string
}

func (q *Queries) GetKV(ctx context.Context, arg GetKVParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getKV, arg.PluginID, arg.Key)
	var value_json string
	err := row.Scan(&value_json)
	return value_json, err
}

const getKVSize = `-- name: GetKVSize :one
SELECT COALESCE(size_bytes, 0) FROM plugin_kv WHERE plugin_id = ? AND key = ?
`

type GetKVSizeParams struct {
	PluginID string
	Key      string
}

func (q *Queries) GetKVSize(ctx context.Context, arg GetKVSizeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getKVSize, arg.PluginID, arg.Key)
	var size_bytes int64
	err := row.Scan(&size_bytes)
	return size_bytes, err
}

const getKVTotalSize = `-- name: GetKVTotalSize :one
SELECT CAST(COALESCE(SUM(size_bytes), 0) AS INTEGER) FROM plugin_kv WHERE plugin_id = ?
`

func (q *Queries) GetKVTotalSize(ctx context.Context, pluginID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getKVTotalSize, pluginID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertKV = `-- name: UpsertKV :exec
INSERT INTO plugin_kv (plugin_id, key, value_json, size_bytes, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(plugin_id, key) DO UPDATE SET
    value_json = excluded.value_json,
    size_bytes = excluded.size_bytes,
    updated_at = excluded.updated_at
`

type UpsertKVParams struct {
	PluginID  string
	Key       string
	ValueJson string
	SizeBytes int64
	UpdatedAt string
}

func (q *Queries) UpsertKV(ctx context.Context, arg UpsertKVParams) error {
	_, err := q.db.ExecContext(ctx, upsertKV,
		arg.PluginID,
		arg.Key,
		arg.ValueJson,
		arg.SizeBytes,
		arg.UpdatedAt,
	)
	return err
}
