// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pluginconfig.sql

package sqlcgen

import (
	"context"
)

const countNamespace = `-- name: CountNamespace :one
SELECT COUNT(*) FROM system_configs WHERE namespace = ?
`

func (q *Queries) CountNamespace(ctx context.Context, namespace string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNamespace, namespace)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seedConfig = `-- name: SeedConfig :exec
INSERT INTO system_configs (namespace, key, value_json, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(namespace, key) DO NOTHING
`

type SeedConfigParams struct {
	Namespace string
	Key       string
	ValueJson string
	UpdatedAt string
}

func (q *Queries) SeedConfig(ctx context.Context, arg SeedConfigParams) error {
	_, err := q.db.ExecContext(ctx, seedConfig,
		arg.Namespace,
		arg.Key,
		arg.ValueJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO system_configs (namespace, key, value_json, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(namespace, key) DO UPDATE SET
    value_json = excluded.value_json,
    updated_at = excluded.updated_at
`

type UpsertConfigParams struct {
	Namespace string
	Key       string
	ValueJson string
	UpdatedAt string
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfig,
		arg.Namespace,
		arg.Key,
		arg.ValueJson,
		arg.UpdatedAt,
	)
	return err
}
