// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: render.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteAllPluginRenderTemplates = `-- name: DeleteAllPluginRenderTemplates :exec
DELETE FROM render_template_states
WHERE source_type = 'plugin'
`

func (q *Queries) DeleteAllPluginRenderTemplates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPluginRenderTemplates)
	return err
}

const deletePluginRenderTemplates = `-- name: DeletePluginRenderTemplates :exec
DELETE FROM render_template_states
WHERE source_type = 'plugin' AND source_plugin_id = ?
`

func (q *Queries) DeletePluginRenderTemplates(ctx context.Context, sourcePluginID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deletePluginRenderTemplates, sourcePluginID)
	return err
}

const getRenderTemplateSyncState = `-- name: GetRenderTemplateSyncState :one
SELECT
    s.current_revision_id,
    r.source_digest,
    s.validation_valid,
    s.validation_issue_count,
    s.source_type,
    s.source_plugin_id,
    s.source_local_id
FROM render_template_states AS s
INNER JOIN render_template_revisions AS r ON r.revision_id = s.current_revision_id
WHERE s.template_id = ?
`

type GetRenderTemplateSyncStateRow struct {
	CurrentRevisionID    string
	SourceDigest         string
	ValidationValid      int64
	ValidationIssueCount int64
	SourceType           string
	SourcePluginID       sql.NullString
	SourceLocalID        sql.NullString
}

func (q *Queries) GetRenderTemplateSyncState(ctx context.Context, templateID string) (GetRenderTemplateSyncStateRow, error) {
	row := q.db.QueryRowContext(ctx, getRenderTemplateSyncState, templateID)
	var i GetRenderTemplateSyncStateRow
	err := row.Scan(
		&i.CurrentRevisionID,
		&i.SourceDigest,
		&i.ValidationValid,
		&i.ValidationIssueCount,
		&i.SourceType,
		&i.SourcePluginID,
		&i.SourceLocalID,
	)
	return i, err
}

const updateRenderTemplateSyncMetadata = `-- name: UpdateRenderTemplateSyncMetadata :exec
UPDATE render_template_states
SET
    validation_valid = ?,
    validation_checked_at = ?,
    validation_issue_count = ?,
    source_type = ?,
    source_plugin_id = ?,
    source_local_id = ?
WHERE template_id = ?
`

type UpdateRenderTemplateSyncMetadataParams struct {
	ValidationValid      int64
	ValidationCheckedAt  string
	ValidationIssueCount int64
	SourceType           string
	SourcePluginID       sql.NullString
	SourceLocalID        sql.NullString
	TemplateID           string
}

func (q *Queries) UpdateRenderTemplateSyncMetadata(ctx context.Context, arg UpdateRenderTemplateSyncMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateRenderTemplateSyncMetadata,
		arg.ValidationValid,
		arg.ValidationCheckedAt,
		arg.ValidationIssueCount,
		arg.SourceType,
		arg.SourcePluginID,
		arg.SourceLocalID,
		arg.TemplateID,
	)
	return err
}

const updateRenderTemplateValidation = `-- name: UpdateRenderTemplateValidation :execresult
UPDATE render_template_states
SET validation_valid = ?, validation_checked_at = ?, validation_issue_count = ?
WHERE template_id = ?
`

type UpdateRenderTemplateValidationParams struct {
	ValidationValid      int64
	ValidationCheckedAt  string
	ValidationIssueCount int64
	TemplateID           string
}

func (q *Queries) UpdateRenderTemplateValidation(ctx context.Context, arg UpdateRenderTemplateValidationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRenderTemplateValidation,
		arg.ValidationValid,
		arg.ValidationCheckedAt,
		arg.ValidationIssueCount,
		arg.TemplateID,
	)
}
