// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: render.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getRenderTemplate = `-- name: GetRenderTemplate :one
SELECT template_id, source_digest, updated_at, source_type, source_plugin_id, source_local_id, manifest_json, html, stylesheet, input_schema_json FROM render_templates WHERE template_id = ?
`

func (q *Queries) GetRenderTemplate(ctx context.Context, templateID string) (RenderTemplate, error) {
	row := q.db.QueryRowContext(ctx, getRenderTemplate, templateID)
	var i RenderTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.SourceDigest,
		&i.UpdatedAt,
		&i.SourceType,
		&i.SourcePluginID,
		&i.SourceLocalID,
		&i.ManifestJson,
		&i.Html,
		&i.Stylesheet,
		&i.InputSchemaJson,
	)
	return i, err
}

const listRenderTemplates = `-- name: ListRenderTemplates :many
SELECT template_id, source_digest, updated_at, source_type, source_plugin_id, source_local_id, manifest_json, html, stylesheet, input_schema_json FROM render_templates ORDER BY template_id
`

func (q *Queries) ListRenderTemplates(ctx context.Context) ([]RenderTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listRenderTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenderTemplate{}
	for rows.Next() {
		var i RenderTemplate
		if err := rows.Scan(
			&i.TemplateID,
			&i.SourceDigest,
			&i.UpdatedAt,
			&i.SourceType,
			&i.SourcePluginID,
			&i.SourceLocalID,
			&i.ManifestJson,
			&i.Html,
			&i.Stylesheet,
			&i.InputSchemaJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRenderTemplate = `-- name: UpsertRenderTemplate :exec
INSERT INTO render_templates (
    template_id, source_digest, updated_at, source_type,
    source_plugin_id, source_local_id, manifest_json, html, stylesheet, input_schema_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(template_id) DO UPDATE SET
    source_digest = excluded.source_digest,
    updated_at = excluded.updated_at,
    manifest_json = excluded.manifest_json,
    html = excluded.html,
    stylesheet = excluded.stylesheet,
    input_schema_json = excluded.input_schema_json
`

type UpsertRenderTemplateParams struct {
	TemplateID      string
	SourceDigest    string
	UpdatedAt       string
	SourceType      string
	SourcePluginID  sql.NullString
	SourceLocalID   sql.NullString
	ManifestJson    string
	Html            string
	Stylesheet      string
	InputSchemaJson sql.NullString
}

func (q *Queries) UpsertRenderTemplate(ctx context.Context, arg UpsertRenderTemplateParams) error {
	_, err := q.db.ExecContext(ctx, upsertRenderTemplate,
		arg.TemplateID,
		arg.SourceDigest,
		arg.UpdatedAt,
		arg.SourceType,
		arg.SourcePluginID,
		arg.SourceLocalID,
		arg.ManifestJson,
		arg.Html,
		arg.Stylesheet,
		arg.InputSchemaJson,
	)
	return err
}
