// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheduler.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM scheduler_jobs WHERE job_id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, jobID)
	return err
}

const deleteJobsByPlugin = `-- name: DeleteJobsByPlugin :exec
DELETE FROM scheduler_jobs WHERE plugin_id = ?
`

func (q *Queries) DeleteJobsByPlugin(ctx context.Context, pluginID string) error {
	_, err := q.db.ExecContext(ctx, deleteJobsByPlugin, pluginID)
	return err
}

const loadJobs = `-- name: LoadJobs :many
SELECT job_id, plugin_id, cron_expr, payload, enabled, next_run, last_run, created_at, updated_at
FROM scheduler_jobs ORDER BY created_at ASC
`

func (q *Queries) LoadJobs(ctx context.Context) ([]SchedulerJob, error) {
	rows, err := q.db.QueryContext(ctx, loadJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulerJob{}
	for rows.Next() {
		var i SchedulerJob
		if err := rows.Scan(
			&i.JobID,
			&i.PluginID,
			&i.CronExpr,
			&i.Payload,
			&i.Enabled,
			&i.NextRun,
			&i.LastRun,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJob = `-- name: SaveJob :exec
INSERT INTO scheduler_jobs (job_id, plugin_id, cron_expr, payload, enabled, next_run, last_run, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(job_id) DO UPDATE SET
    cron_expr = excluded.cron_expr,
    payload = excluded.payload,
    enabled = excluded.enabled,
    next_run = excluded.next_run,
    last_run = excluded.last_run,
    updated_at = excluded.updated_at
`

type SaveJobParams struct {
	JobID     string
	PluginID  string
	CronExpr  string
	Payload   string
	Enabled   int64
	NextRun   string
	LastRun   sql.NullString
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) error {
	_, err := q.db.ExecContext(ctx, saveJob,
		arg.JobID,
		arg.PluginID,
		arg.CronExpr,
		arg.Payload,
		arg.Enabled,
		arg.NextRun,
		arg.LastRun,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
