// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secrets.sql

package sqlcgen

import (
	"context"
)

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secret_store WHERE key = ?
`

func (q *Queries) DeleteSecret(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, key)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT value FROM secret_store WHERE key = ?
`

func (q *Queries) GetSecret(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSecret, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const listSecretKeys = `-- name: ListSecretKeys :many
SELECT key FROM secret_store ORDER BY key
`

func (q *Queries) ListSecretKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSecretKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSecret = `-- name: UpsertSecret :exec
INSERT INTO secret_store (key, value, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertSecretParams struct {
	Key       string
	Value     []byte
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertSecret,
		arg.Key,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
