// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: storage.sql

package sqlcgen

import (
	"context"
)

const listSchemaMigrations = `-- name: ListSchemaMigrations :many
SELECT version, name, applied_at FROM schema_migrations ORDER BY version
`

func (q *Queries) ListSchemaMigrations(ctx context.Context) ([]SchemaMigration, error) {
	rows, err := q.db.QueryContext(ctx, listSchemaMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemaMigration{}
	for rows.Next() {
		var i SchemaMigration
		if err := rows.Scan(&i.Version, &i.Name, &i.AppliedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
