// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package sqlcgen

import (
	"context"
)

const readSchemaMetadata = `-- name: ReadSchemaMetadata :one
SELECT version, initialized_at FROM schema_metadata WHERE singleton_id = 1
`

type ReadSchemaMetadataRow struct {
	Version       string
	InitializedAt string
}

func (q *Queries) ReadSchemaMetadata(ctx context.Context) (ReadSchemaMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, readSchemaMetadata)
	var i ReadSchemaMetadataRow
	err := row.Scan(&i.Version, &i.InitializedAt)
	return i, err
}
