// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE task_id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, taskID)
	return err
}

const loadTasks = `-- name: LoadTasks :many
SELECT task_id, task_type, status, progress, summary, started_at, finished_at, result_json, error_json
FROM tasks ORDER BY created_at ASC
`

type LoadTasksRow struct {
	TaskID     string
	TaskType   string
	Status     string
	Progress   int64
	Summary    string
	StartedAt  sql.NullString
	FinishedAt sql.NullString
	ResultJson sql.NullString
	ErrorJson  sql.NullString
}

func (q *Queries) LoadTasks(ctx context.Context) ([]LoadTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, loadTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadTasksRow{}
	for rows.Next() {
		var i LoadTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskType,
			&i.Status,
			&i.Progress,
			&i.Summary,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ResultJson,
			&i.ErrorJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTask = `-- name: SaveTask :exec
INSERT INTO tasks (task_id, task_type, status, progress, summary, started_at, finished_at, result_json, error_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(task_id) DO UPDATE SET
    status = CASE
        WHEN tasks.status IN ('succeeded', 'failed', 'cancelled', 'interrupted')
            AND excluded.status IN ('pending', 'running')
        THEN tasks.status
        ELSE excluded.status
    END,
    progress = CASE
        WHEN tasks.status IN ('succeeded', 'failed', 'cancelled', 'interrupted')
            AND excluded.status IN ('pending', 'running')
        THEN tasks.progress
        ELSE excluded.progress
    END,
    summary = CASE
        WHEN tasks.status IN ('succeeded', 'failed', 'cancelled', 'interrupted')
            AND excluded.status IN ('pending', 'running')
        THEN tasks.summary
        ELSE excluded.summary
    END,
    started_at = CASE
        WHEN tasks.status IN ('succeeded', 'failed', 'cancelled', 'interrupted')
            AND excluded.status IN ('pending', 'running')
        THEN tasks.started_at
        ELSE excluded.started_at
    END,
    finished_at = CASE
        WHEN tasks.status IN ('succeeded', 'failed', 'cancelled', 'interrupted')
            AND excluded.status IN ('pending', 'running')
        THEN tasks.finished_at
        ELSE excluded.finished_at
    END,
    result_json = CASE
        WHEN tasks.status IN ('succeeded', 'failed', 'cancelled', 'interrupted')
            AND excluded.status IN ('pending', 'running')
        THEN tasks.result_json
        ELSE excluded.result_json
    END,
    error_json = CASE
        WHEN tasks.status IN ('succeeded', 'failed', 'cancelled', 'interrupted')
            AND excluded.status IN ('pending', 'running')
        THEN tasks.error_json
        ELSE excluded.error_json
    END
`

type SaveTaskParams struct {
	TaskID     string
	TaskType   string
	Status     string
	Progress   int64
	Summary    string
	StartedAt  sql.NullString
	FinishedAt sql.NullString
	ResultJson sql.NullString
	ErrorJson  sql.NullString
	CreatedAt  string
}

func (q *Queries) SaveTask(ctx context.Context, arg SaveTaskParams) error {
	_, err := q.db.ExecContext(ctx, saveTask,
		arg.TaskID,
		arg.TaskType,
		arg.Status,
		arg.Progress,
		arg.Summary,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ResultJson,
		arg.ErrorJson,
		arg.CreatedAt,
	)
	return err
}
