// Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.
package pluginwire

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
	"io"
	"sync"
)

//go:embed protocol.schema.json
var schemaJSON []byte
var compileOnce sync.Once
var compiled *jsonschema.Schema
var compileError error
var ErrFrameTooLarge = errors.New("plugin protocol frame exceeds byte limit")

type ValidationError struct{ Cause error }

func (e *ValidationError) Error() string { return "plugin frame violates the protocol schema" }
func (e *ValidationError) Unwrap() error { return e.Cause }

func Validate(data []byte, maxBytes int) error {
	data = bytes.TrimSuffix(data, []byte{'\n'})
	if maxBytes <= 0 {
		maxBytes = DefaultMaxFrameBytes
	}
	if len(data) > maxBytes {
		return fmt.Errorf("%w: limit=%d", ErrFrameTooLarge, maxBytes)
	}
	compileOnce.Do(func() {
		var document any
		if compileError = json.Unmarshal(schemaJSON, &document); compileError != nil {
			return
		}
		compiler := jsonschema.NewCompiler()
		compiler.AssertFormat()
		const location = "urn:rayleabot:plugin-protocol"
		if compileError = compiler.AddResource(location, document); compileError != nil {
			return
		}
		compiled, compileError = compiler.Compile(location)
	})
	if compileError != nil {
		return fmt.Errorf("compile plugin schema: %w", compileError)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var value any
	if err := decoder.Decode(&value); err != nil {
		return err
	}
	if err := decoder.Decode(new(any)); err != io.EOF {
		return errors.New("plugin frame must contain exactly one JSON value")
	}
	if err := compiled.Validate(value); err != nil {
		return &ValidationError{Cause: err}
	}
	return nil
}
