// Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.

package pluginwire

import "encoding/json"

type FrameEnvelope struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
}

type InitFrame struct {
	Type                 string         `json:"type"`
	RequestID            string         `json:"request_id"`
	Timezone             string         `json:"timezone"`
	CommandPrefixes      []string       `json:"command_prefixes"`
	ProtocolVersion      string         `json:"protocol_version"`
	PluginID             string         `json:"plugin_id"`
	Config               map[string]any `json:"config"`
	EffectivePermissions []string       `json:"effective_permissions"`
	SuperAdmins          []string       `json:"super_admins"`
	Concurrency          int            `json:"concurrency"`
	Bots                 []BotIdentity  `json:"bots"`
}

type InitProgressFrame struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
	Summary   string `json:"summary"`
}

type InitAckFrame struct {
	Type         string `json:"type"`
	RequestID    string `json:"request_id"`
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message,omitempty"`
}

type EventFrame struct {
	Type      string             `json:"type"`
	RequestID string             `json:"request_id"`
	Event     ProtocolEventFrame `json:"event"`
}

type ProtocolEventFrame struct {
	EventID        string                `json:"event_id"`
	SourceProtocol string                `json:"source_protocol"`
	SourceAdapter  string                `json:"source_adapter"`
	EventType      string                `json:"event_type"`
	Timestamp      int64                 `json:"timestamp"`
	Actor          *ProtocolActorFrame   `json:"actor,omitempty"`
	Target         *ProtocolTargetFrame  `json:"target,omitempty"`
	Payload        *ProtocolPayloadFrame `json:"payload,omitempty"`
	Message        *ProtocolMessageFrame `json:"message,omitempty"`
	RawPayload     any                   `json:"raw_payload,omitempty"`
	Webhook        *ProtocolWebhookFrame `json:"webhook,omitempty"`
}

type ProtocolActorFrame struct {
	ID       string `json:"id"`
	Nickname string `json:"nickname,omitempty"`
	Role     string `json:"role,omitempty"`
}

type ProtocolTargetFrame struct {
	Type string `json:"type"`
	ID   string `json:"id"`
	Name string `json:"name,omitempty"`
}

type ProtocolMessageFrame struct {
	Segments  []ProtocolSegmentFrame `json:"segments,omitempty"`
	PlainText string                 `json:"plain_text,omitempty"`
}

type ProtocolWebhookFrame struct {
	Route           string `json:"route"`
	ReceivedAt      int64  `json:"received_at"`
	ClientTimestamp *int64 `json:"client_timestamp,omitempty"`
	ClientEventID   string `json:"client_event_id,omitempty"`
}

type ProtocolPayloadFrame struct {
	Command     json.RawMessage                 `json:"command,omitempty"`
	Args        []string                        `json:"args,omitempty"`
	Action      string                          `json:"action,omitempty"`
	Payload     map[string]any                  `json:"payload,omitempty"`
	MessageID   string                          `json:"message_id,omitempty"`
	SubType     string                          `json:"sub_type,omitempty"`
	OperatorID  string                          `json:"operator_id,omitempty"`
	QQOfficial  *ProtocolQQOfficialPayloadFrame `json:"qq_official,omitempty"`
	OneBot      *ProtocolOneBotPayloadFrame     `json:"onebot,omitempty"`
	Config      *map[string]any                 `json:"config,omitempty"`
	ChangedKeys []string                        `json:"changed_keys,omitempty"`
	Bots        *[]BotIdentity                  `json:"bots,omitempty"`
}

type ProtocolOneBotPayloadFrame struct {
	PostType      string                     `json:"post_type,omitempty"`
	MetaEventType string                     `json:"meta_event_type,omitempty"`
	MessageType   string                     `json:"message_type,omitempty"`
	RequestType   string                     `json:"request_type,omitempty"`
	NoticeType    string                     `json:"notice_type,omitempty"`
	SubType       string                     `json:"sub_type,omitempty"`
	SelfID        string                     `json:"self_id,omitempty"`
	UserID        string                     `json:"user_id,omitempty"`
	GroupID       string                     `json:"group_id,omitempty"`
	TargetID      string                     `json:"target_id,omitempty"`
	Time          int64                      `json:"time,omitempty"`
	Interval      int                        `json:"interval,omitempty"`
	MessageID     string                     `json:"message_id,omitempty"`
	RealID        string                     `json:"real_id,omitempty"`
	MessageSeq    string                     `json:"message_seq,omitempty"`
	RawMessage    string                     `json:"raw_message,omitempty"`
	Font          int                        `json:"font,omitempty"`
	MessageFormat string                     `json:"message_format,omitempty"`
	Sender        *ProtocolOneBotSenderFrame `json:"sender,omitempty"`
	Comment       string                     `json:"comment,omitempty"`
	Flag          string                     `json:"flag,omitempty"`
	Status        map[string]any             `json:"status,omitempty"`
}

type ProtocolOneBotSenderFrame struct {
	UserID   string `json:"user_id,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Card     string `json:"card,omitempty"`
	Role     string `json:"role,omitempty"`
	Title    string `json:"title,omitempty"`
	Sex      string `json:"sex,omitempty"`
	Age      int    `json:"age,omitempty"`
}

type ProtocolQQOfficialPayloadFrame struct {
	DispatchType string `json:"dispatch_type,omitempty"`
	MessageID    string `json:"message_id,omitempty"`
	GroupOpenID  string `json:"group_openid,omitempty"`
	UserOpenID   string `json:"user_openid,omitempty"`
	MemberOpenID string `json:"member_openid,omitempty"`
	MemberRole   string `json:"member_role,omitempty"`
}

type BotIdentity struct {
	SourceAdapter  string `json:"source_adapter"`
	SourceProtocol string `json:"source_protocol"`
	ID             string `json:"id"`
	Nickname       string `json:"nickname,omitempty"`
}

type GovernanceScope struct {
	SourceProtocol string `json:"source_protocol"`
	SourceAdapter  string `json:"source_adapter"`
	BotID          string `json:"bot_id"`
	Kind           string `json:"kind"`
}

type ProtocolSegmentFrame struct {
	Type string         `json:"type"`
	Data map[string]any `json:"data,omitempty"`
}

type ProtocolOutboundMessageFrame struct {
	Segments []ProtocolSegmentFrame `json:"segments"`
}

type PingFrame struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
}

type PongFrame struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
}

type ShutdownFrame struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
	Reason    string `json:"reason"`
}

type ErrorFrame struct {
	Type      string         `json:"type"`
	RequestID string         `json:"request_id"`
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	Details   map[string]any `json:"details,omitempty"`
}

type ResultFrame struct {
	Type      string         `json:"type"`
	RequestID string         `json:"request_id"`
	Status    string         `json:"status"`
	Data      map[string]any `json:"data"`
}

type ActionFrame struct {
	Type            string          `json:"type"`
	RequestID       string          `json:"request_id"`
	ParentRequestID string          `json:"parent_request_id,omitempty"`
	Action          string          `json:"action"`
	Data            json.RawMessage `json:"data"`
}

type ProtocolActionMessageSendFrame struct {
	SourceProtocol          string                        `json:"source_protocol,omitempty"`
	SourceAdapter           *string                       `json:"source_adapter,omitempty"`
	TargetType              string                        `json:"target_type"`
	TargetID                string                        `json:"target_id"`
	Message                 *ProtocolOutboundMessageFrame `json:"message"`
	ReplyToEventID          *string                       `json:"reply_to_event_id,omitempty"`
	FallbackToSendIfMissing bool                          `json:"fallback_to_send_if_missing,omitempty"`
}

type ProtocolActionLoggerWriteFrame struct {
	Level   string         `json:"level"`
	Message string         `json:"message"`
	Fields  map[string]any `json:"fields,omitempty"`
}

type ProtocolActionStorageKVFrame struct {
	Operation string          `json:"operation"`
	Key       *string         `json:"key,omitempty"`
	Value     json.RawMessage `json:"value,omitempty"`
	Prefix    *string         `json:"prefix,omitempty"`
}

type ProtocolActionStorageFileFrame struct {
	Operation     string  `json:"operation"`
	Path          *string `json:"path,omitempty"`
	ContentText   *string `json:"content_text,omitempty"`
	ContentBase64 *string `json:"content_base64,omitempty"`
	Prefix        *string `json:"prefix,omitempty"`
}

type ProtocolActionHTTPRequestFrame struct {
	Method         string            `json:"method"`
	URL            string            `json:"url"`
	Headers        map[string]string `json:"headers,omitempty"`
	TimeoutSeconds *int              `json:"timeout_seconds,omitempty"`
	BodyText       *string           `json:"body_text,omitempty"`
	BodyBase64     *string           `json:"body_base64,omitempty"`
}

type ProtocolActionPluginListFrame struct {
	Visibility string `json:"visibility,omitempty"`
}

type ProtocolActionSecretReadFrame struct {
	Key string `json:"key"`
}

type ProtocolActionThirdPartyAccountReadFrame struct {
	Platform  string `json:"platform"`
	AccountID string `json:"account_id,omitempty"`
}

type ProtocolActionThirdPartyAccountValidateFrame struct {
	Platform    string `json:"platform"`
	AccountID   string `json:"account_id"`
	Observation string `json:"observation"`
	HTTPStatus  int    `json:"http_status,omitempty"`
}

type ProtocolActionThirdPartyResolveFrame struct {
	Platform string `json:"platform"`
	Query    string `json:"query"`
	Cookie   string `json:"cookie,omitempty"`
}

type ProtocolActionConfigWriteFrame struct {
	Values map[string]json.RawMessage `json:"values"`
}

type ProtocolActionGovernanceBlacklistWriteFrame struct {
	Operation string          `json:"operation"`
	EntryType *string         `json:"entry_type,omitempty"`
	TargetID  *string         `json:"target_id,omitempty"`
	Reason    *string         `json:"reason,omitempty"`
	Scope     GovernanceScope `json:"scope,omitempty"`
}

type ProtocolActionGovernanceWhitelistWriteFrame struct {
	Operation string          `json:"operation"`
	Enabled   *bool           `json:"enabled,omitempty"`
	EntryType *string         `json:"entry_type,omitempty"`
	TargetID  *string         `json:"target_id,omitempty"`
	Reason    *string         `json:"reason,omitempty"`
	Scope     GovernanceScope `json:"scope,omitempty"`
}

type ProtocolActionSchedulerCreateFrame struct {
	TaskID    string          `json:"task_id"`
	LogLabel  string          `json:"log_label,omitempty"`
	Cron      string          `json:"cron"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload,omitempty"`
}

type ProtocolActionRenderImageFrame struct {
	Template     string                             `json:"template"`
	Theme        string                             `json:"theme,omitempty"`
	Output       string                             `json:"output,omitempty"`
	FallbackText string                             `json:"fallback_text,omitempty"`
	Resources    []ProtocolRenderImageResourceFrame `json:"resources,omitempty"`
	Data         json.RawMessage                    `json:"data"`
}

type ProtocolRenderImageResourceFrame struct {
	ID           string   `json:"id"`
	URL          string   `json:"url"`
	FallbackURLs []string `json:"fallback_urls,omitempty"`
	Referer      string   `json:"referer,omitempty"`
}

type Frame struct {
	Type                 string          `json:"type"`
	RequestID            string          `json:"request_id"`
	Timezone             string          `json:"timezone,omitempty"`
	CommandPrefixes      []string        `json:"command_prefixes,omitempty"`
	ProtocolVersion      string          `json:"protocol_version,omitempty"`
	PluginID             string          `json:"plugin_id,omitempty"`
	Config               map[string]any  `json:"config,omitempty"`
	EffectivePermissions []string        `json:"effective_permissions,omitempty"`
	SuperAdmins          []string        `json:"super_admins,omitempty"`
	Concurrency          int             `json:"concurrency,omitempty"`
	Bots                 *[]BotIdentity  `json:"bots,omitempty"`
	Summary              string          `json:"summary,omitempty"`
	Status               string          `json:"status,omitempty"`
	ErrorMessage         string          `json:"error_message,omitempty"`
	Event                json.RawMessage `json:"event,omitempty"`
	ParentRequestID      string          `json:"parent_request_id,omitempty"`
	Action               string          `json:"action,omitempty"`
	Data                 json.RawMessage `json:"data,omitempty"`
	Code                 string          `json:"code,omitempty"`
	Message              string          `json:"message,omitempty"`
	Details              map[string]any  `json:"details,omitempty"`
	Reason               string          `json:"reason,omitempty"`
}

func (frame Frame) MarshalJSON() ([]byte, error) {
	type plain Frame
	encoded, err := json.Marshal(plain(frame))
	if err != nil {
		return nil, err
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(encoded, &object); err != nil {
		return nil, err
	}
	switch frame.Type {
	case "init":
		if _, present := object["bots"]; !present {
			value, err := json.Marshal(frame.Bots)
			if err != nil {
				return nil, err
			}
			object["bots"] = value
		}
		if _, present := object["command_prefixes"]; !present {
			value, err := json.Marshal(frame.CommandPrefixes)
			if err != nil {
				return nil, err
			}
			object["command_prefixes"] = value
		}
		if _, present := object["concurrency"]; !present {
			value, err := json.Marshal(frame.Concurrency)
			if err != nil {
				return nil, err
			}
			object["concurrency"] = value
		}
		if _, present := object["config"]; !present {
			value, err := json.Marshal(frame.Config)
			if err != nil {
				return nil, err
			}
			object["config"] = value
		}
		if _, present := object["effective_permissions"]; !present {
			value, err := json.Marshal(frame.EffectivePermissions)
			if err != nil {
				return nil, err
			}
			object["effective_permissions"] = value
		}
		if _, present := object["plugin_id"]; !present {
			value, err := json.Marshal(frame.PluginID)
			if err != nil {
				return nil, err
			}
			object["plugin_id"] = value
		}
		if _, present := object["protocol_version"]; !present {
			value, err := json.Marshal(frame.ProtocolVersion)
			if err != nil {
				return nil, err
			}
			object["protocol_version"] = value
		}
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["super_admins"]; !present {
			value, err := json.Marshal(frame.SuperAdmins)
			if err != nil {
				return nil, err
			}
			object["super_admins"] = value
		}
		if _, present := object["timezone"]; !present {
			value, err := json.Marshal(frame.Timezone)
			if err != nil {
				return nil, err
			}
			object["timezone"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "init_progress":
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["summary"]; !present {
			value, err := json.Marshal(frame.Summary)
			if err != nil {
				return nil, err
			}
			object["summary"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "init_ack":
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["status"]; !present {
			value, err := json.Marshal(frame.Status)
			if err != nil {
				return nil, err
			}
			object["status"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "event":
		if _, present := object["event"]; !present {
			value, err := json.Marshal(frame.Event)
			if err != nil {
				return nil, err
			}
			object["event"] = value
		}
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "action":
		if _, present := object["action"]; !present {
			value, err := json.Marshal(frame.Action)
			if err != nil {
				return nil, err
			}
			object["action"] = value
		}
		if _, present := object["data"]; !present {
			value, err := json.Marshal(frame.Data)
			if err != nil {
				return nil, err
			}
			object["data"] = value
		}
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "result":
		if _, present := object["data"]; !present {
			value, err := json.Marshal(frame.Data)
			if err != nil {
				return nil, err
			}
			object["data"] = value
		}
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["status"]; !present {
			value, err := json.Marshal(frame.Status)
			if err != nil {
				return nil, err
			}
			object["status"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "error":
		if _, present := object["code"]; !present {
			value, err := json.Marshal(frame.Code)
			if err != nil {
				return nil, err
			}
			object["code"] = value
		}
		if _, present := object["message"]; !present {
			value, err := json.Marshal(frame.Message)
			if err != nil {
				return nil, err
			}
			object["message"] = value
		}
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "ping":
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "pong":
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	case "shutdown":
		if _, present := object["reason"]; !present {
			value, err := json.Marshal(frame.Reason)
			if err != nil {
				return nil, err
			}
			object["reason"] = value
		}
		if _, present := object["request_id"]; !present {
			value, err := json.Marshal(frame.RequestID)
			if err != nil {
				return nil, err
			}
			object["request_id"] = value
		}
		if _, present := object["type"]; !present {
			value, err := json.Marshal(frame.Type)
			if err != nil {
				return nil, err
			}
			object["type"] = value
		}
	}
	return json.Marshal(object)
}

const ProtocolVersion = "3"
const DefaultMaxFrameBytes = 8388608
