packages:
  - "."

supportedArchitectures:
  os:
    - win32
    - linux
    - darwin
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl

overrides:
  "@fluentui/react-motion": 9.16.1
  js-yaml: 4.2.0
  undici: 7.28.0
