// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EnvironmentCheckResult {
    "scope": string;
    "code": string;
    "title": string;
    "severity": string;
    "summary": string;
    "detail": string;
    "remediation": string;
}

export interface LauncherAdvancedOverrides {
    "serverExecutablePath"?: string;
    "configPath"?: string;
    "workdir"?: string;
}

export interface LauncherCloseConfirmResponse {
    "action": string;
    "setAsDefault": boolean;
}

export interface LauncherLocalSnapshot {
    "processId": number | null;
    "processLifecycle": string;
    "processOwnership": string;
    "environmentChecks": EnvironmentCheckResult[] | null;
    "preflightChecks": EnvironmentCheckResult[] | null;
    "advisoryChecks": EnvironmentCheckResult[] | null;
    "recentStderr": string[] | null;
    "runtimePrepare": RuntimePrepareSnapshot | null;
    "releaseCheck": ReleaseCheckSnapshot;
    "lastLocalError": string;
    "statusHint": string;
    "settings": LauncherSettings;
    "resolvedSettings": LauncherResolvedSettings;
    "endpoint": ServerEndpoint;
    "localRecoverySummary": ServerRecoveryCompatibilitySummary | null;
}

export interface LauncherResolvedSettings {
    "installationRoot": string;
    "serverExecutablePath": string;
    "configPath": string;
    "workdir": string;
}

export interface LauncherServerSnapshot {
    "health": ServerLivenessStatusResponse | null;
    "readiness": ServerReadinessStatusResponse | null;
    "systemStatus": ServerSystemStatusResponse | null;
}

export interface LauncherSettings {
    "installationRoot": string;
    "closeBehavior": string;
    "advancedOverrides"?: LauncherAdvancedOverrides | null;
}

export interface LauncherSnapshot {
    "server": LauncherServerSnapshot;
    "launcher": LauncherLocalSnapshot;
}

export interface ReleaseCheckSnapshot {
    "status": string;
    "currentVersion": string;
    "latestVersion": string;
    "summary": string;
    "detail": string;
    "errorCode": string;
    "releasePageUrl": string;
    "updateAvailable": boolean;
    "downloadProgress": number | null;
    "downloadedBytes": number | null;
    "totalBytes": number | null;
    "artifactFileName": string;
    "canCheck": boolean;
    "canDownload": boolean;
    "canInstall": boolean;
}

export interface RuntimePrepareResourceProgress {
    "kind": string;
    "label": string;
    "resourceId": string;
    "version": string;
    "sourceLabel": string;
    "sourceUrl": string;
    "archivePath": string;
    "storeRoot": string;
    "stage": string;
    "status": string;
    "progress": number | null;
    "downloadedBytes": number | null;
    "totalBytes": number | null;
    "extractedEntries": number | null;
    "totalEntries": number | null;
    "summary": string;
    "error": string;
    "updatedAt": string;
}

export interface RuntimePrepareSnapshot {
    "active": boolean;
    "currentKind": string;
    "summary": string;
    "resources": RuntimePrepareResourceProgress[] | null;
}

export type ServerAdapterProtocol = string;

export type ServerAdapterState = string;

export interface ServerAdapterStatus {
    "id": string;
    "protocol": ServerAdapterProtocol;
    "enabled": boolean;
    "state": ServerAdapterState;
}

export interface ServerDiagnosticIssue {
    "code": string;
    "severity": string;
    "summary": string;
    "user_message"?: string;
    "remediation"?: string;
    "internal_reason"?: string;
    "runtime_resources"?: string[] | null;
}

export interface ServerEndpoint {
    "host": string;
    "port": number;
    "baseUrl": string;
}

export interface ServerLivenessStatusResponse {
    "status": string;
}

export interface ServerReadinessStatusResponse {
    "status": string;
    "reason"?: string;
    "reason_codes"?: string[] | null;
    "checks"?: ServerReadinessStatusResponseChecks | null;
    "issues"?: ServerDiagnosticIssue[] | null;
    "recovery_summary"?: ServerRecoveryCompatibilitySummary | null;
}

export interface ServerReadinessStatusResponseChecks {
    "config"?: string;
    "database"?: string;
    "runtime"?: string;
    "render"?: string;
}

export interface ServerRecoveryCompatibilityAuditEntry {
    "task_id": string;
    "created_at": string;
    "operator_id": string;
    "note": string;
    "items": ServerRecoveryCompatibilityAuditItem[] | null;
}

export interface ServerRecoveryCompatibilityAuditItem {
    "review_id": string;
    "plugin_id": string;
    "reason_code": string;
    "summary": string;
    "version"?: string;
}

export interface ServerRecoveryCompatibilityIssue {
    "code": string;
    "severity": string;
    "summary": string;
    "remediation"?: string;
    "runtime_resources"?: string[] | null;
}

export interface ServerRecoveryCompatibilitySkippedPlugin {
    "plugin_id": string;
    "version"?: string;
    "reason_code": string;
    "summary": string;
    "review_id": string;
    "review_status": string;
    "reviewed_at"?: string;
    "reviewed_by"?: string;
    "manual_action"?: string;
    "manifest_path"?: string;
}

export interface ServerRecoveryCompatibilitySummary {
    "status": string;
    "phase": string;
    "operation": string;
    "created_at": string;
    "updated_at": string;
    "source_core_version"?: string;
    "target_core_version"?: string;
    "source_config_schema_version"?: string;
    "target_config_schema_version"?: string;
    "source_db_schema_version"?: string;
    "target_db_schema_version"?: string;
    "requires_post_start_checks"?: boolean;
    "issues"?: ServerRecoveryCompatibilityIssue[] | null;
    "skipped_plugins"?: ServerRecoveryCompatibilitySkippedPlugin[] | null;
    "manual_actions"?: string[] | null;
    "next_steps"?: string[] | null;
    "audit"?: ServerRecoveryCompatibilityAuditEntry[] | null;
}

export interface ServerSystemStatusResponse {
    "status": string;
    "adapters": ServerAdapterStatus[] | null;
    "active_plugins"?: number;
    "running_plugins"?: number;
    "failed_plugins"?: number;
    "db_schema_version"?: string;
    "uptime_seconds"?: number;
    "recovery_summary"?: ServerRecoveryCompatibilitySummary | null;
    "health"?: ServerReadinessStatusResponse | null;
}
