// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EnvironmentCheckResult {
    "scope": string;
    "code": string;
    "title": string;
    "severity": string;
    "summary": string;
    "detail": string;
    "remediation": string;
}

export interface LauncherAdvancedOverrides {
    "serverExecutablePath"?: string;
    "configPath"?: string;
    "workdir"?: string;
}

export interface LauncherCloseConfirmResponse {
    "action": string;
    "setAsDefault": boolean;
}

export interface LauncherLocalSnapshot {
    "processId": number | null;
    "processLifecycle": string;
    "processOwnership": string;
    "environmentChecks": EnvironmentCheckResult[] | null;
    "preflightChecks": EnvironmentCheckResult[] | null;
    "advisoryChecks": EnvironmentCheckResult[] | null;
    "recentStderr": string[] | null;
    "runtimePrepare": RuntimePrepareSnapshot | null;
    "releaseCheck": ReleaseCheckSnapshot;
    "lastLocalError": string;
    "statusHint": string;
    "settings": LauncherSettings;
    "resolvedSettings": LauncherResolvedSettings;
    "endpoint": ServerEndpoint;
    "localRecoverySummary": any;
}

export interface LauncherResolvedSettings {
    "installationRoot": string;
    "serverExecutablePath": string;
    "configPath": string;
    "workdir": string;
}

export interface LauncherServerSnapshot {
    "health": any;
    "readiness": any;
    "systemStatus": any;
}

export interface LauncherSettings {
    "installationRoot": string;
    "closeBehavior": string;
    "advancedOverrides"?: LauncherAdvancedOverrides | null;
}

export interface LauncherSnapshot {
    "server": LauncherServerSnapshot;
    "launcher": LauncherLocalSnapshot;
}

export interface ReleaseCheckSnapshot {
    "status": string;
    "currentVersion": string;
    "latestVersion": string;
    "summary": string;
    "detail": string;
    "errorCode": string;
    "releasePageUrl": string;
    "updateAvailable": boolean;
    "downloadProgress": number | null;
    "downloadedBytes": number | null;
    "totalBytes": number | null;
    "artifactFileName": string;
    "canCheck": boolean;
    "canDownload": boolean;
    "canInstall": boolean;
}

export interface RuntimePrepareResourceProgress {
    "kind": string;
    "label": string;
    "resourceId": string;
    "version": string;
    "sourceLabel": string;
    "sourceUrl": string;
    "archivePath": string;
    "storeRoot": string;
    "stage": string;
    "status": string;
    "progress": number | null;
    "downloadedBytes": number | null;
    "totalBytes": number | null;
    "extractedEntries": number | null;
    "totalEntries": number | null;
    "summary": string;
    "error": string;
    "updatedAt": string;
}

export interface RuntimePrepareSnapshot {
    "active": boolean;
    "currentKind": string;
    "summary": string;
    "resources": RuntimePrepareResourceProgress[] | null;
}

export interface ServerEndpoint {
    "host": string;
    "port": number;
    "baseUrl": string;
}
