// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum CheckSeverity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CheckOK = "ok",
    CheckWarning = "warning",
    CheckError = "error",
};

export interface EnvironmentCheckResult {
    "scope": EnvironmentCheckScope;
    "code": string;
    "title": string;
    "severity": CheckSeverity;
    "summary": string;
    "detail": string;
    "remediation": string;
}

export enum EnvironmentCheckScope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ScopePreflight = "preflight",
    ScopeAdvisory = "advisory",
};

export interface LauncherAdvancedOverrides {
    "serverExecutablePath"?: string;
    "configPath"?: string;
    "workdir"?: string;
}

export enum LauncherCloseAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CloseActionHide = "hide",
    CloseActionExit = "exit",
    CloseActionCancel = "cancel",
};

export enum LauncherCloseBehavior {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CloseAskEveryTime = "ask_every_time",
    CloseHideToTray = "hide_to_tray",
    CloseExitApplication = "exit_application",
};

export interface LauncherCloseConfirmResponse {
    "action": LauncherCloseAction;
    "setAsDefault": boolean;
}

export interface LauncherLocalSnapshot {
    "processId": number | null;
    "processLifecycle": LauncherProcessLifecycle;
    "processOwnership": LauncherProcessOwnership;
    "environmentChecks": EnvironmentCheckResult[] | null;
    "preflightChecks": EnvironmentCheckResult[] | null;
    "advisoryChecks": EnvironmentCheckResult[] | null;
    "recentStderr": string[] | null;
    "runtimePrepare": RuntimePrepareSnapshot | null;
    "releaseCheck": ReleaseCheckSnapshot;
    "lastLocalError": string;
    "statusHint": string;
    "settings": LauncherSettings;
    "resolvedSettings": LauncherResolvedSettings;
    "endpoint": ServerEndpoint;
}

export enum LauncherProcessLifecycle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Stopped = "stopped",
    Starting = "starting",
    Running = "running",
    Stopping = "stopping",
};

export enum LauncherProcessOwnership {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OwnershipNone = "none",
    OwnershipLauncher = "launcher_managed",
    OwnershipExternal = "external",
};

export interface LauncherResolvedSettings {
    "installationRoot": string;
    "serverExecutablePath": string;
    "configPath": string;
    "workdir": string;
}

export interface LauncherServerSnapshot {
    "health": ServerLivenessStatusResponse | null;
    "readiness": ServerReadinessStatusResponse | null;
    "systemStatus": ServerSystemStatusResponse | null;
}

export interface LauncherSettings {
    "installationRoot": string;
    "closeBehavior": LauncherCloseBehavior;
    "advancedOverrides"?: LauncherAdvancedOverrides | null;
}

export interface LauncherSnapshot {
    "server": LauncherServerSnapshot;
    "launcher": LauncherLocalSnapshot;
}

export interface ReleaseCheckSnapshot {
    "status": ReleaseCheckStatus;
    "currentVersion": string;
    "latestVersion": string;
    "summary": string;
    "detail": string;
    "errorCode": string;
    "releasePageUrl": string;
    "updateAvailable": boolean;
    "canCheck": boolean;
}

export enum ReleaseCheckStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReleaseDisabled = "disabled",
    ReleaseIdle = "idle",
    ReleaseChecking = "checking",
    ReleaseUpdating = "updating",
    ReleaseUpToDate = "up_to_date",
    ReleaseUpdateAvailable = "update_available",
    ReleaseFailed = "failed",
};

export interface RuntimePrepareResourceProgress {
    "kind": string;
    "label": string;
    "resourceId": string;
    "version": string;
    "sourceLabel": string;
    "sourceUrl": string;
    "archivePath": string;
    "storeRoot": string;
    "stage": string;
    "status": RuntimePrepareStatus;
    "progress": number | null;
    "downloadedBytes": number | null;
    "totalBytes": number | null;
    "extractedEntries": number | null;
    "totalEntries": number | null;
    "summary": string;
    "error": string;
    "updatedAt": string;
}

export interface RuntimePrepareSnapshot {
    "active": boolean;
    "currentKind": string;
    "summary": string;
    "resources": RuntimePrepareResourceProgress[] | null;
}

export enum RuntimePrepareStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PreparePending = "pending",
    PrepareRunning = "running",
    PrepareSucceeded = "succeeded",
    PrepareFailed = "failed",
};

export type ServerAdapterProtocol = string;

export type ServerAdapterState = string;

export interface ServerAdapterStatus {
    "id": string;
    "protocol": ServerAdapterProtocol;
    "enabled": boolean;
    "state": ServerAdapterState;
}

export interface ServerDiagnosticIssue {
    "code": string;
    "severity": string;
    "summary": string;
    "user_message"?: string;
    "remediation"?: string;
    "internal_reason"?: string;
    "runtime_resources"?: string[] | null;
}

export interface ServerEndpoint {
    "host": string;
    "port": number;
    "baseUrl": string;
}

export interface ServerLivenessStatusResponse {
    "status": string;
}

export interface ServerReadinessStatusResponse {
    "status": string;
    "reason"?: string;
    "reason_codes"?: string[] | null;
    "checks"?: ServerReadinessStatusResponseChecks | null;
    "issues"?: ServerDiagnosticIssue[] | null;
}

export interface ServerReadinessStatusResponseChecks {
    "config"?: string;
    "database"?: string;
    "runtime"?: string;
    "render"?: string;
}

export interface ServerSystemStatusResponse {
    "status": string;
    "adapters": ServerAdapterStatus[] | null;
    "active_plugins"?: number;
    "running_plugins"?: number;
    "failed_plugins"?: number;
    "db_schema_version"?: string;
    "uptime_seconds"?: number;
    "health"?: ServerReadinessStatusResponse | null;
}
