// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.CheckForUpdates");
}

export function ChooseConfigFile(): $CancellablePromise<string | null> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.ChooseConfigFile");
}

export function ChooseInstallationRoot(): $CancellablePromise<string | null> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.ChooseInstallationRoot");
}

export function ChooseServerExecutable(): $CancellablePromise<string | null> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.ChooseServerExecutable");
}

export function ChooseWorkdir(): $CancellablePromise<string | null> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.ChooseWorkdir");
}

export function Close(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.Close");
}

export function CloseConfirmResponse(response: $models.LauncherCloseConfirmResponse): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.CloseConfirmResponse", response);
}

export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.DownloadUpdate");
}

export function ExitApplication(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.ExitApplication");
}

export function ExternalStopConfirmResponse(confirmed: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.ExternalStopConfirmResponse", confirmed);
}

export function GetPlatform(): $CancellablePromise<string> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.GetPlatform");
}

export function GetSnapshot(): $CancellablePromise<$models.LauncherSnapshot> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.GetSnapshot");
}

export function HasPendingCloseConfirm(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.HasPendingCloseConfirm");
}

export function HasPendingExternalStopConfirm(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.HasPendingExternalStopConfirm");
}

export function Initialize(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.Initialize");
}

export function InstallDownloadedUpdate(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.InstallDownloadedUpdate");
}

export function IsMaximized(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.IsMaximized");
}

export function Maximize(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.Maximize");
}

export function Minimize(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.Minimize");
}

export function OpenLogsDirectory(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.OpenLogsDirectory");
}

export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.OpenReleasePage");
}

export function OpenRepositoryPage(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.OpenRepositoryPage");
}

export function OpenWebUI(targetPath: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.OpenWebUI", targetPath);
}

export function PreviewResolvedSettings(settings: $models.LauncherSettings): $CancellablePromise<$models.LauncherResolvedSettings> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.PreviewResolvedSettings", settings);
}

export function Refresh(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.Refresh");
}

export function ResetAdmin(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.ResetAdmin");
}

export function SaveSettings(settings: $models.LauncherSettings): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.SaveSettings", settings);
}

export function SetThemeMode(mode: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.SetThemeMode", mode);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.Start");
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByName("github.com/RayleaBot/RayleaBot/launcher/internal/desktop.Service.Stop");
}
