import importlib.util
import json
from pathlib import Path
import shutil
import sys
import tempfile
import unittest

import yaml

SCRIPTS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPTS))
spec = importlib.util.spec_from_file_location('launcher_generator', SCRIPTS / 'generate-launcher-api.py')
generator = importlib.util.module_from_spec(spec)
spec.loader.exec_module(generator)
from generated_outputs import sync_outputs


class LauncherGenerationTests(unittest.TestCase):
    def test_recursive_closure_determinism_and_drift(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / 'contracts').mkdir()
            source = root / 'contracts/web-api.openapi.yaml'
            shutil.copyfile(SCRIPTS.parent / 'contracts/web-api.openapi.yaml', source)
            first = generator.generate(root)
            self.assertEqual(first, generator.generate(root))
            output = root / 'launcher/api-subset.generated.json'
            closure = json.loads(first[output])['components']['schemas']
            self.assertIn('RecoveryCompatibilityAuditItem', closure)
            self.assertNotIn('PluginStoreDetailResponse', closure)
            marker = b'Code generated by scripts/generate-launcher-api.py'
            self.assertTrue(sync_outputs(root, first, marker, True))
            sync_outputs(root, first, marker, False)
            self.assertEqual(sync_outputs(root, first, marker, True), [])
            extra = output.with_name('old-api.generated.json')
            extra.write_bytes(first[output])
            self.assertIn(extra.relative_to(root).as_posix(), sync_outputs(root, first, marker, True))
            sync_outputs(root, first, marker, False)
            self.assertFalse(extra.exists())
            document = yaml.safe_load(source.read_text(encoding='utf-8'))
            document['components']['schemas']['DiagnosticIssue']['properties']['new_field'] = {'type': 'integer'}
            source.write_text(yaml.safe_dump(document), encoding='utf-8')
            changed = generator.generate(root)
            self.assertTrue(all(first[path] != payload for path, payload in changed.items()))
            self.assertIn(b'NewField', changed[root / 'launcher/internal/desktop/server_models.generated.go'])


if __name__ == '__main__':
    unittest.main()
