import importlib.util
import json
from pathlib import Path
import shutil
import sys
import tempfile
import unittest
from unittest.mock import patch

SCRIPTS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPTS))
from generated_outputs import sync_outputs


def load_generator(name):
    spec = importlib.util.spec_from_file_location(name, SCRIPTS / (name + '.py'))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class GenerationTests(unittest.TestCase):
    def test_wire_determinism_and_contract_propagation(self):
        generator = load_generator('generate-plugin-wire')
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            for directory in ['contracts', 'fixtures/plugin-protocol', 'scripts/templates', 'scripts/testdata']:
                shutil.copytree(SCRIPTS.parent / directory, root / directory)
            with patch.object(generator, 'ROOT', root):
                first = generator.generate()
                self.assertEqual(first, generator.generate())
                server = root / 'server/internal/pluginwire/protocol.generated.go'
                sdk = root / 'sdk/go/internal/pluginwire/protocol.generated.go'
                self.assertEqual(first[server], first[sdk])
                source = root / 'contracts/plugin-protocol.schema.json'
                schema = json.loads(source.read_text(encoding='utf-8'))
                schema['$defs']['init']['allOf'][1]['properties']['protocol_version']['const'] = '99'
                schema['$defs']['onebot_action_kind']['enum'].append('fixture.action')
                schema['$defs']['provider_extension_action_kind']['enum'].append('provider.fixture.action')
                source.write_text(json.dumps(schema), encoding='utf-8')
                changed = generator.generate()
                action_kinds = root / 'server/internal/pluginwire/action_kinds.generated.go'
                self.assertNotEqual(first[action_kinds], changed[action_kinds])
                self.assertIn(b'"fixture.action"', changed[action_kinds])
                self.assertIn(b'"provider.fixture.action"', changed[action_kinds])
                for output in [server, sdk, root / 'server/internal/contractversions/versions.generated.go', root / 'launcher/internal/contractversions/versions.generated.go']:
                    self.assertNotEqual(first[output], changed[output])
                    self.assertIn(b'"99"', changed[output])
                release_source = root / 'contracts/release-manifest.schema.json'
                release_schema = json.loads(release_source.read_text(encoding='utf-8'))
                release_schema['$defs']['artifactId']['enum'].append('fixture-x64-full')
                release_source.write_text(json.dumps(release_schema), encoding='utf-8')
                artifact_change = generator.generate()
                for name in ['server/internal/releaseupdate/artifacts.generated.go', 'launcher/internal/desktop/artifacts.generated.go', 'scripts/artifact_ids_generated.py']:
                    self.assertNotEqual(changed[root / name], artifact_change[root / name])
                    self.assertIn(b'"fixture-x64-full"', artifact_change[root / name])

    def test_generate_and_verify_detect_missing_changed_and_extra_outputs(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            path = root / 'models.generated.go'
            marker = b'Code generated by fixture'
            outputs = {path: marker + b'\nconst Version = 1\n'}
            self.assertEqual(sync_outputs(root, outputs, marker, True), [path.name])
            self.assertEqual(sync_outputs(root, outputs, marker, False), [])
            self.assertEqual(sync_outputs(root, outputs, marker, True), [])
            path.write_bytes(b'changed')
            self.assertEqual(sync_outputs(root, outputs, marker, True), [path.name])
            stale = root / 'old.generated.go'
            stale.write_bytes(marker)
            manual = root / 'manual.go'
            manual.write_bytes(b'package fixture')
            self.assertEqual(sync_outputs(root, outputs, marker, True), [path.name, stale.name])
            sync_outputs(root, outputs, marker, False)
            self.assertFalse(stale.exists())
            self.assertTrue(manual.exists())
            path.unlink()
            self.assertEqual(sync_outputs(root, outputs, marker, True), [path.name])

    def test_stale_raw_schema_and_vector_detection(self):
        generator = load_generator('generate-plugin-wire')
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            extra = [root / 'server/internal/pluginwire/old.schema.json', root / 'sdk/go/testdata/old.generated.json']
            for path in extra:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text('{}', encoding='utf-8')
            with patch.object(generator, 'ROOT', root):
                self.assertEqual(generator.sync_owned_data({}, True), sorted(path.relative_to(root).as_posix() for path in extra))
                self.assertTrue(all(path.exists() for path in extra))
                self.assertEqual(generator.sync_owned_data({}, False), [])
                self.assertTrue(all(not path.exists() for path in extra))

    def test_error_catalog_determinism(self):
        import yaml
        generator = load_generator('generate-error-codes')
        document = yaml.safe_load((SCRIPTS.parent / 'contracts/error-codes.yaml').read_text(encoding='utf-8'))
        first = generator.generate(document['codes'], document.get('diagnostics', {}))
        self.assertEqual(first, generator.generate(document['codes'], document.get('diagnostics', {})))


if __name__ == '__main__':
    unittest.main()
