PLATFORM = {
    "id": "bilibili",
    "name": "Bilibili",
    "subject_label": "UID",
    "subscribe_usage": "用法：/订阅b站推送 [直播|视频|图文|文章|转发] UID或昵称；类型可选，不填表示全部类型。",
    "unsubscribe_usage": "用法：/取消b站推送 [直播|视频|图文|文章|转发] UID或昵称；类型可选，不填表示全部类型。",
    "search_usage": "用法：/b站搜索up UP昵称关键词",
    "services": {
        "all": "全部",
        "live": "直播",
        "video": "视频",
        "image_text": "图文",
        "article": "文章",
        "repost": "转发",
    },
    "service_aliases": {
        "全部": "all",
        "全量": "all",
        "所有": "all",
        "直播": "live",
        "视频": "video",
        "图文": "image_text",
        "动态": "image_text",
        "文章": "article",
        "专栏": "article",
        "转发": "repost",
        "live": "live",
        "video": "video",
        "image_text": "image_text",
        "article": "article",
        "repost": "repost",
        "all": "all",
    },
}
