import { expect, test } from './real-server.fixture'

test('password update verifies the current password and supports an optional new username', async ({ page, request, server, baseURL }) => {
  const setup = await request.post('/api/setup/admin', {
    headers: { Origin: baseURL!, 'X-Raylea-Setup-Token': server.setupToken, 'X-Raylea-Session-Transport': 'bearer' },
    data: { identifier: 'admin', secret: 'fixture-only-secret' },
  })
  expect(setup.status()).toBe(200)
  await page.goto('/login')
  await page.getByLabel('管理员密钥').fill('fixture-only-secret')
  await page.getByRole('button', { name: /登\s*录/ }).click()
  await expect(page.getByRole('heading', { name: '系统状态', level: 1 })).toBeVisible()
  await page.getByTestId('sidebar-account').click()
  await page.getByRole('menuitem', { name: '修改账户', exact: true }).click()
  const dialog = page.getByTestId('account-credentials-dialog')
  await dialog.getByLabel('当前密码', { exact: true }).fill('incorrect-current-secret')
  await dialog.getByLabel('新密码', { exact: true }).fill('fixture-next-secret')
  await dialog.getByLabel('确认新密码', { exact: true }).fill('does-not-match')
  await dialog.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(dialog.getByLabel('确认新密码', { exact: true })).toBeFocused()
  await expect(dialog.getByRole('alert')).toContainText('两次输入')
  await dialog.getByLabel('确认新密码', { exact: true }).fill('fixture-next-secret')
  await dialog.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('当前密码不正确')
  await expect(dialog.getByLabel('当前密码', { exact: true })).toBeFocused()
  await dialog.getByLabel('当前密码', { exact: true }).fill('fixture-only-secret')
  await dialog.getByRole('button', { name: '同时修改用户名' }).click()
  await dialog.getByLabel('新用户名（可选）', { exact: true }).fill('renamed-admin')
  const saved = page.waitForResponse(response => response.url().endsWith('/api/account/credentials') && response.status() === 204)
  await dialog.getByRole('button', { name: '保存修改', exact: true }).click()
  const outgoing = (await saved).request()
  expect(outgoing.headers()['x-raylea-csrf']).toBeTruthy()
  expect(outgoing.postDataJSON()).toEqual({ current_secret: 'fixture-only-secret', new_secret: 'fixture-next-secret', new_identifier: 'renamed-admin' })
  await expect(page).toHaveURL(/\/login(?:\?|$)/)
  await expect(page.getByText('账户已更新，请使用新凭据重新登录。', { exact: true }).first()).toBeVisible()
  await page.getByLabel('管理员账号').fill('renamed-admin')
  await page.getByLabel('管理员密钥').fill('fixture-next-secret')
  await page.getByRole('button', { name: /登\s*录/ }).click()
  await expect(page.getByRole('heading', { name: '系统状态', level: 1 })).toBeVisible()
})
