// Generated by scripts/generate-design-tokens.mjs from design/tokens.json. Do not edit.

export interface GeneratedLauncherThemeTokens {
  attention: string;
  attentionSoft: string;
  authCanvasFocus: string;
  authCanvasWash: string;
  authControl: string;
  authControlHover: string;
  authParticle: string;
  authParticleLine: string;
  border: string;
  borderControl: string;
  brandFill: string;
  brandFillHover: string;
  brandFillPressed: string;
  brandForeground: string;
  brandSoft: string;
  canvas: string;
  chrome: string;
  chromeMuted: string;
  chromeText: string;
  danger: string;
  dangerSoft: string;
  focus: string;
  navHover: string;
  navSelected: string;
  navSelectedText: string;
  onAttention: string;
  onBrand: string;
  shadowFloating: string;
  shadowSurface: string;
  success: string;
  successSoft: string;
  surface: string;
  surfaceRaised: string;
  surfaceSoft: string;
  text: string;
  textMuted: string;
  warning: string;
  warningSoft: string;
}

export const launcherGeneratedThemes: Record<'light' | 'dark', GeneratedLauncherThemeTokens> = {
  light: {
    attention: "#9B4A2F",
    attentionSoft: "#F9ECE6",
    border: "#DDD4D9",
    borderControl: "#93868E",
    brandFill: "#8A285D",
    brandForeground: "#8A285D",
    brandSoft: "#F7E9F1",
    canvas: "#F6F3F5",
    chrome: "#3F1830",
    chromeMuted: "#E8AAC7",
    chromeText: "#FFF4F9",
    danger: "#B9384E",
    dangerSoft: "#FBE9EC",
    focus: "#9F356C",
    onAttention: "#FFFFFF",
    onBrand: "#FFFFFF",
    success: "#227653",
    successSoft: "#E8F4EE",
    surface: "#FFFBFD",
    surfaceRaised: "#FFFFFF",
    surfaceSoft: "#F0EAED",
    text: "#211820",
    textMuted: "#6B5E66",
    warning: "#8A5600",
    warningSoft: "#FBF0DC",
    brandFillHover: "#6C204B",
    brandFillPressed: "#3F1830",
    navHover: "#27101E",
    navSelected: "#6C204B",
    navSelectedText: "#FFF4F9",
    authCanvasFocus: "#BF4F8724",
    authCanvasWash: "#8A285D12",
    authControl: "#FFF9FC",
    authControlHover: "#FFF4F9",
    authParticle: "#8A285DA8",
    authParticleLine: "#8A285D2B",
    shadowSurface: "0 2px 8px #21182014",
    shadowFloating: "0 18px 48px #21182029",
  },
  dark: {
    attention: "#E08A61",
    attentionSoft: "#3B261E",
    border: "#41363D",
    borderControl: "#806C78",
    brandFill: "#D57BA6",
    brandForeground: "#F0A4C9",
    brandSoft: "#3A2030",
    canvas: "#151114",
    chrome: "#24151F",
    chromeMuted: "#E8AAC7",
    chromeText: "#FFF4F9",
    danger: "#FF8494",
    dangerSoft: "#402026",
    focus: "#F0A4C9",
    onAttention: "#27101E",
    onBrand: "#27101E",
    success: "#65D39A",
    successSoft: "#193429",
    surface: "#1D181C",
    surfaceRaised: "#282127",
    surfaceSoft: "#211B20",
    text: "#F4EDF1",
    textMuted: "#BAADB4",
    warning: "#F0BB5A",
    warningSoft: "#3B2D16",
    brandFillHover: "#E8AAC7",
    brandFillPressed: "#BF4F87",
    navHover: "#27101E",
    navSelected: "#3F1830",
    navSelectedText: "#FFF4F9",
    authCanvasFocus: "#F0A4C91F",
    authCanvasWash: "#D57BA60F",
    authControl: "#211B20",
    authControlHover: "#282127",
    authParticle: "#F0A4C9C7",
    authParticleLine: "#F0A4C938",
    shadowSurface: "0 2px 10px #00000047",
    shadowFloating: "0 20px 56px #00000070",
  },
};
