/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LivenessStatusResponse: {
            /** @constant */
            status: "ok";
        };
        ReadinessStatusResponse: {
            /** @enum {string} */
            status: "ready" | "degraded" | "setup_required" | "failed";
            reason?: string;
            reason_codes?: string[];
            checks?: {
                config?: string;
                database?: string;
                runtime?: string;
                render?: string;
            };
            issues?: components["schemas"]["DiagnosticIssue"][];
        };
        DiagnosticIssue: {
            code: string;
            /** @enum {string} */
            severity: "ok" | "warning" | "error";
            summary: string;
            user_message?: string;
            remediation?: string;
            internal_reason?: string;
            /** @description 可通过运行环境准备任务处理的资源；省略时客户端不推断准备目标。 */
            runtime_resources?: ("chromium" | "ffmpeg")[];
        };
        SystemStatusResponse: {
            /** @enum {string} */
            status: "running" | "shutting_down";
            /** @description 按配置顺序返回实例状态；无实例时为 []，不构造占位连接。 */
            adapters: components["schemas"]["AdapterStatus"][];
            /** @description Number of plugin runtimes currently active. */
            active_plugins?: number;
            /** @description Number of plugins currently in the running state. */
            running_plugins?: number;
            /** @description Number of plugins currently in the failed state. */
            failed_plugins?: number;
            /** @description Current database schema migration version. */
            db_schema_version?: string;
            uptime_seconds?: number;
            health?: components["schemas"]["ReadinessStatusResponse"];
        };
        AdapterStatus: {
            id: string;
            protocol: components["schemas"]["AdapterProtocol"];
            enabled: boolean;
            state: components["schemas"]["AdapterState"];
        };
        /**
         * @description 正式支持的聊天适配器标识。集合随正式接入的适配器增长；管理面按此值区分协议， 不从会话种类或标识符格式推断来源。
         * @enum {string}
         */
        AdapterProtocol: "onebot11" | "qqofficial";
        /**
         * @description 适配器连接状态，与聊天传输状态共用词表。
         * @enum {string}
         */
        AdapterState: "idle" | "listening" | "connecting" | "connected" | "auth_failed" | "reconnecting" | "stopped";
        SystemShutdownResponse: {
            accepted: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
