// Package pluginwiregen projects the formal plugin contracts into Go models.
package pluginwiregen

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"sort"
	"strings"

	"github.com/RayleaBot/RayleaBot/tools/internal/cli"
	"github.com/RayleaBot/RayleaBot/tools/internal/generated"
	d "github.com/RayleaBot/RayleaBot/tools/internal/ordered"
	"github.com/RayleaBot/RayleaBot/tools/internal/repo"
)

// The marker names this generator and identifies the files it owns.
const marker = "Code generated by tools/cmd/generate-plugin-wire"
const header = "// " + marker + " from contracts; DO NOT EDIT.\n"

var dataDirs = []string{"server/internal/plugins/pluginwire", "sdk/go/internal/pluginwire", "server/internal/plugins/pluginwire/testdata", "server/internal/platform/redact/testdata", "sdk/go/testdata"}

func kind(n *d.Object) string {
	if a, ok := n.Get("type").([]any); ok {
		var nonnull []string
		for _, v := range a {
			if v != "null" {
				nonnull = append(nonnull, d.Str(v))
			}
		}
		if len(nonnull) == 1 {
			return nonnull[0]
		}
		return "any"
	}
	if v := d.Str(n.Get("type")); v != "" {
		return v
	}
	if n.Has("properties") {
		return "object"
	}
	if a := d.List(n.Get("enum")); len(a) > 0 {
		all := true
		for _, v := range a {
			if _, ok := v.(string); !ok {
				all = false
			}
		}
		if all {
			return "string"
		}
	}
	if n.Has("const") {
		switch n.Get("const").(type) {
		case bool:
			return "boolean"
		case int, int64, uint64:
			return "integer"
		default:
			return "string"
		}
	}
	return "any"
}
func union(a, b []string) []string {
	r := append(append([]string{}, a...), b...)
	sort.Strings(r)
	return slices.Compact(r)
}
func stringsAny(a []string) []any {
	r := make([]any, len(a))
	for i, v := range a {
		r[i] = v
	}
	return r
}
func shape(value any, root *d.Object) (*d.Object, error) {
	n := d.Obj(value).Copy()
	if ref := d.Str(n.Get("$ref")); ref != "" {
		if !strings.HasPrefix(ref, "#/") {
			return nil, fmt.Errorf("wire generator accepts only local schema references")
		}
		v, e := d.At(root, ref[1:])
		if e != nil {
			return nil, e
		}
		base := d.Obj(v).Copy()
		for _, f := range *n {
			if f.Name != "$ref" {
				base.Set(f.Name, f.Value)
			}
		}
		n = base
	}
	r := &d.Object{}
	for _, f := range *n {
		if f.Name != "allOf" && f.Name != "oneOf" && f.Name != "anyOf" {
			r.Set(f.Name, f.Value)
		}
	}
	for _, v := range d.List(n.Get("allOf")) {
		part, e := shape(v, root)
		if e != nil {
			return nil, e
		}
		if part.Has("properties") {
			p := d.Obj(r.Get("properties")).Copy()
			for _, f := range *d.Obj(part.Get("properties")) {
				p.Set(f.Name, f.Value)
			}
			r.Set("properties", p)
		}
		if part.Has("required") {
			r.Set("required", stringsAny(union(d.Strings(r.Get("required")), d.Strings(part.Get("required")))))
		}
		if part.Has("type") {
			r.Set("type", part.Get("type"))
		} else if kind(part) != "any" && !r.Has("type") {
			r.Set("type", kind(part))
		}
	}
	alternatives := d.List(n.Get("oneOf"))
	if !n.Has("oneOf") {
		alternatives = d.List(n.Get("anyOf"))
	}
	if len(alternatives) > 0 {
		parts := []*d.Object{}
		objects := true
		kinds := map[string]bool{}
		for _, v := range alternatives {
			p, e := shape(v, root)
			if e != nil {
				return nil, e
			}
			parts = append(parts, p)
			objects = objects && (p.Has("properties") || p.Get("type") == "object")
			if kind(p) != "null" {
				kinds[kind(p)] = true
			}
		}
		if objects {
			fields := &d.Object{}
			required := d.Strings(parts[0].Get("required"))
			for _, p := range parts {
				for _, f := range *d.Obj(p.Get("properties")) {
					v := f.Value
					if fields.Has(f.Name) && !reflect.DeepEqual(fields.Get(f.Name), v) {
						v = &d.Object{{Name: "anyOf", Value: []any{fields.Get(f.Name), v}}}
					}
					fields.Set(f.Name, v)
				}
				required = slices.DeleteFunc(required, func(s string) bool { return !slices.Contains(d.Strings(p.Get("required")), s) })
			}
			base := d.Obj(r.Get("properties")).Copy()
			for _, f := range *fields {
				v := f.Value
				if base.Has(f.Name) {
					v = &d.Object{{Name: "allOf", Value: []any{base.Get(f.Name), v}}}
				}
				base.Set(f.Name, v)
			}
			r.Set("type", "object")
			r.Set("properties", base)
			r.Set("required", stringsAny(union(d.Strings(r.Get("required")), required)))
		} else if len(kinds) == 1 {
			for k := range kinds {
				r.Set("type", k)
			}
		}
	}
	return r, nil
}
func goName(name string) string {
	special := map[string]string{"id": "ID", "ids": "IDs", "url": "URL", "urls": "URLs", "http": "HTTP", "kv": "KV", "qq": "QQ", "openid": "OpenID", "onebot": "OneBot"}
	var b strings.Builder
	for _, p := range strings.Split(name, "_") {
		if v := special[p]; v != "" {
			b.WriteString(v)
		} else if p != "" {
			b.WriteString(strings.ToUpper(p[:1]) + strings.ToLower(p[1:]))
		}
	}
	return b.String()
}

type modelGenerator struct {
	schema *d.Object
	named  map[*d.Object]string
}

func (g modelGenerator) fieldType(model, name string, node any, required bool) (string, error) {
	if model == "ProtocolEventFrame" && name == "raw_payload" {
		return "any", nil
	}
	if rawFields[model+":"+name] {
		return "json.RawMessage", nil
	}
	if model == "ProtocolActionConfigWriteFrame" && name == "values" {
		return "map[string]json.RawMessage", nil
	}
	if name == "scope" && strings.HasPrefix(model, "ProtocolActionGovernance") {
		return "GovernanceScope", nil
	}
	if (model == "ProtocolMessageFrame" || model == "ProtocolOutboundMessageFrame") && name == "segments" {
		return "[]ProtocolSegmentFrame", nil
	}
	resolved := node
	if ref := d.Str(d.Obj(node).Get("$ref")); ref != "" {
		var e error
		resolved, e = d.At(g.schema, strings.TrimPrefix(ref, "#"))
		if e != nil {
			return "", e
		}
	}
	named := g.named[d.Obj(resolved)]
	expanded, e := shape(node, g.schema)
	if e != nil {
		return "", e
	}
	category := kind(expanded)
	var result string
	if named != "" && named != model && category == "object" {
		result = named
		if !required {
			result = "*" + result
		}
	} else {
		switch category {
		case "string":
			result = "string"
		case "integer":
			result = "int"
			if slices.Contains([]string{"timestamp", "time", "received_at", "expires_at_ms", "deadline_at_ms"}, name) {
				result = "int64"
			}
		case "number":
			result = "float64"
		case "boolean":
			result = "bool"
		case "array":
			v, err := g.fieldType(model, name+"_item", expanded.Get("items"), true)
			if err != nil {
				return "", err
			}
			result = "[]" + v
		case "object":
			v := "any"
			if a, ok := expanded.Get("additionalProperties").(*d.Object); ok {
				v, e = g.fieldType(model, name+"_value", a, true)
				if e != nil {
					return "", e
				}
			}
			result = "map[string]" + v
		default:
			result = "any"
		}
	}
	if presenceFields[model+":"+name] && !strings.HasPrefix(result, "*") {
		result = "*" + result
	}
	return result, nil
}
func quote(v any) string { b, _ := d.JSON(v, false); return strings.TrimSpace(string(b)) }
func (g modelGenerator) render() (string, error) {
	var b strings.Builder
	b.WriteString(header + "\npackage pluginwire\n\nimport \"encoding/json\"\n\n")
	shapes := map[string]*d.Object{}
	field := func(name, typ, suffix string) { fmt.Fprintf(&b, "%s %s `json:%q`\n", goName(name), typ, name+suffix) }
	for _, m := range models {
		v, e := d.At(g.schema, m[1])
		if e != nil {
			return "", e
		}
		n, e := shape(v, g.schema)
		if e != nil {
			return "", e
		}
		props := d.Obj(n.Get("properties"))
		if len(*props) == 0 {
			return "", fmt.Errorf("%s: expected a named object projection", m[1])
		}
		shapes[m[0]] = n
		fmt.Fprintf(&b, "type %s struct {\n", m[0])
		for _, f := range *props {
			required := slices.Contains(d.Strings(n.Get("required")), f.Name)
			typ, e := g.fieldType(m[0], f.Name, f.Value, required)
			if e != nil {
				return "", e
			}
			suffix := ",omitempty"
			if required {
				suffix = ""
			}
			field(f.Name, typ, suffix)
		}
		b.WriteString("}\n\n")
	}
	type frameField struct {
		name, model string
		schema      any
		typ         string
	}
	var fields []frameField
	requiredByType := &d.Object{}
	for _, variant := range []string{"InitFrame", "InitProgressFrame", "InitAckFrame", "EventFrame", "ActionFrame", "ResultFrame", "ErrorFrame", "PingFrame", "PongFrame", "ShutdownFrame"} {
		n := shapes[variant]
		p := d.Obj(n.Get("properties"))
		t, e := shape(p.Get("type"), g.schema)
		if e != nil {
			return "", e
		}
		discriminator := d.Str(t.Get("const"))
		if discriminator == "" {
			discriminator = "action"
		}
		requiredByType.Set(discriminator, n.Get("required"))
		for _, f := range *p {
			if slices.ContainsFunc(fields, func(v frameField) bool { return v.name == f.Name }) {
				continue
			}
			typ := "json.RawMessage"
			if f.Name != "event" && f.Name != "data" {
				typ, e = g.fieldType(variant, f.Name, f.Value, true)
				if e != nil {
					return "", e
				}
			}
			if f.Name == "bots" {
				typ = "*[]BotIdentity"
			}
			fields = append(fields, frameField{f.Name, variant, f.Value, typ})
		}
	}
	b.WriteString("type Frame struct {\n")
	for _, f := range fields {
		suffix := ",omitempty"
		if f.name == "type" || f.name == "request_id" {
			suffix = ""
		}
		field(f.name, f.typ, suffix)
	}
	b.WriteString("}\n\n// MarshalJSON keeps all supplied fields and includes the selected frame's\n// required fields even when they have zero, empty or null values.\nfunc (frame Frame) MarshalJSON() ([]byte, error) {\ntype plain Frame\nswitch frame.Type {\n")
	for _, r := range *requiredByType {
		required := d.Strings(r.Value)
		if !slices.ContainsFunc(required, func(v string) bool { return v != "type" && v != "request_id" }) {
			continue
		}
		fmt.Fprintf(&b, "case %q:\n", r.Name)
		for _, name := range required {
			for _, f := range fields {
				if f.name == name && f.typ == "json.RawMessage" {
					fmt.Fprintf(&b, "if frame.%s != nil && len(frame.%s) == 0 {\n// Empty raw fields were omitted before required-field encoding.\n// Preserve earlier field errors and marshal custom values only once.\nif _, err := json.Marshal(plain(frame)); err != nil { return nil, err }\nreturn json.Marshal(frame.%s)\n}\n", goName(name), goName(name), goName(name))
				}
			}
		}
		b.WriteString("type projection struct {\n")
		for _, f := range fields {
			suffix := ",omitempty"
			if slices.Contains(required, f.name) || f.name == "type" || f.name == "request_id" {
				suffix = ""
			}
			field(f.name, f.typ, suffix)
		}
		b.WriteString("}\nreturn json.Marshal(projection(frame))\n")
	}
	b.WriteString("default:\nreturn json.Marshal(plain(frame))\n}\n}\n")
	return b.String(), nil
}

func Generate(root string) (map[string][]byte, error) {
	read := func(name string) (*d.Object, error) { return d.Read(filepath.Join(root, "contracts", name)) }
	schema, e := read("plugin-protocol.schema.json")
	if e != nil {
		return nil, e
	}
	config, e := read("config.user.schema.json")
	if e != nil {
		return nil, e
	}
	g := modelGenerator{schema, map[*d.Object]string{}}
	for _, m := range models {
		v, e := d.At(schema, m[1])
		if e != nil {
			return nil, e
		}
		g.named[d.Obj(v)] = m[0]
	}
	source, e := g.render()
	if e != nil {
		return nil, e
	}
	version, e := d.At(schema, "/$defs/init/allOf/1/properties/protocol_version/const")
	if e != nil {
		return nil, e
	}
	limit, e := d.At(config, "/properties/runtime/properties/ipc_message_max_bytes/default")
	if e != nil {
		return nil, e
	}
	source += fmt.Sprintf("\nconst ProtocolVersion = %s\nconst DefaultMaxFrameBytes = %s\n", quote(version), quote(limit))
	outputs := map[string][]byte{}
	putGo := func(path, source string) error {
		b, e := format.Source([]byte(source))
		if e == nil {
			outputs[path] = b
		}
		return e
	}
	wire := "server/internal/plugins/pluginwire/"
	for _, p := range []string{wire + "protocol.generated.go", "sdk/go/internal/pluginwire/protocol.generated.go"} {
		if e = putGo(p, source); e != nil {
			return nil, e
		}
	}
	for _, v := range [][2]string{{wire + "codec.generated.go", header + codecSource}, {wire + "codec.generated_test.go", header + testSource}} {
		if e = putGo(v[0], v[1]); e != nil {
			return nil, e
		}
	}
	raw, e := os.ReadFile(filepath.Join(root, "contracts/plugin-protocol.schema.json"))
	if e != nil {
		return nil, e
	}
	outputs[wire+"protocol.schema.json"] = bytes.ReplaceAll(raw, []byte("\r\n"), []byte("\n"))
	actions := header + "\npackage pluginwire\n"
	for _, v := range [][2]string{{"IsOneBotAction", "onebot_action_kind"}, {"IsProviderExtensionAction", "provider_extension_action_kind"}} {
		values, e := d.At(schema, "/$defs/"+v[1]+"/enum")
		if e != nil {
			return nil, e
		}
		var cases []string
		for _, v := range d.List(values) {
			cases = append(cases, quote(v))
		}
		actions += fmt.Sprintf("\nfunc %s(kind string) bool {\nswitch kind {\ncase %s:\nreturn true\ndefault:\nreturn false\n}\n}\n", v[0], strings.Join(cases, ", "))
	}
	if e = putGo(wire+"action_kinds.generated.go", actions); e != nil {
		return nil, e
	}
	paths, e := filepath.Glob(filepath.Join(root, "fixtures/plugin-protocol/*.yaml"))
	if e != nil {
		return nil, e
	}
	vectors := []any{}
	for _, p := range paths {
		f, e := d.Read(p)
		if e != nil {
			return nil, e
		}
		vectors = append(vectors, &d.Object{{Name: "name", Value: filepath.Base(p)}, {Name: "valid", Value: d.Obj(f.Get("expect")).Get("valid")}, {Name: "frames", Value: f.Get("frames")}})
	}
	outputs[wire+"testdata/frames.generated.json"], e = d.JSON(vectors, true)
	if e != nil {
		return nil, e
	}
	versions := &d.Object{}
	for _, v := range [][3]string{{"PluginProtocolVersion", "plugin-protocol.schema.json", "/$defs/init/allOf/1/properties/protocol_version/const"}, {"PluginManifestVersion", "plugin-info.schema.json", "/properties/manifest_version/const"}, {"PluginArtifactVersion", "plugin-artifact.schema.json", "/properties/artifact_version/const"}, {"BackupManifestVersion", "backup-manifest.schema.json", "/properties/version/const"}, {"ConfigSchemaVersion", "config.user.schema.json", "/properties/schema_version/const"}, {"DepsManifestVersion", "deps-manifest.schema.json", "/properties/manifest_version/const"}} {
		doc, e := read(v[1])
		if e != nil {
			return nil, e
		}
		value, e := d.At(doc, v[2])
		if e != nil {
			return nil, e
		}
		versions.Set(v[0], value)
	}
	constants := func(pkg string, values *d.Object) string {
		s := header + "\npackage " + pkg + "\n\nconst (\n"
		for _, f := range *values {
			s += f.Name + " = " + quote(f.Value) + "\n"
		}
		return s + ")\n"
	}
	for _, p := range []string{"server/internal/platform/contractversions/versions.generated.go", "launcher/internal/contractversions/versions.generated.go"} {
		if e = putGo(p, constants("contractversions", versions)); e != nil {
			return nil, e
		}
	}
	release, e := read("release-manifest.schema.json")
	if e != nil {
		return nil, e
	}
	ids, e := d.At(release, "/$defs/artifactId/enum")
	if e != nil {
		return nil, e
	}
	artifacts := &d.Object{}
	for _, v := range d.Strings(ids) {
		name := "Artifact"
		for _, p := range strings.Split(v, "-") {
			switch p {
			case "macos":
				name += "MacOS"
			case "arm64":
				name += "ARM64"
			default:
				name += goName(p)
			}
		}
		artifacts.Set(name, v)
	}
	for _, v := range [][2]string{{"server/internal/releaseupdate", "releaseupdate"}, {"launcher/internal/desktop", "desktop"}} {
		if e = putGo(v[0]+"/artifacts.generated.go", constants(v[1], artifacts)); e != nil {
			return nil, e
		}
	}
	redaction, e := os.ReadFile(filepath.Join(root, "scripts/testdata/redaction.json"))
	if e != nil {
		return nil, e
	}
	for _, p := range []string{"server/internal/platform/redact/testdata/redaction.generated.json", "sdk/go/testdata/redaction.generated.json"} {
		outputs[p] = bytes.ReplaceAll(redaction, []byte("\r\n"), []byte("\n"))
	}
	if e = putGo("sdk/go/pluginbuild/versions.generated.go", constants("pluginbuild", &d.Object{{Name: "ArtifactVersion", Value: versions.Get("PluginArtifactVersion")}, {Name: "ManifestVersion", Value: versions.Get("PluginManifestVersion")}})); e != nil {
		return nil, e
	}
	return outputs, nil
}
func Run(args []string, out, stderr io.Writer) int {
	fs := flag.NewFlagSet("generate-plugin-wire", flag.ContinueOnError)
	fs.SetOutput(stderr)
	verify := fs.Bool("verify", false, "verify generated outputs without writing")
	if e := cli.Parse(fs, args, 0, 0); e != nil {
		return cli.ErrorTo(stderr, e)
	}
	outputs, e := Generate(repo.Root())
	var failures []string
	if e == nil {
		failures, e = generated.Sync(repo.Root(), outputs, marker, dataDirs, *verify)
	}
	if e != nil {
		fmt.Fprintln(stderr, e)
		return 1
	}
	if len(failures) > 0 {
		fmt.Fprintln(stderr, "plugin wire generation drift: "+strings.Join(failures, ", "))
		return 1
	}
	if *verify {
		fmt.Fprintln(out, "plugin wire verified")
	} else {
		fmt.Fprintln(out, "plugin wire generated")
	}
	return 0
}
