# Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.
ARTIFACT_WINDOWS_X64_FULL = "windows-x64-full"
ARTIFACT_LINUX_X64_FULL = "linux-x64-full"
ARTIFACT_MACOS_ARM64_FULL = "macos-arm64-full"
ARTIFACT_LINUX_X64_SERVER = "linux-x64-server"

ARTIFACT_IDS = (
    ARTIFACT_WINDOWS_X64_FULL,
    ARTIFACT_LINUX_X64_FULL,
    ARTIFACT_MACOS_ARM64_FULL,
    ARTIFACT_LINUX_X64_SERVER,
)
