#!/usr/bin/env python3
"""Generate Launcher's API response models and their complete schema reference closure."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess

import yaml

from generated_outputs import sync_outputs

ROOT = Path(__file__).resolve().parents[1]
ROOTS = ('LivenessStatusResponse', 'ReadinessStatusResponse', 'SystemStatusResponse', 'RecoveryCompatibilitySummary', 'SystemShutdownResponse')
HEADER = '// Code generated by scripts/generate-launcher-api.py; DO NOT EDIT.\n'


def go_name(name):
    return ''.join({'id': 'ID', 'url': 'URL', 'db': 'DB', 'http': 'HTTP', 'ws': 'WS'}.get(word, word.title()) for word in name.split('_'))


def generate(root=ROOT):
    document = yaml.safe_load((root / 'contracts/web-api.openapi.yaml').read_text(encoding='utf-8'))
    schemas = document['components']['schemas']
    closure = {}

    def visit(value):
        if isinstance(value, list):
            for child in value:
                visit(child)
        elif isinstance(value, dict):
            if '$ref' in value:
                prefix = '#/components/schemas/'
                if not value['$ref'].startswith(prefix):
                    raise ValueError('unsupported external schema reference: ' + value['$ref'])
                collect(value['$ref'][len(prefix):])
            for child in value.values():
                visit(child)

    def collect(name):
        if name not in closure:
            closure[name] = schemas[name]
            visit(schemas[name])

    for name in ROOTS:
        collect(name)
    models = {}

    def type_of(node, name, optional=False):
        if '$ref' in node:
            referenced = node['$ref'].rsplit('/', 1)[1]
            result = 'Server' + referenced
            return ('*' if optional and schemas[referenced].get('type') == 'object' else '') + result
        kind = node.get('type')
        if isinstance(kind, list):
            kinds = [value for value in kind if value != 'null']
            if len(kinds) != 1:
                raise ValueError(f'{name}: unsupported union')
            return '*' + type_of({**node, 'type': kinds[0]}, name)
        if kind == 'object':
            if 'properties' not in node:
                additional = node.get('additionalProperties', {})
                return 'map[string]' + (type_of(additional, name + 'Value') if isinstance(additional, dict) and additional else 'any')
            models[name] = node
            return ('*' if optional else '') + name
        if kind == 'array':
            return '[]' + type_of(node['items'], name + 'Item')
        if kind in ('string', 'integer', 'number', 'boolean'):
            return {'string': 'string', 'integer': 'int64', 'number': 'float64', 'boolean': 'bool'}[kind]
        raise ValueError(f'{name}: unsupported schema node {node}')

    for name, schema in sorted(closure.items()):
        models['Server' + name] = schema
    lines = [HEADER, 'package desktop\n']
    done = set()
    while len(done) != len(models):
        name = next(name for name in models if name not in done)
        done.add(name)
        schema = models[name]
        if schema.get('type') != 'object' or 'properties' not in schema:
            lines.append(f'type {name} {type_of(schema, name)}\n')
            continue
        lines.append(f'type {name} struct {{')
        for field, node in schema['properties'].items():
            optional = field not in schema.get('required', [])
            typename = type_of(node, name + go_name(field), optional)
            suffix = ',omitempty' if optional else ''
            lines.append(f' {go_name(field)} {typename} `json:"{field}{suffix}"`')
        lines.append('}\n')
    source = subprocess.check_output(['gofmt'], input='\n'.join(lines).encode('utf-8'))
    schema = {'$comment': HEADER.strip('/\n '), '$schema': 'https://json-schema.org/draft/2020-12/schema', '$defs': closure}
    schema_json = json.dumps(schema, ensure_ascii=False, indent=2).replace('#/components/schemas/', '#/$defs/') + '\n'
    # The TS subset keeps exactly the same recursive closure; no unrelated paths.
    subset = {'x-generator': HEADER.strip('/\n '), 'openapi': document['openapi'], 'info': document['info'], 'paths': {}, 'components': {'schemas': closure}}
    return {
        root / 'launcher/internal/desktop/server_models.generated.go': source,
        root / 'launcher/internal/desktop/api-contracts/responses.generated.json': schema_json.encode('utf-8'),
        root / 'launcher/api-subset.generated.json': (json.dumps(subset, ensure_ascii=False, indent=2) + '\n').encode('utf-8'),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verify', action='store_true')
    args = parser.parse_args()
    failures = sync_outputs(ROOT, generate(), b'Code generated by scripts/generate-launcher-api.py', args.verify)
    if failures:
        raise SystemExit('Launcher API generation drift: ' + ', '.join(failures))
    print('Launcher API verified' if args.verify else 'Launcher API generated')


if __name__ == '__main__':
    main()
