#!/usr/bin/env python3
"""Generate identical, independently buildable plugin wire packages from contracts."""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import yaml

from generated_outputs import sync_outputs

ROOT = Path(__file__).resolve().parents[1]
HEADER = "// Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.\n"
EVENT = "/$defs/event/allOf/1/properties/event"
PAYLOAD = EVENT + "/properties/payload"

# This table names public Go projections. Fields, required sets and scalar types
# come from schema; raw JSON is retained at heterogeneous application boundaries.
MODELS = {
    "FrameEnvelope": "/$defs/common",
    "InitFrame": "/$defs/init", "InitProgressFrame": "/$defs/init_progress",
    "InitAckFrame": "/$defs/init_ack", "EventFrame": "/$defs/event",
    "ProtocolEventFrame": EVENT,
    "ProtocolActorFrame": EVENT + "/properties/actor",
    "ProtocolTargetFrame": EVENT + "/properties/target",
    "ProtocolMessageFrame": EVENT + "/properties/message",
    "ProtocolWebhookFrame": EVENT + "/properties/webhook",
    "ProtocolPayloadFrame": PAYLOAD,
    "ProtocolOneBotPayloadFrame": PAYLOAD + "/properties/onebot",
    "ProtocolOneBotSenderFrame": PAYLOAD + "/properties/onebot/properties/sender",
    "ProtocolQQOfficialPayloadFrame": PAYLOAD + "/properties/qq_official",
    "BotIdentity": "/$defs/bot_identity", "GovernanceScope": "/$defs/governance_scope",
    "ProtocolSegmentFrame": "/$defs/outbound_message_segment",
    "ProtocolOutboundMessageFrame": "/$defs/outbound_message",
    "PingFrame": "/$defs/ping", "PongFrame": "/$defs/pong",
    "ShutdownFrame": "/$defs/shutdown", "ErrorFrame": "/$defs/error",
    "ResultFrame": "/$defs/result", "ActionFrame": "/$defs/action",
    "ProtocolActionMessageSendFrame": "/$defs/action_message_send_data",
    "ProtocolActionLoggerWriteFrame": "/$defs/action_logger_write_data",
    "ProtocolActionStorageKVFrame": "/$defs/action_storage_kv/allOf/1/properties/data",
    "ProtocolActionStorageFileFrame": "/$defs/action_storage_file/allOf/1/properties/data",
    "ProtocolActionHTTPRequestFrame": "/$defs/action_http_request/allOf/1/properties/data",
    "ProtocolActionPluginListFrame": "/$defs/action_plugin_list_data",
    "ProtocolActionSecretReadFrame": "/$defs/action_secret_read_data",
    "ProtocolActionThirdPartyAccountReadFrame": "/$defs/action_thirdparty_account_read_data",
    "ProtocolActionThirdPartyAccountValidateFrame": "/$defs/action_thirdparty_account_validate_data",
    "ProtocolActionThirdPartyResolveFrame": "/$defs/action_thirdparty_resolve_data",
    "ProtocolActionConfigWriteFrame": "/$defs/action_config_write_data",
    "ProtocolActionGovernanceBlacklistWriteFrame": "/$defs/action_governance_blacklist_write_data",
    "ProtocolActionGovernanceWhitelistWriteFrame": "/$defs/action_governance_whitelist_write_data",
    "ProtocolActionSchedulerCreateFrame": "/$defs/action_scheduler_create_data",
    "ProtocolActionRenderImageFrame": "/$defs/action_render_image_data",
    "ProtocolRenderImageResourceFrame": "/$defs/render_image_resource",
}
RAW_FIELDS = {
    ("ProtocolPayloadFrame", "command"),
    ("ActionFrame", "data"), ("ProtocolActionStorageKVFrame", "value"),
    ("ProtocolActionSchedulerCreateFrame", "payload"), ("ProtocolActionRenderImageFrame", "data"),
}
PRESENCE_FIELDS = {
    ("ProtocolWebhookFrame", "client_timestamp"), ("ProtocolPayloadFrame", "bots"),
    ("ProtocolPayloadFrame", "config"), ("ProtocolActionMessageSendFrame", "source_adapter"),
    ("ProtocolActionMessageSendFrame", "reply_to_event_id"),
    ("ProtocolActionMessageSendFrame", "message"),
    ("ProtocolActionGovernanceWhitelistWriteFrame", "enabled"),
    ("ProtocolActionHTTPRequestFrame", "timeout_seconds"),
}
for model, fields in {
    "ProtocolActionStorageKVFrame": ["key", "prefix"],
    "ProtocolActionStorageFileFrame": ["path", "prefix", "content_text", "content_base64"],
    "ProtocolActionHTTPRequestFrame": ["body_text", "body_base64"],
    "ProtocolActionGovernanceBlacklistWriteFrame": ["entry_type", "target_id", "reason"],
    "ProtocolActionGovernanceWhitelistWriteFrame": ["entry_type", "target_id", "reason"],
}.items():
    PRESENCE_FIELDS.update((model, field) for field in fields)


def at(document, pointer):
    for part in pointer.strip("/").split("/") if pointer else []:
        part = part.replace("~1", "/").replace("~0", "~")
        document = document[int(part)] if isinstance(document, list) else document[part]
    return document


def shape(node, root):
    if not isinstance(node, dict):
        return {}
    if "$ref" in node:
        if not node["$ref"].startswith("#/"):
            raise ValueError("wire generator accepts only local schema references")
        node = {**at(root, node["$ref"][1:]), **{key: value for key, value in node.items() if key != "$ref"}}
    result = {key: value for key, value in node.items() if key not in {"allOf", "oneOf", "anyOf"}}
    for part in node.get("allOf", []):
        part = shape(part, root)
        if "properties" in part:
            result["properties"] = {**result.get("properties", {}), **part["properties"]}
        if "required" in part:
            result["required"] = sorted(set(result.get("required", [])) | set(part["required"]))
        if "type" in part:
            result["type"] = part["type"]
        elif kind(part) != "any" and "type" not in result:
            result["type"] = kind(part)
    alternatives = node.get("oneOf", node.get("anyOf", []))
    if alternatives:
        alternatives = [shape(part, root) for part in alternatives]
        object_alternatives = [part for part in alternatives if "properties" in part or part.get("type") == "object"]
        if len(object_alternatives) == len(alternatives):
            fields = {}
            for part in alternatives:
                for key, value in part.get("properties", {}).items():
                    if key in fields and fields[key] != value:
                        fields[key] = {"anyOf": [fields[key], value]}
                    else:
                        fields[key] = value
            base_fields = result.get("properties", {})
            fields = {**base_fields, **{
                key: {"allOf": [base_fields[key], value]} if key in base_fields else value
                for key, value in fields.items()
            }}
            required = set(result.get("required", [])) | set.intersection(*(set(part.get("required", [])) for part in alternatives))
            result.update(type="object", properties=fields, required=sorted(required))
        else:
            kinds = {kind(part) for part in alternatives} - {"null"}
            if len(kinds) == 1:
                result["type"] = kinds.pop()
    return result


def kind(node):
    value = node.get("type")
    if isinstance(value, list):
        nonnull = [item for item in value if item != "null"]
        return nonnull[0] if len(nonnull) == 1 else "any"
    if value:
        return value
    if "properties" in node:
        return "object"
    if node.get("enum") and all(isinstance(value, str) for value in node["enum"]):
        return "string"
    if "const" in node:
        value = node["const"]
        return "boolean" if isinstance(value, bool) else "integer" if isinstance(value, int) else "string"
    return "any"


def go_name(name):
    special = {"id": "ID", "ids": "IDs", "url": "URL", "urls": "URLs", "http": "HTTP", "kv": "KV", "qq": "QQ", "openid": "OpenID", "onebot": "OneBot"}
    return "".join(special.get(part, part.title()) for part in name.split("_"))


class GoModels:
    def __init__(self, schema):
        self.schema = schema
        self.named_nodes = {id(at(schema, path)): name for name, path in MODELS.items()}

    def field_type(self, model, name, node, required):
        if model == "ProtocolEventFrame" and name == "raw_payload":
            return "any"
        if (model, name) in RAW_FIELDS:
            return "json.RawMessage"
        if model == "ProtocolActionConfigWriteFrame" and name == "values":
            return "map[string]json.RawMessage"
        if name == "scope" and model.startswith("ProtocolActionGovernance"):
            return "GovernanceScope"
        if model in {"ProtocolMessageFrame", "ProtocolOutboundMessageFrame"} and name == "segments":
            return "[]ProtocolSegmentFrame"
        resolved = at(self.schema, node["$ref"][1:]) if isinstance(node, dict) and "$ref" in node else node
        named = self.named_nodes.get(id(resolved))
        expanded = shape(node, self.schema)
        category = kind(expanded)
        if named and named != model and category == "object":
            result = named if required else "*" + named
        elif category == "string":
            result = "string"
        elif category == "integer":
            result = "int64" if name in {"timestamp", "time", "received_at", "client_timestamp"} else "int"
        elif category == "number":
            result = "float64"
        elif category == "boolean":
            result = "bool"
        elif category == "array":
            result = "[]" + self.field_type(model, name + "_item", expanded.get("items", {}), True)
        elif category == "object":
            additional = expanded.get("additionalProperties")
            value_type = self.field_type(model, name + "_value", additional, True) if isinstance(additional, dict) else "any"
            result = "map[string]" + value_type
        else:
            result = "any"
        if (model, name) in PRESENCE_FIELDS and not result.startswith("*"):
            result = "*" + result
        return result

    def render(self):
        lines = [HEADER, "package pluginwire\n", 'import "encoding/json"\n']
        shapes = {}
        for name, pointer in MODELS.items():
            node = shape(at(self.schema, pointer), self.schema)
            fields = node.get("properties", {})
            if not fields:
                raise ValueError(f"{pointer}: expected a named object projection")
            shapes[name] = node
            lines.append(f"type {name} struct {{")
            for field, property_schema in fields.items():
                required = field in node.get("required", [])
                go_type = self.field_type(name, field, property_schema, required)
                optional = "" if required else ",omitempty"
                lines.append(f' {go_name(field)} {go_type} `json:"{field}{optional}"`')
            lines.append("}\n")
        # A decoding/dispatch projection combines the top-level alternatives. Its
        # raw event/data fields retain unions; Validate checks the selected branch.
        variants = ["InitFrame", "InitProgressFrame", "InitAckFrame", "EventFrame", "ActionFrame", "ResultFrame", "ErrorFrame", "PingFrame", "PongFrame", "ShutdownFrame"]
        fields = {}
        required_by_type = {}
        for variant in variants:
            node = shapes[variant]
            discriminator = shape(node["properties"]["type"], self.schema).get("const", "action")
            required_by_type[discriminator] = node.get("required", [])
            for name, property_schema in node["properties"].items():
                fields.setdefault(name, (variant, property_schema))
        lines.append("type Frame struct {")
        for name, (variant, property_schema) in fields.items():
            go_type = "json.RawMessage" if name in {"event", "data"} else self.field_type(variant, name, property_schema, True)
            if name == "bots":
                go_type = "*[]BotIdentity"
            suffix = "" if name in {"type", "request_id"} else ",omitempty"
            lines.append(f' {go_name(name)} {go_type} `json:"{name}{suffix}"`')
        lines.append("}\n")
        lines += ["func (frame Frame) MarshalJSON() ([]byte, error) {", " type plain Frame", " encoded, err := json.Marshal(plain(frame)); if err != nil { return nil, err }", " var object map[string]json.RawMessage; if err := json.Unmarshal(encoded, &object); err != nil { return nil, err }", " switch frame.Type {"]
        for discriminator, required in required_by_type.items():
            lines.append(f" case {json.dumps(discriminator)}:")
            for field in required:
                lines.append(f'  if _, present := object[{json.dumps(field)}]; !present {{ value, err := json.Marshal(frame.{go_name(field)}); if err != nil {{ return nil, err }}; object[{json.dumps(field)}] = value }}')
        lines += [" }", " return json.Marshal(object)", "}\n"]
        return "\n".join(lines)


CODEC = '''package pluginwire
import (
 "bytes"
 _ "embed"
 "encoding/json"
 "errors"
 "fmt"
 "io"
 "sync"
 jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed protocol.schema.json
var schemaJSON []byte
var compileOnce sync.Once
var compiled *jsonschema.Schema
var compileError error
var ErrFrameTooLarge = errors.New("plugin protocol frame exceeds byte limit")
type ValidationError struct { Cause error }
func (e *ValidationError) Error() string { return "plugin frame violates the protocol schema" }
func (e *ValidationError) Unwrap() error { return e.Cause }

func Validate(data []byte, maxBytes int) error {
 data = bytes.TrimSuffix(data, []byte{'\\n'})
 if maxBytes <= 0 { maxBytes = DefaultMaxFrameBytes }
 if len(data) > maxBytes { return fmt.Errorf("%w: limit=%d", ErrFrameTooLarge, maxBytes) }
 compileOnce.Do(func(){
  var document any
  if compileError = json.Unmarshal(schemaJSON, &document); compileError != nil { return }
  compiler := jsonschema.NewCompiler(); compiler.AssertFormat()
  const location = "urn:rayleabot:plugin-protocol"
  if compileError = compiler.AddResource(location, document); compileError != nil { return }
  compiled, compileError = compiler.Compile(location)
 })
 if compileError != nil { return fmt.Errorf("compile plugin schema: %w", compileError) }
 decoder := json.NewDecoder(bytes.NewReader(data)); decoder.UseNumber()
 var value any
 if err := decoder.Decode(&value); err != nil { return err }
 if err := decoder.Decode(new(any)); err != io.EOF { return errors.New("plugin frame must contain exactly one JSON value") }
 if err := compiled.Validate(value); err != nil { return &ValidationError{Cause: err} }
 return nil
}
'''


def gofmt(source):
    return subprocess.check_output(["gofmt"], input=source.encode("utf-8"))


def generate():
    schema = json.loads((ROOT / "contracts/plugin-protocol.schema.json").read_text(encoding="utf-8"))
    config = json.loads((ROOT / "contracts/config.user.schema.json").read_text(encoding="utf-8"))
    protocol_version = at(schema, "/$defs/init/allOf/1/properties/protocol_version/const")
    max_bytes = at(config, "/properties/runtime/properties/ipc_message_max_bytes/default")
    models = gofmt(GoModels(schema).render() + f'\nconst ProtocolVersion = {json.dumps(protocol_version)}\nconst DefaultMaxFrameBytes = {max_bytes}\n')
    codec = gofmt(HEADER + CODEC)
    source = (ROOT / "contracts/plugin-protocol.schema.json").read_text(encoding="utf-8").replace("\r\n", "\n").encode("utf-8")
    outputs = {}
    action_kinds = HEADER + "\npackage pluginwire\n"
    for name, definition in [("IsOneBotAction", "onebot_action_kind"), ("IsProviderExtensionAction", "provider_extension_action_kind")]:
        values = at(schema, f"/$defs/{definition}/enum")
        cases = ", ".join(json.dumps(value) for value in values)
        action_kinds += f"\nfunc {name}(kind string) bool {{\nswitch kind {{\ncase {cases}:\nreturn true\ndefault:\nreturn false\n}}\n}}\n"
    outputs[ROOT / "server/internal/plugins/pluginwire/action_kinds.generated.go"] = gofmt(action_kinds)
    for directory in ["server/internal/plugins/pluginwire", "sdk/go/internal/pluginwire"]:
        outputs[ROOT / directory / "protocol.generated.go"] = models
        outputs[ROOT / directory / "codec.generated.go"] = codec
        outputs[ROOT / directory / "protocol.schema.json"] = source
        outputs[ROOT / directory / "codec.generated_test.go"] = gofmt(HEADER + (ROOT / "scripts/templates/pluginwire_test.go").read_text(encoding="utf-8"))
        vectors = []
        for path in sorted((ROOT / "fixtures/plugin-protocol").glob("*.yaml")):
            fixture = yaml.safe_load(path.read_text(encoding="utf-8"))
            vectors.append({"name": path.name, "valid": fixture["expect"]["valid"], "frames": fixture["frames"]})
        outputs[ROOT / directory / "testdata/frames.generated.json"] = (json.dumps(vectors, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    versions = {}
    for name, file, pointer in [
        ("PluginProtocolVersion", "plugin-protocol.schema.json", "/$defs/init/allOf/1/properties/protocol_version/const"),
        ("PluginManifestVersion", "plugin-info.schema.json", "/properties/manifest_version/const"),
        ("PluginArtifactVersion", "plugin-artifact.schema.json", "/properties/artifact_version/const"),
        ("PluginUIBridgeVersion", "plugin-management-ui-bridge.schema.json", "/properties/version/const"),
        ("BackupManifestVersion", "backup-manifest.schema.json", "/properties/version/const"),
        ("ConfigSchemaVersion", "config.user.schema.json", "/properties/schema_version/const"),
        ("DepsManifestVersion", "deps-manifest.schema.json", "/properties/manifest_version/const"),
        ("UpdateProtocolVersion", "release-manifest.schema.json", "/x-current-update-protocol-version"),
    ]:
        document = json.loads((ROOT / "contracts" / file).read_text(encoding="utf-8"))
        versions[name] = at(document, pointer)
    text = HEADER + "\npackage contractversions\n\nconst (\n" + "\n".join(
        f" {name} = {json.dumps(value)}" for name, value in versions.items()
    ) + "\n)\n"
    outputs[ROOT / "server/internal/platform/contractversions/versions.generated.go"] = gofmt(text)
    outputs[ROOT / "launcher/internal/contractversions/versions.generated.go"] = gofmt(text)
    python_names = {
        "PLUGIN_MANIFEST_VERSION": "PluginManifestVersion", "PLUGIN_UI_BRIDGE_VERSION": "PluginUIBridgeVersion",
        "UPDATE_PROTOCOL_VERSION": "UpdateProtocolVersion",
    }
    python = "# Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.\n" + "\n".join(
        f"{name} = {json.dumps(versions[source])}" for name, source in python_names.items()
    ) + "\n"
    outputs[ROOT / "scripts/release/contract_versions_generated.py"] = python.encode("utf-8")
    release_schema = json.loads((ROOT / "contracts/release-manifest.schema.json").read_text(encoding="utf-8"))
    artifact_ids = at(release_schema, "/$defs/artifactId/enum")
    artifact_constants = {
        "Artifact" + "".join({"macos": "MacOS", "arm64": "ARM64"}.get(part, part.title()) for part in value.split("-")): value
        for value in artifact_ids
    }
    for directory, package in [("server/internal/releaseupdate", "releaseupdate"), ("launcher/internal/desktop", "desktop")]:
        text = HEADER + f"\npackage {package}\n\nconst (\n" + "\n".join(
            f" {name} = {json.dumps(value)}" for name, value in artifact_constants.items()
        ) + "\n)\n"
        outputs[ROOT / directory / "artifacts.generated.go"] = gofmt(text)
    python = "# Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.\n" + "\n".join(
        f"ARTIFACT_{value.upper().replace('-', '_')} = {json.dumps(value)}" for value in artifact_ids
    ) + "\n\nARTIFACT_IDS = (\n" + "".join(f"    ARTIFACT_{value.upper().replace('-', '_')},\n" for value in artifact_ids) + ")\n"
    outputs[ROOT / "scripts/artifact_ids_generated.py"] = python.encode("utf-8")
    vectors = (ROOT / "scripts/testdata/redaction.json").read_bytes().replace(b"\r\n", b"\n")
    for target in ["server/internal/platform/redact/testdata/redaction.generated.json", "sdk/go/testdata/redaction.generated.json"]:
        outputs[ROOT / target] = vectors
    text = HEADER + "\npackage pluginbuild\n\nconst (\n" + "\n".join(
        f" {name} = {json.dumps(versions[source])}" for name, source in {
            "ArtifactVersion": "PluginArtifactVersion", "ManifestVersion": "PluginManifestVersion",
        }.items()
    ) + "\n)\n"
    outputs[ROOT / "sdk/go/pluginbuild/versions.generated.go"] = gofmt(text)
    return outputs



def sync_owned_data(outputs, verify):
    # Raw schema copies and JSON test vectors cannot carry Go ownership headers.
    # These generated-data directories are exclusively owned by this generator.
    stale = []
    for directory in [
        "server/internal/plugins/pluginwire", "sdk/go/internal/pluginwire",
        "server/internal/plugins/pluginwire/testdata", "sdk/go/internal/pluginwire/testdata",
        "server/internal/platform/redact/testdata", "sdk/go/testdata",
    ]:
        for pattern in ("*.schema.json", "*.generated.json"):
            for path in (ROOT / directory).glob(pattern):
                if path not in outputs:
                    if verify:
                        stale.append(path.relative_to(ROOT).as_posix())
                    else:
                        path.unlink()
    return sorted(stale)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    outputs = generate()
    failures = sync_outputs(ROOT, outputs, b"Code generated by scripts/generate-plugin-wire.py", args.verify)
    failures.extend(sync_owned_data(outputs, args.verify))
    if failures:
        raise SystemExit("plugin wire generation drift: " + ", ".join(failures))
    print("plugin wire verified" if args.verify else "plugin wire generated")


if __name__ == "__main__":
    main()
