#!/usr/bin/env python3
"""Generate the server and Web error catalogs from the formal error contract."""
from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path

import yaml
from generated_outputs import sync_outputs

ROOT = Path(__file__).resolve().parents[1]


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def generate(codes: dict, diagnostics: dict) -> dict[Path, str]:
    constants: list[str] = []
    definitions: list[str] = []
    messages: dict[str, dict[str, str]] = {}
    web: dict[str, dict] = {}
    names: set[str] = set()
    for code, entry in sorted(codes.items()):
        if entry['code'] != code or entry['message_key'] != 'errors.' + code:
            raise ValueError(f'{code}: inconsistent code/message_key')
        name = ''.join(part[:1].upper() + part[1:] for part in re.split(r'[._]', code))
        if name in names:
            raise ValueError(f'duplicate Go name: {name}')
        names.add(name)
        status = entry['http_status'] or 0
        surfaces = entry['applies_to']
        if ('http' in surfaces) != (status != 0):
            raise ValueError(f'{code}: HTTP applicability and status must agree')
        constants.append(f'{name} = {quoted(code)}')
        constants.append(f'{name}MessageKey = {quoted(entry["message_key"])}')
        definitions.append(
            f'{name}: {{Code: {name}, HTTPStatus: {status}, MessageKey: {name}MessageKey, '
            f'Message: {quoted(entry["message"])}, Retryable: {str(entry["retryable"]).lower()}, '
            f'Surfaces: {quoted(",".join(surfaces))}}},'
        )
        domain, key = code.split('.', 1)
        messages.setdefault(domain, {})[key] = entry['message']
        web[code] = {'messageKey': entry['message_key'], 'httpStatus': entry['http_status'], 'retryable': entry['retryable']}
    diagnostic_definitions: list[str] = []
    for code, entry in sorted(diagnostics.items()):
        if code in codes or not isinstance(entry.get('description'), str) or not entry['description'].strip():
            raise ValueError(f'{code}: invalid or duplicated diagnostic identity')
        name = 'Diagnostic' + ''.join(part[:1].upper() + part[1:] for part in re.split(r'[._]', code))
        constants.append(f'{name} = {quoted(code)}')
        diagnostic_definitions.append(f'{name}: {quoted(entry["description"])},')
    go = '''// Code generated by scripts/generate-error-codes.py; DO NOT EDIT.
package errorcodes

const (
''' + '\n'.join(constants) + '''
)

var catalog = map[string]Definition{
''' + '\n'.join(definitions) + '\n}\n\nvar diagnostics = map[string]string{\n' + '\n'.join(diagnostic_definitions) + '\n}\n'
    formatted = subprocess.run(['gofmt'], input=go, text=True, encoding='utf-8', capture_output=True, check=True).stdout
    ts = '// Generated by scripts/generate-error-codes.py. Do not edit.\n\n'
    ts += 'export const errorCatalog = ' + json.dumps(web, ensure_ascii=False, indent=2) + ' as const\n\n'
    ts += 'export const errorMessages = ' + json.dumps(messages, ensure_ascii=False, indent=2) + ' as const\n'
    return {
        ROOT / 'server/internal/errorcodes/catalog.generated.go': formatted,
        ROOT / 'web/src/types/error-codes.generated.ts': ts,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verify', action='store_true')
    args = parser.parse_args()
    document = yaml.safe_load((ROOT / 'contracts/error-codes.yaml').read_text(encoding='utf-8'))
    outputs = {path: content.encode('utf-8') for path, content in generate(document['codes'], document.get('diagnostics', {})).items()}
    stale = sync_outputs(ROOT, outputs, b'by scripts/generate-error-codes.py', args.verify)
    if stale:
        raise SystemExit('error catalog drift: ' + ', '.join(stale))
    print('error catalogs verified' if args.verify else 'error catalogs generated')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
