// Code generated by tools/cmd/generate-plugin-wire from contracts; DO NOT EDIT.

package desktop

const (
	ArtifactWindowsX64Full = "windows-x64-full"
	ArtifactLinuxX64Full   = "linux-x64-full"
	ArtifactMacOSARM64Full = "macos-arm64-full"
	ArtifactLinuxX64Server = "linux-x64-server"
)
