// Code generated by scripts/generate-launcher-api.py; DO NOT EDIT.

package desktop

type ServerAdapterProtocol string

type ServerAdapterState string

type ServerAdapterStatus struct {
	ID       string                `json:"id"`
	Protocol ServerAdapterProtocol `json:"protocol"`
	Enabled  bool                  `json:"enabled"`
	State    ServerAdapterState    `json:"state"`
}

type ServerDiagnosticIssue struct {
	Code             string   `json:"code"`
	Severity         string   `json:"severity"`
	Summary          string   `json:"summary"`
	UserMessage      string   `json:"user_message,omitempty"`
	Remediation      string   `json:"remediation,omitempty"`
	InternalReason   string   `json:"internal_reason,omitempty"`
	RuntimeResources []string `json:"runtime_resources,omitempty"`
}

type ServerLivenessStatusResponse struct {
	Status string `json:"status"`
}

type ServerReadinessStatusResponse struct {
	Status          string                               `json:"status"`
	Reason          string                               `json:"reason,omitempty"`
	ReasonCodes     []string                             `json:"reason_codes,omitempty"`
	Checks          *ServerReadinessStatusResponseChecks `json:"checks,omitempty"`
	Issues          []ServerDiagnosticIssue              `json:"issues,omitempty"`
	RecoverySummary *ServerRecoveryCompatibilitySummary  `json:"recovery_summary,omitempty"`
}

type ServerRecoveryCompatibilityAuditEntry struct {
	TaskID     string                                 `json:"task_id"`
	CreatedAt  string                                 `json:"created_at"`
	OperatorID string                                 `json:"operator_id"`
	Note       string                                 `json:"note"`
	Items      []ServerRecoveryCompatibilityAuditItem `json:"items"`
}

type ServerRecoveryCompatibilityAuditItem struct {
	ReviewID   string `json:"review_id"`
	PluginID   string `json:"plugin_id"`
	ReasonCode string `json:"reason_code"`
	Summary    string `json:"summary"`
	Version    string `json:"version,omitempty"`
}

type ServerRecoveryCompatibilityIssue struct {
	Code             string   `json:"code"`
	Severity         string   `json:"severity"`
	Summary          string   `json:"summary"`
	Remediation      string   `json:"remediation,omitempty"`
	RuntimeResources []string `json:"runtime_resources,omitempty"`
}

type ServerRecoveryCompatibilitySkippedPlugin struct {
	PluginID     string `json:"plugin_id"`
	Version      string `json:"version,omitempty"`
	ReasonCode   string `json:"reason_code"`
	Summary      string `json:"summary"`
	ReviewID     string `json:"review_id"`
	ReviewStatus string `json:"review_status"`
	ReviewedAt   string `json:"reviewed_at,omitempty"`
	ReviewedBy   string `json:"reviewed_by,omitempty"`
	ManualAction string `json:"manual_action,omitempty"`
	ManifestPath string `json:"manifest_path,omitempty"`
}

type ServerRecoveryCompatibilitySummary struct {
	Status                    string                                     `json:"status"`
	Phase                     string                                     `json:"phase"`
	Operation                 string                                     `json:"operation"`
	CreatedAt                 string                                     `json:"created_at"`
	UpdatedAt                 string                                     `json:"updated_at"`
	SourceCoreVersion         string                                     `json:"source_core_version,omitempty"`
	TargetCoreVersion         string                                     `json:"target_core_version,omitempty"`
	SourceConfigSchemaVersion string                                     `json:"source_config_schema_version,omitempty"`
	TargetConfigSchemaVersion string                                     `json:"target_config_schema_version,omitempty"`
	SourceDBSchemaVersion     string                                     `json:"source_db_schema_version,omitempty"`
	TargetDBSchemaVersion     string                                     `json:"target_db_schema_version,omitempty"`
	RequiresPostStartChecks   bool                                       `json:"requires_post_start_checks,omitempty"`
	Issues                    []ServerRecoveryCompatibilityIssue         `json:"issues,omitempty"`
	SkippedPlugins            []ServerRecoveryCompatibilitySkippedPlugin `json:"skipped_plugins,omitempty"`
	ManualActions             []string                                   `json:"manual_actions,omitempty"`
	NextSteps                 []string                                   `json:"next_steps,omitempty"`
	Audit                     []ServerRecoveryCompatibilityAuditEntry    `json:"audit,omitempty"`
}

type ServerSystemShutdownResponse struct {
	Accepted bool `json:"accepted"`
}

type ServerSystemStatusResponse struct {
	Status          string                              `json:"status"`
	Adapters        []ServerAdapterStatus               `json:"adapters"`
	ActivePlugins   int64                               `json:"active_plugins,omitempty"`
	RunningPlugins  int64                               `json:"running_plugins,omitempty"`
	FailedPlugins   int64                               `json:"failed_plugins,omitempty"`
	DBSchemaVersion string                              `json:"db_schema_version,omitempty"`
	UptimeSeconds   int64                               `json:"uptime_seconds,omitempty"`
	RecoverySummary *ServerRecoveryCompatibilitySummary `json:"recovery_summary,omitempty"`
	Health          *ServerReadinessStatusResponse      `json:"health,omitempty"`
}

type ServerReadinessStatusResponseChecks struct {
	Config   string `json:"config,omitempty"`
	Database string `json:"database,omitempty"`
	Runtime  string `json:"runtime,omitempty"`
	Render   string `json:"render,omitempty"`
}
