package action

import runtimeprotocol "github.com/RayleaBot/RayleaBot/server/internal/runtime/protocol"

type protocolActionMessageSendFrame = runtimeprotocol.ProtocolActionMessageSendFrame
type protocolActionMessageReplyFrame = runtimeprotocol.ProtocolActionMessageReplyFrame
type protocolActionLoggerWriteFrame = runtimeprotocol.ProtocolActionLoggerWriteFrame
type protocolActionStorageKVFrame = runtimeprotocol.ProtocolActionStorageKVFrame
type protocolActionConfigReadFrame = runtimeprotocol.ProtocolActionConfigReadFrame
type protocolActionPluginListFrame = runtimeprotocol.ProtocolActionPluginListFrame
type protocolActionSecretReadFrame = runtimeprotocol.ProtocolActionSecretReadFrame
type protocolActionConfigWriteFrame = runtimeprotocol.ProtocolActionConfigWriteFrame
type protocolActionGovernanceBlacklistWriteFrame = runtimeprotocol.ProtocolActionGovernanceBlacklistWriteFrame
type protocolActionGovernanceWhitelistWriteFrame = runtimeprotocol.ProtocolActionGovernanceWhitelistWriteFrame
type protocolActionStorageFileFrame = runtimeprotocol.ProtocolActionStorageFileFrame
type protocolActionHTTPRequestFrame = runtimeprotocol.ProtocolActionHTTPRequestFrame
type protocolActionSchedulerCreateFrame = runtimeprotocol.ProtocolActionSchedulerCreateFrame
type protocolActionEventExposeWebhookFrame = runtimeprotocol.ProtocolActionEventExposeWebhookFrame
type protocolWebhookReplayProtectionFrame = runtimeprotocol.ProtocolWebhookReplayProtectionFrame
type protocolActionRenderImageFrame = runtimeprotocol.ProtocolActionRenderImageFrame
type protocolSegmentFrame = runtimeprotocol.ProtocolSegmentFrame
