// Code generated by scripts/generate-error-codes.py; DO NOT EDIT.
package errorcodes

const (
	AdapterApiCallFailed                       = "adapter.api_call_failed"
	AdapterAuthFailed                          = "adapter.auth_failed"
	AdapterCapabilityUnsupported               = "adapter.capability_unsupported"
	AdapterConnectionFailed                    = "adapter.connection_failed"
	AdapterConnectionLost                      = "adapter.connection_lost"
	AdapterMatrixProjectionFailed              = "adapter.matrix_projection_failed"
	AdapterMessageQuotaExceeded                = "adapter.message_quota_exceeded"
	AdapterProviderExtensionNotSupported       = "adapter.provider_extension_not_supported"
	AdapterReplyTargetMissing                  = "adapter.reply_target_missing"
	AdapterReplyWindowExpired                  = "adapter.reply_window_expired"
	AdapterSendFailed                          = "adapter.send_failed"
	AdapterSendUnconfirmed                     = "adapter.send_unconfirmed"
	AdapterTransportForwardWsConnectionFailed  = "adapter.transport_forward_ws_connection_failed"
	AdapterTransportForwardWsSessionLost       = "adapter.transport_forward_ws_session_lost"
	AdapterTransportHttpApiAuthFailed          = "adapter.transport_http_api_auth_failed"
	AdapterTransportHttpApiInvalidResponse     = "adapter.transport_http_api_invalid_response"
	AdapterTransportHttpApiRequestFailed       = "adapter.transport_http_api_request_failed"
	AdapterTransportNotImplemented             = "adapter.transport_not_implemented"
	AdapterTransportReverseWsAuthFailed        = "adapter.transport_reverse_ws_auth_failed"
	AdapterTransportReverseWsUpgradeFailed     = "adapter.transport_reverse_ws_upgrade_failed"
	AdapterTransportUnavailable                = "adapter.transport_unavailable"
	AdapterTransportWebhookAuthFailed          = "adapter.transport_webhook_auth_failed"
	AdapterTransportWebhookDuplicateEvent      = "adapter.transport_webhook_duplicate_event"
	AdapterTransportWebhookInvalidPayload      = "adapter.transport_webhook_invalid_payload"
	PermissionAuthenticationRequired           = "permission.authentication_required"
	PermissionBlacklisted                      = "permission.blacklisted"
	PermissionCurrentSecretInvalid             = "permission.current_secret_invalid"
	PermissionDenied                           = "permission.denied"
	PermissionNotWhitelisted                   = "permission.not_whitelisted"
	PermissionUnavailable                      = "permission.unavailable"
	PlatformInternalError                      = "platform.internal_error"
	PlatformInvalidConfig                      = "platform.invalid_config"
	PlatformInvalidRequest                     = "platform.invalid_request"
	PlatformRateLimited                        = "platform.rate_limited"
	PlatformRenderInputTooLarge                = "platform.render_input_too_large"
	PlatformRenderQueueFull                    = "platform.render_queue_full"
	PlatformRenderTimeout                      = "platform.render_timeout"
	PlatformResourceBusy                       = "platform.resource_busy"
	PlatformResourceMissing                    = "platform.resource_missing"
	PlatformResourceNotFound                   = "platform.resource_not_found"
	PlatformStateConflict                      = "platform.state_conflict"
	PlatformTaskQueueFull                      = "platform.task_queue_full"
	PlatformTaskTimeout                        = "platform.task_timeout"
	PlatformTemplateNotFound                   = "platform.template_not_found"
	PlatformUpstreamRequestFailed              = "platform.upstream_request_failed"
	PlatformUpstreamResponseTooLarge           = "platform.upstream_response_too_large"
	PlatformUserRateLimited                    = "platform.user_rate_limited"
	PlatformValueTooLarge                      = "platform.value_too_large"
	PluginArtifactInvalid                      = "plugin.artifact_invalid"
	PluginContractUnsupported                  = "plugin.contract_unsupported"
	PluginCoreVersionIncompatible              = "plugin.core_version_incompatible"
	PluginEventCanceled                        = "plugin.event_canceled"
	PluginEventTimeout                         = "plugin.event_timeout"
	PluginInitTimeout                          = "plugin.init_timeout"
	PluginInstallDigestMismatch                = "plugin.install_digest_mismatch"
	PluginInstallFailed                        = "plugin.install_failed"
	PluginInstallInspectionExpired             = "plugin.install_inspection_expired"
	PluginInstallInspectionRequired            = "plugin.install_inspection_required"
	PluginInternalError                        = "plugin.internal_error"
	PluginManagementActionFailed               = "plugin.management_action_failed"
	PluginNotHandled                           = "plugin.not_handled"
	PluginNotRecoverable                       = "plugin.not_recoverable"
	PluginPackageResourceLimitExceeded         = "plugin.package_resource_limit_exceeded"
	PluginPackageUnsafeEntry                   = "plugin.package_unsafe_entry"
	PluginPermissionDenied                     = "plugin.permission_denied"
	PluginPlatformMismatch                     = "plugin.platform_mismatch"
	PluginProtocolViolation                    = "plugin.protocol_violation"
	PluginSessionConflict                      = "plugin.session_conflict"
	PluginSettingsApplyFailed                  = "plugin.settings_apply_failed"
	PluginShutdown                             = "plugin.shutdown"
	PluginShutdownTimeout                      = "plugin.shutdown_timeout"
	PluginStopping                             = "plugin.stopping"
	PluginStoreCatalogUnavailable              = "plugin.store_catalog_unavailable"
	PluginStoreIntegrityMismatch               = "plugin.store_integrity_mismatch"
	PluginStoreReleaseUnavailable              = "plugin.store_release_unavailable"
	PluginStoreSourceConflict                  = "plugin.store_source_conflict"
	PluginStoreSourceImmutable                 = "plugin.store_source_immutable"
	PluginTrustedCodeConfirmationRequired      = "plugin.trusted_code_confirmation_required"
	PluginUninstallFailed                      = "plugin.uninstall_failed"
	PluginWebhookReplayRejected                = "plugin.webhook_replay_rejected"
	PluginWebhookTimestampSkew                 = "plugin.webhook_timestamp_skew"
	ReleaseManifestInvalid                     = "release.manifest_invalid"
	DiagnosticAuthUnavailable                  = "auth.unavailable"
	DiagnosticConfigNotAccessible              = "config.not_accessible"
	DiagnosticConfigOk                         = "config.ok"
	DiagnosticDatabaseOk                       = "database.ok"
	DiagnosticDatabasePathUnresolvable         = "database.path_unresolvable"
	DiagnosticDatabasePingFailed               = "database.ping_failed"
	DiagnosticDepsManifest                     = "deps.manifest"
	DiagnosticDepsManifestInvalid              = "deps.manifest_invalid"
	DiagnosticDepsManifestMissing              = "deps.manifest_missing"
	DiagnosticDepsManifestPlatformMissing      = "deps.manifest_platform_missing"
	DiagnosticHtmlCompileFailed                = "html.compile_failed"
	DiagnosticInputSchemaCompileFailed         = "input_schema.compile_failed"
	DiagnosticLoggingRecentErrorsUnavailable   = "logging.recent_errors_unavailable"
	DiagnosticPlatformTemplateSourceInvalid    = "platform.template_source_invalid"
	DiagnosticPluginMinCoreVersion             = "plugin.min_core_version"
	DiagnosticRecoveryBlocked                  = "recovery.blocked"
	DiagnosticRecoveryConfigSchemaUnsupported  = "recovery.config_schema_unsupported"
	DiagnosticRecoveryDbSchemaUnsupported      = "recovery.db_schema_unsupported"
	DiagnosticRecoveryDegraded                 = "recovery.degraded"
	DiagnosticRecoveryPluginIncompatible       = "recovery.plugin_incompatible"
	DiagnosticRecoveryPluginMinCoreVersion     = "recovery.plugin_min_core_version"
	DiagnosticRecoveryPluginPlatformMismatch   = "recovery.plugin_platform_mismatch"
	DiagnosticRecoveryPostStartChecksRequired  = "recovery.post_start_checks_required"
	DiagnosticSchemaInvalid                    = "schema.invalid"
	DiagnosticSchemaOk                         = "schema.ok"
	DiagnosticSetupRequired                    = "setup.required"
	DiagnosticStorageSchemaMetadataUnavailable = "storage.schema_metadata_unavailable"
	DiagnosticWindowsLongPathsDisabled         = "windows.long_paths_disabled"
	DiagnosticWindowsLongPathsEnabled          = "windows.long_paths_enabled"
	DiagnosticWindowsLongPathsUnavailable      = "windows.long_paths_unavailable"
)

var catalog = map[string]Definition{
	AdapterApiCallFailed:                      {Code: AdapterApiCallFailed, HTTPStatus: 502, Message: "协议 API 调用失败", Retryable: true, Surfaces: "http,websocket,plugin_protocol"},
	AdapterAuthFailed:                         {Code: AdapterAuthFailed, HTTPStatus: 401, Message: "协议鉴权失败", Retryable: false, Surfaces: "http,websocket,readiness,plugin_protocol"},
	AdapterCapabilityUnsupported:              {Code: AdapterCapabilityUnsupported, HTTPStatus: 400, Message: "当前适配器不支持该能力", Retryable: false, Surfaces: "http,plugin_protocol"},
	AdapterConnectionFailed:                   {Code: AdapterConnectionFailed, HTTPStatus: 503, Message: "协议连接建立失败", Retryable: true, Surfaces: "http,websocket,readiness,plugin_protocol"},
	AdapterConnectionLost:                     {Code: AdapterConnectionLost, HTTPStatus: 503, Message: "协议连接已断开", Retryable: true, Surfaces: "http,websocket,plugin_protocol,readiness"},
	AdapterMatrixProjectionFailed:             {Code: AdapterMatrixProjectionFailed, HTTPStatus: 500, Message: "协议兼容矩阵生成失败", Retryable: true, Surfaces: "http,websocket"},
	AdapterMessageQuotaExceeded:               {Code: AdapterMessageQuotaExceeded, HTTPStatus: 429, Message: "主动推送额度已用完", Retryable: true, Surfaces: "http,plugin_protocol"},
	AdapterProviderExtensionNotSupported:      {Code: AdapterProviderExtensionNotSupported, HTTPStatus: 501, Message: "当前 provider 扩展能力尚未实现", Retryable: false, Surfaces: "http,websocket,plugin_protocol"},
	AdapterReplyTargetMissing:                 {Code: AdapterReplyTargetMissing, HTTPStatus: 409, Message: "回复目标不存在或已失效", Retryable: false, Surfaces: "http,websocket,plugin_protocol"},
	AdapterReplyWindowExpired:                 {Code: AdapterReplyWindowExpired, HTTPStatus: 409, Message: "消息回复时限已过", Retryable: false, Surfaces: "http,plugin_protocol"},
	AdapterSendFailed:                         {Code: AdapterSendFailed, HTTPStatus: 502, Message: "消息发送失败", Retryable: true, Surfaces: "http,websocket,plugin_protocol"},
	AdapterSendUnconfirmed:                    {Code: AdapterSendUnconfirmed, HTTPStatus: 504, Message: "消息发送结果未确认", Retryable: false, Surfaces: "http,websocket,plugin_protocol,logs"},
	AdapterTransportForwardWsConnectionFailed: {Code: AdapterTransportForwardWsConnectionFailed, HTTPStatus: 503, Message: "OneBot 主动连接建立失败", Retryable: true, Surfaces: "http,websocket,readiness"},
	AdapterTransportForwardWsSessionLost:      {Code: AdapterTransportForwardWsSessionLost, HTTPStatus: 503, Message: "OneBot 主动连接已断开", Retryable: true, Surfaces: "http,websocket,plugin_protocol,readiness"},
	AdapterTransportHttpApiAuthFailed:         {Code: AdapterTransportHttpApiAuthFailed, HTTPStatus: 401, Message: "OneBot HTTP API 鉴权失败", Retryable: false, Surfaces: "http,websocket,plugin_protocol,readiness"},
	AdapterTransportHttpApiInvalidResponse:    {Code: AdapterTransportHttpApiInvalidResponse, HTTPStatus: 502, Message: "OneBot HTTP API 响应不合法", Retryable: true, Surfaces: "http,websocket,plugin_protocol,readiness"},
	AdapterTransportHttpApiRequestFailed:      {Code: AdapterTransportHttpApiRequestFailed, HTTPStatus: 502, Message: "OneBot HTTP API 请求失败", Retryable: true, Surfaces: "http,websocket,plugin_protocol,readiness"},
	AdapterTransportNotImplemented:            {Code: AdapterTransportNotImplemented, HTTPStatus: 501, Message: "当前协议传输模式尚未实现", Retryable: false, Surfaces: "http,websocket,readiness,plugin_protocol"},
	AdapterTransportReverseWsAuthFailed:       {Code: AdapterTransportReverseWsAuthFailed, HTTPStatus: 401, Message: "OneBot 回连鉴权失败", Retryable: false, Surfaces: "http,websocket,readiness"},
	AdapterTransportReverseWsUpgradeFailed:    {Code: AdapterTransportReverseWsUpgradeFailed, HTTPStatus: 503, Message: "OneBot 回连升级失败", Retryable: true, Surfaces: "http,websocket,readiness"},
	AdapterTransportUnavailable:               {Code: AdapterTransportUnavailable, HTTPStatus: 503, Message: "适配器传输当前不可用", Retryable: false, Surfaces: "http,websocket,logs,plugin_protocol"},
	AdapterTransportWebhookAuthFailed:         {Code: AdapterTransportWebhookAuthFailed, HTTPStatus: 401, Message: "OneBot Webhook 鉴权失败", Retryable: false, Surfaces: "http,websocket,readiness"},
	AdapterTransportWebhookDuplicateEvent:     {Code: AdapterTransportWebhookDuplicateEvent, HTTPStatus: 202, Message: "OneBot Webhook 重复事件已丢弃", Retryable: false, Surfaces: "http,websocket,logs"},
	AdapterTransportWebhookInvalidPayload:     {Code: AdapterTransportWebhookInvalidPayload, HTTPStatus: 400, Message: "OneBot Webhook 负载不合法", Retryable: false, Surfaces: "http,websocket,readiness"},
	PermissionAuthenticationRequired:          {Code: PermissionAuthenticationRequired, HTTPStatus: 401, Message: "请求认证未通过", Retryable: false, Surfaces: "http,websocket"},
	PermissionBlacklisted:                     {Code: PermissionBlacklisted, HTTPStatus: 0, Message: "当前用户或群处于黑名单中", Retryable: false, Surfaces: "plugin_protocol,logs"},
	PermissionCurrentSecretInvalid:            {Code: PermissionCurrentSecretInvalid, HTTPStatus: 403, Message: "当前密码不正确", Retryable: false, Surfaces: "http"},
	PermissionDenied:                          {Code: PermissionDenied, HTTPStatus: 403, Message: "当前用户无权执行该操作", Retryable: false, Surfaces: "http,websocket,plugin_protocol"},
	PermissionNotWhitelisted:                  {Code: PermissionNotWhitelisted, HTTPStatus: 0, Message: "当前用户或群不在白名单中", Retryable: false, Surfaces: "plugin_protocol,logs"},
	PermissionUnavailable:                     {Code: PermissionUnavailable, HTTPStatus: 0, Message: "暂时无法确认权限，本次操作未执行", Retryable: true, Surfaces: "logs"},
	PlatformInternalError:                     {Code: PlatformInternalError, HTTPStatus: 500, Message: "内部错误", Retryable: true, Surfaces: "http,websocket,plugin_protocol,task,readiness"},
	PlatformInvalidConfig:                     {Code: PlatformInvalidConfig, HTTPStatus: 400, Message: "配置校验失败", Retryable: false, Surfaces: "http,websocket,readiness"},
	PlatformInvalidRequest:                    {Code: PlatformInvalidRequest, HTTPStatus: 400, Message: "请求参数不合法", Retryable: false, Surfaces: "http,websocket,task"},
	PlatformRateLimited:                       {Code: PlatformRateLimited, HTTPStatus: 429, Message: "触发平台级限流", Retryable: true, Surfaces: "http,websocket,plugin_protocol"},
	PlatformRenderInputTooLarge:               {Code: PlatformRenderInputTooLarge, HTTPStatus: 413, Message: "渲染输入超过大小限制", Retryable: false, Surfaces: "http,websocket,plugin_protocol,task"},
	PlatformRenderQueueFull:                   {Code: PlatformRenderQueueFull, HTTPStatus: 429, Message: "渲染队列已满", Retryable: true, Surfaces: "http,websocket,plugin_protocol"},
	PlatformRenderTimeout:                     {Code: PlatformRenderTimeout, HTTPStatus: 504, Message: "渲染任务超时", Retryable: true, Surfaces: "http,websocket,plugin_protocol,task"},
	PlatformResourceBusy:                      {Code: PlatformResourceBusy, HTTPStatus: 409, Message: "资源正被占用，请稍后重试", Retryable: true, Surfaces: "http,websocket,plugin_protocol"},
	PlatformResourceMissing:                   {Code: PlatformResourceMissing, HTTPStatus: 503, Message: "缺少必要资源", Retryable: false, Surfaces: "http,websocket,readiness,plugin_protocol"},
	PlatformResourceNotFound:                  {Code: PlatformResourceNotFound, HTTPStatus: 404, Message: "请求的资源不存在", Retryable: false, Surfaces: "http,websocket"},
	PlatformStateConflict:                     {Code: PlatformStateConflict, HTTPStatus: 409, Message: "当前状态不允许执行该操作", Retryable: false, Surfaces: "http,websocket,task"},
	PlatformTaskQueueFull:                     {Code: PlatformTaskQueueFull, HTTPStatus: 429, Message: "后台任务队列已满", Retryable: true, Surfaces: "http,websocket,task"},
	PlatformTaskTimeout:                       {Code: PlatformTaskTimeout, HTTPStatus: 504, Message: "后台任务超时", Retryable: true, Surfaces: "http,websocket,task"},
	PlatformTemplateNotFound:                  {Code: PlatformTemplateNotFound, HTTPStatus: 404, Message: "模板不存在", Retryable: false, Surfaces: "http,task"},
	PlatformUpstreamRequestFailed:             {Code: PlatformUpstreamRequestFailed, HTTPStatus: 502, Message: "上游请求失败", Retryable: true, Surfaces: "http,websocket,plugin_protocol,readiness"},
	PlatformUpstreamResponseTooLarge:          {Code: PlatformUpstreamResponseTooLarge, HTTPStatus: 502, Message: "上游响应超过大小限制", Retryable: false, Surfaces: "http,websocket,plugin_protocol,task"},
	PlatformUserRateLimited:                   {Code: PlatformUserRateLimited, HTTPStatus: 0, Message: "用户命令触发冷却限流", Retryable: true, Surfaces: "plugin_protocol,logs"},
	PlatformValueTooLarge:                     {Code: PlatformValueTooLarge, HTTPStatus: 413, Message: "写入值超过大小限制", Retryable: false, Surfaces: "http,websocket,plugin_protocol"},
	PluginArtifactInvalid:                     {Code: PluginArtifactInvalid, HTTPStatus: 400, Message: "插件产物结构或入口校验失败", Retryable: false, Surfaces: "http,task,plugin_protocol"},
	PluginContractUnsupported:                 {Code: PluginContractUnsupported, HTTPStatus: 409, Message: "插件合同版本不受支持", Retryable: false, Surfaces: "http,task,cli,plugin_protocol,backup,restore,update,readiness"},
	PluginCoreVersionIncompatible:             {Code: PluginCoreVersionIncompatible, HTTPStatus: 409, Message: "插件与当前 RayleaBot 版本不兼容", Retryable: false, Surfaces: "http,task,cli,readiness"},
	PluginEventCanceled:                       {Code: PluginEventCanceled, HTTPStatus: 0, Message: "插件事件处理已取消", Retryable: false, Surfaces: "plugin_protocol,websocket,task,logs"},
	PluginEventTimeout:                        {Code: PluginEventTimeout, HTTPStatus: 0, Message: "插件事件处理超时", Retryable: true, Surfaces: "plugin_protocol,websocket,task"},
	PluginInitTimeout:                         {Code: PluginInitTimeout, HTTPStatus: 0, Message: "插件初始化超时", Retryable: true, Surfaces: "plugin_protocol,websocket,task"},
	PluginInstallDigestMismatch:               {Code: PluginInstallDigestMismatch, HTTPStatus: 409, Message: "插件包与检查结果不一致", Retryable: false, Surfaces: "http,task"},
	PluginInstallFailed:                       {Code: PluginInstallFailed, HTTPStatus: 409, Message: "插件安装失败", Retryable: true, Surfaces: "http,websocket,task"},
	PluginInstallInspectionExpired:            {Code: PluginInstallInspectionExpired, HTTPStatus: 409, Message: "插件包检查结果已过期", Retryable: true, Surfaces: "http,task"},
	PluginInstallInspectionRequired:           {Code: PluginInstallInspectionRequired, HTTPStatus: 409, Message: "请先检查插件包并确认信任", Retryable: false, Surfaces: "http,task"},
	PluginInternalError:                       {Code: PluginInternalError, HTTPStatus: 0, Message: "插件内部处理异常", Retryable: false, Surfaces: "plugin_protocol,websocket,task"},
	PluginManagementActionFailed:              {Code: PluginManagementActionFailed, HTTPStatus: 502, Message: "插件管理操作执行失败", Retryable: false, Surfaces: "http"},
	PluginNotHandled:                          {Code: PluginNotHandled, HTTPStatus: 0, Message: "插件声明不处理该事件", Retryable: false, Surfaces: "plugin_protocol"},
	PluginNotRecoverable:                      {Code: PluginNotRecoverable, HTTPStatus: 409, Message: "插件当前不可恢复", Retryable: false, Surfaces: "http"},
	PluginPackageResourceLimitExceeded:        {Code: PluginPackageResourceLimitExceeded, HTTPStatus: 413, Message: "插件包超过资源限制", Retryable: false, Surfaces: "http,task"},
	PluginPackageUnsafeEntry:                  {Code: PluginPackageUnsafeEntry, HTTPStatus: 400, Message: "插件包包含不安全文件", Retryable: false, Surfaces: "http,task"},
	PluginPermissionDenied:                    {Code: PluginPermissionDenied, HTTPStatus: 403, Message: "插件访问未声明权限", Retryable: false, Surfaces: "http,websocket,plugin_protocol,task"},
	PluginPlatformMismatch:                    {Code: PluginPlatformMismatch, HTTPStatus: 409, Message: "插件产物与当前平台不匹配", Retryable: false, Surfaces: "http,task,readiness"},
	PluginProtocolViolation:                   {Code: PluginProtocolViolation, HTTPStatus: 0, Message: "插件协议违规", Retryable: false, Surfaces: "plugin_protocol,websocket,task"},
	PluginSessionConflict:                     {Code: PluginSessionConflict, HTTPStatus: 0, Message: "当前作用域已有对话，请先结束已有对话", Retryable: false, Surfaces: "plugin_protocol"},
	PluginSettingsApplyFailed:                 {Code: PluginSettingsApplyFailed, HTTPStatus: 409, Message: "设置已保存，运行时应用失败，请重试保存或重载插件", Retryable: true, Surfaces: "http,plugin_protocol,task"},
	PluginShutdown:                            {Code: PluginShutdown, HTTPStatus: 0, Message: "插件运行时已关闭，本地动作结果未确认", Retryable: false, Surfaces: "plugin_protocol"},
	PluginShutdownTimeout:                     {Code: PluginShutdownTimeout, HTTPStatus: 0, Message: "插件优雅退出超时", Retryable: true, Surfaces: "plugin_protocol,websocket,task"},
	PluginStopping:                            {Code: PluginStopping, HTTPStatus: 0, Message: "插件正在停止，不再接受新动作", Retryable: false, Surfaces: "plugin_protocol"},
	PluginStoreCatalogUnavailable:             {Code: PluginStoreCatalogUnavailable, HTTPStatus: 503, Message: "插件商店目录暂不可用", Retryable: true, Surfaces: "http,task"},
	PluginStoreIntegrityMismatch:              {Code: PluginStoreIntegrityMismatch, HTTPStatus: 409, Message: "插件商店产物与目录摘要不一致", Retryable: false, Surfaces: "http,task"},
	PluginStoreReleaseUnavailable:             {Code: PluginStoreReleaseUnavailable, HTTPStatus: 409, Message: "当前平台没有可安装的插件商店产物", Retryable: false, Surfaces: "http,task"},
	PluginStoreSourceConflict:                 {Code: PluginStoreSourceConflict, HTTPStatus: 409, Message: "插件源地址已存在", Retryable: false, Surfaces: "http"},
	PluginStoreSourceImmutable:                {Code: PluginStoreSourceImmutable, HTTPStatus: 409, Message: "官方插件源不能修改或删除", Retryable: false, Surfaces: "http"},
	PluginTrustedCodeConfirmationRequired:     {Code: PluginTrustedCodeConfirmationRequired, HTTPStatus: 403, Message: "必须确认该插件将作为完全可信的本地代码运行", Retryable: false, Surfaces: "http,task"},
	PluginUninstallFailed:                     {Code: PluginUninstallFailed, HTTPStatus: 409, Message: "插件卸载失败", Retryable: true, Surfaces: "http,websocket,task"},
	PluginWebhookReplayRejected:               {Code: PluginWebhookReplayRejected, HTTPStatus: 401, Message: "插件 Webhook 请求已被识别为重复事件", Retryable: false, Surfaces: "http"},
	PluginWebhookTimestampSkew:                {Code: PluginWebhookTimestampSkew, HTTPStatus: 401, Message: "插件 Webhook 请求时间戳超出容忍窗口", Retryable: false, Surfaces: "http"},
	ReleaseManifestInvalid:                    {Code: ReleaseManifestInvalid, HTTPStatus: 502, Message: "发布清单无效", Retryable: false, Surfaces: "http,task,cli"},
}
