import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page, request }) => {
  await request.post('http://127.0.0.1:4010/__test/reset', { data: { initialized: true } })
  await page.goto('/login')
  await page.getByLabel('管理员密钥').fill('fixture-only-secret')
  await page.getByRole('button', { name: /登\s*录/ }).click()
  await expect(page.getByRole('heading', { name: '系统状态', level: 1 })).toBeVisible()
  await page.goto('/config')
  await expect(page.getByRole('textbox', { name: '监听地址', exact: true })).toBeVisible()
})

test('categories and advanced search retain one draft and save it together', async ({ page }) => {
  await page.getByRole('tab', { name: '基础与访问', exact: true }).focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('heading', { name: '图片生成', level: 2 })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '浏览器路径', exact: true })).toHaveCount(0)
  const output = page.getByRole('combobox', { name: '默认生成格式' })
  await expect(output).toHaveAttribute('aria-describedby', 'config-field-render-default_output-description')
  await page.getByRole('spinbutton', { name: '图片精度' }).fill('225')
  await page.getByRole('searchbox', { name: '搜索配置项' }).fill('browser_args')
  await page.getByRole('textbox', { name: '浏览器参数', exact: true }).fill('--disable-gpu\n--disable-dev-shm-usage')
  await page.getByRole('searchbox', { name: '搜索配置项' }).fill('')
  await page.getByRole('tab', { name: '基础与访问' }).click()
  await page.getByRole('spinbutton', { name: '监听端口', exact: true }).fill('23456')
  await expect(page.locator('#config-save-status')).toContainText('3 项未保存')
  const saved = page.waitForRequest(request => request.method() === 'PUT' && request.url().endsWith('/api/config'))
  await page.getByRole('button', { name: '保存更改', exact: true }).click()
  const body = (await saved).postDataJSON()
  expect(body.server.port).toBe(23456)
  expect(body.render.device_scale_percent).toBe(225)
  expect(body.render.browser_args).toEqual(['--disable-gpu', '--disable-dev-shm-usage'])
  await expect(page.getByRole('button', { name: '保存更改', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('spinbutton', { name: '监听端口', exact: true })).toHaveValue('23456')
  await page.getByRole('tab', { name: '图片生成' }).click()
  await expect(page.getByRole('spinbutton', { name: '图片精度' })).toHaveValue('225')
})

test('leaving can retain edits or discard them even when the page is cached', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const port = page.getByRole('spinbutton', { name: '监听端口', exact: true })
  const original = await port.inputValue()
  await port.fill('23456')
  const dashboard = page.locator('.admin-layout__sider').getByText('系统状态', { exact: true })
  await dashboard.click()
  const confirmation = page.getByRole('alertdialog', { name: '离开前放弃修改？' })
  await expect(confirmation).toBeVisible()
  await confirmation.getByRole('button', { name: '继续编辑' }).click()
  await expect(port).toHaveValue('23456')
  await dashboard.click()
  await confirmation.getByRole('button', { name: '放弃并离开' }).click()
  await expect(page).toHaveURL(/\/$/)
  await page.locator('.admin-layout__sider').getByText('配置', { exact: true }).click()
  await expect(port).toHaveValue(original)
  await expect(page.getByRole('button', { name: '保存更改', exact: true })).toBeDisabled()
  expect(errors).toEqual([])
})

test('a failed save is visible even with no search results and can be retried', async ({ page }) => {
  await page.getByRole('spinbutton', { name: '监听端口', exact: true }).fill('23456')
  await page.getByRole('searchbox', { name: '搜索配置项' }).fill('no_such_configuration')
  await expect(page.getByText('没有找到配置项')).toBeVisible()
  await page.route('**/api/config', async route => {
    if (route.request().method() === 'PUT') await route.fulfill({ status: 500, json: { code: 'internal.error', message: 'fixture failure', request_id: 'fixture-config-failure' } })
    else await route.continue()
  })
  await page.getByRole('button', { name: '保存更改', exact: true }).click()
  await expect(page.locator('.config-editor [role=alert]')).toBeVisible()
  await expect(page.getByTestId('config-save')).toHaveAttribute('data-state', 'error')
  await expect(page.locator('#config-save-status')).toContainText('1 项未保存')
  await page.unroute('**/api/config')
  await page.getByRole('button', { name: '清除搜索' }).click()
  await expect(page.getByRole('spinbutton', { name: '监听端口', exact: true })).toHaveValue('23456')
  await page.getByRole('button', { name: '保存更改', exact: true }).click()
  await expect(page.locator('.config-editor [role=alert]')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '保存更改', exact: true })).toBeDisabled()
  await expect(page.getByTestId('config-save')).toHaveAttribute('data-state', 'idle')
})

test('one floating save control signals unsaved changes and stays neutral after saving', async ({ page }) => {
  const save = page.getByTestId('config-save')
  await expect(save).toHaveCount(1)
  await expect(page.locator('.config-savebar')).toHaveCount(0)
  await expect(save).toHaveAttribute('aria-describedby', 'config-save-status')
  let releaseSave: (() => void) | undefined
  await page.route('**/api/config', async route => {
    if (route.request().method() === 'PUT') await new Promise<void>(resolve => { releaseSave = resolve })
    await route.continue()
  })
  for (const [index, theme] of ['light', 'dark'].entries()) {
    await page.emulateMedia({ colorScheme: theme as 'light' | 'dark', reducedMotion: 'reduce' })
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
    await expect(save).toHaveAttribute('data-state', 'idle')
    const neutral = await save.evaluate(element => getComputedStyle(element).backgroundColor)
    await page.getByRole('spinbutton', { name: '监听端口', exact: true }).fill(String(23456 + index))
    await expect(save).toHaveAttribute('data-state', 'dirty')
    await expect(save.locator('.config-save-fab__count')).toHaveText('1')
    expect(await save.evaluate(element => getComputedStyle(element).backgroundColor)).not.toBe(neutral)
    await save.click()
    await expect(save).toHaveAttribute('aria-busy', 'true')
    await expect(save).toHaveAttribute('data-state', 'saving')
    await expect.poll(() => Boolean(releaseSave)).toBe(true)
    releaseSave!()
    releaseSave = undefined
    await expect(save).toHaveAttribute('data-state', 'idle')
    await expect(save.locator('.config-save-fab__count')).toHaveCount(0)
    expect(await save.evaluate(element => getComputedStyle(element).backgroundColor)).toBe(neutral)
  }
})

test('cleared fields show default placeholders and undo floats to the left of save', async ({ page }) => {
  const port = page.getByRole('spinbutton', { name: '监听端口', exact: true })
  const original = await port.inputValue()
  await port.fill('')
  await expect(port).toHaveValue('')
  await expect(port).toHaveAttribute('placeholder', '8080')
  const discard = page.getByTestId('config-discard')
  const save = page.getByTestId('config-save')
  await expect(discard).toBeVisible()
  const left = await discard.boundingBox()
  const right = await save.boundingBox()
  expect(left!.x + left!.width).toBeLessThan(right!.x)
  expect(left!.y + left!.height / 2).toBeCloseTo(right!.y + right!.height / 2, 0)
  await discard.click()
  await expect(port).toHaveValue(original)
  await expect(discard).toHaveCount(0)
  await expect(save).toHaveAttribute('data-state', 'idle')
  await expect(save).toBeFocused()
})

test('an unfinished rate limit remains dirty across category changes and search', async ({ page }) => {
  await page.getByRole('tab', { name: '运行与请求' }).click()
  await page.getByRole('button', { name: /进程、队列与网络边界/ }).click()
  const count = page.getByRole('spinbutton', { name: 'IPC 突发限制 次数' })
  const original = await count.inputValue()
  await count.fill('')
  await expect(page.getByTestId('config-save')).toHaveAttribute('data-state', 'dirty')
  await page.getByRole('tab', { name: '图片生成', exact: true }).click()
  await page.getByRole('tab', { name: '运行与请求' }).click()
  await expect(count).toHaveValue('')
  await expect(page.getByRole('spinbutton', { name: 'IPC 突发限制 时间窗口' })).toHaveValue('1')
  await page.getByRole('searchbox', { name: '搜索配置项' }).fill('browser_args')
  await page.getByRole('searchbox', { name: '搜索配置项' }).fill('')
  await expect(count).toHaveValue('')
  await page.getByTestId('config-discard').click()
  await expect(count).toHaveValue(original)
  await expect(page.getByTestId('config-save')).toHaveAttribute('data-state', 'idle')
})

test('the workbench stays bounded on wide screens and usable on narrow screens', async ({ page }) => {
  await page.setViewportSize({ width: 2560, height: 1440 })
  expect((await page.locator('.config-workbench-page').boundingBox())!.width).toBeLessThanOrEqual(1120)
  await expect(page.getByRole('combobox', { name: '配置分类' })).toBeHidden()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await expect(page.getByRole('tablist', { name: '配置分类' })).toBeHidden()
  await page.getByRole('combobox', { name: '配置分类' }).click()
  await page.getByRole('option', { name: '运行与请求' }).click()
  await page.getByRole('button', { name: /进程、队列与网络边界/ }).click()
  await page.getByRole('spinbutton', { name: 'IPC 突发限制 次数' }).fill('200')
  await expect(page.locator('#config-save-status')).toContainText('1 项未保存')
  const saveBounds = await page.getByRole('button', { name: '保存更改', exact: true }).boundingBox()
  expect(saveBounds!.height).toBeGreaterThanOrEqual(44)
  expect(saveBounds!.y + saveBounds!.height).toBeLessThanOrEqual(844)
  for (const width of [390, 320, 768, 1024]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.locator('.admin-layout__content').evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
  }
})
