import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page, request }) => {
  await request.post('http://127.0.0.1:4010/__test/reset', { data: { initialized: true } })
  await page.goto('/login')
  await page.getByLabel('管理员密钥').fill('fixture-only-secret')
  await page.getByRole('button', { name: /登\s*录/ }).click()
  await expect(page.getByRole('heading', { name: '系统状态', level: 1 })).toBeVisible()
})

test('shell preferences retain values and release focus after a menu opens the drawer', async ({ page }) => {
  await page.getByTestId('header-more').click()
  await page.getByTestId('header-settings').click()
  const drawer = page.getByTestId('preferences-drawer')
  await expect(drawer).toHaveCSS('opacity', '1')
  expect(await drawer.evaluate(el => el.getBoundingClientRect().height)).toBe(await page.evaluate(() => innerHeight))
  await expect(drawer.getByRole('button', { name: '关闭弹窗' })).toBeFocused()
  await drawer.getByRole('radio', { name: '紧凑', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-density', 'compact')
  await drawer.getByRole('tab', { name: '工作区', exact: true }).click()
  const tabSwitch = drawer.getByRole('switch').first()
  await tabSwitch.click()
  await expect(tabSwitch).toHaveAttribute('aria-checked', 'false')
  await page.keyboard.press('Escape')
  await expect(drawer).toHaveCount(0)
  await expect(page.getByTestId('header-more')).toBeFocused()
  await expect(page.locator('body')).not.toHaveCSS('pointer-events', 'none')
  await expect(page.getByRole('tablist', { name: '工作区页签' })).toHaveCount(0)
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-density', 'compact')
  await page.getByTestId('header-more').click()
  await page.getByTestId('header-settings').click()
  await page.getByRole('button', { name: '恢复默认设置' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-density', 'default')
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('header-more')).toBeFocused()
  await expect(page.getByRole('tablist', { name: '工作区页签' })).toBeVisible()
})

test('shell search supports keyboard navigation and restores its trigger after cancellation', async ({ page }) => {
  const trigger = page.getByTestId('header-search')
  await trigger.click()
  const search = page.getByTestId('route-search-modal')
  const input = search.getByRole('textbox')
  await expect(input).toBeFocused()
  await input.fill('协议中心')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/protocols$/)
  await expect(search).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '协议中心', level: 1 })).toBeVisible()
  await trigger.click()
  await expect(input).toBeFocused()
  await input.fill('没有这个页面')
  await expect(search.locator('.app-empty-state')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(search).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Control+k')
  await expect(input).toBeFocused()
})

test('collapsed sidebar menus remain keyboard accessible and keep open plugin targets', async ({ page }) => {
  await page.goto('/plugins/weather')
  await expect(page.getByRole('heading', { name: /weather/i, level: 1 })).toBeVisible()
  await page.getByRole('button', { name: '折叠侧栏' }).click()
  const trigger = page.locator('.admin-layout__sider [data-sidebar-entry=plugin-center]')
  await trigger.focus()
  await page.keyboard.press('ArrowDown')
  const menu = page.getByRole('menu')
  await expect(menu).toBeVisible()
  await expect(menu.getByRole('menuitem').first()).toBeFocused()
  await expect(menu.locator('[data-sidebar-open-plugin-id=weather]')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(menu).toHaveCount(0)
  await expect(trigger).toBeFocused()
})

test('shell tooltips use a readable width independent of spacing tokens', async ({ page }) => {
  for (const id of ['header-search']) {
    await page.getByTestId(id).hover()
    const tooltip = page.locator('[data-slot=tooltip-content]')
    await expect(tooltip).toBeVisible()
    const bounds = await tooltip.boundingBox()
    expect(bounds?.width).toBeGreaterThan(40)
    expect(bounds?.height).toBeLessThan(40)
    await page.mouse.move(500, 500)
    await expect(tooltip).toHaveCount(0)
  }
})
