name: race

on:
  workflow_dispatch:

jobs:
  go-race:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod

      - name: Run go test -race
        working-directory: server
        run: go test -race ./...
