// Code generated by scripts/generate-plugin-wire.py from contracts; DO NOT EDIT.

package contractversions

const (
	PluginProtocolVersion = "3"
	PluginManifestVersion = "3"
	PluginArtifactVersion = "2"
	PluginUIBridgeVersion = "3"
	BackupManifestVersion = "3"
	ConfigSchemaVersion   = "4"
	DepsManifestVersion   = 5
	UpdateProtocolVersion = 2
)
