// Code generated by tools/cmd/generate-plugin-wire from contracts; DO NOT EDIT.

package contractversions

const (
	PluginProtocolVersion = "4"
	PluginManifestVersion = "4"
	PluginArtifactVersion = "2"
	BackupManifestVersion = "3"
	ConfigSchemaVersion   = "4"
	DepsManifestVersion   = 5
)
